NVMe-oF 개요 기술 블로그 포스트
gluesys/tech-blog pull request #104
Opened 2022-08-19 09:35 UTC by john3991005

NVMe-oF의 개요에 대한 포스트입니다.

2022-08-20 09:31 UTC, kjy8901 approved these changes

2022-08-21 10:44 UTC, potatogim requested changes
리뷰 남깁니다~!

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +tags:       [NVMe, NVMe-oF, NVMe over Fabrics, RDMA, Storage, SSD, RoCE, iWARP, 파이버채널, Fibre Channel, 이더넷, Ethernet, TCP]
* 파이버채널 -> 파이버 채널

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +현재 스토리지 인터페이스의 주류인 SATA/SAS 인터페이스는 디스크가 회전하는 기계인 하드디스크에 최적화되었기 때문에, 전기 신호로 데이터를 읽고 쓰는 SSD에 적합하지 않습니다. 헤드 탐색시간이나 회전 지연시간 설정과 같이 불필요한 기능들이 많고, 순차적인 명령어 큐 또한 순차적으로 처리하기 때문에 플래시의 본래 성능을 끌어내기 어려웠습니다. 여기서
* 디스크가 회전하는 기계인 -> 플래터가 회전하며 데이터를 읽고 쓰는
* 헤드 탐색 시간과 회전 지연 시간이 불필요하다기보다 HDD에서의 물리적인 구동부로 인해 생기는 비효율성을 서술하는게 좋겠네요.
    * `~ 같이 불필요한 기능들이 많고` -> `~ 같이 물리적인 입출력 구조를 갖지 않는 SSD에서는 불필요한 고려가 전제되어 있고`
* 이미 큐가 순차적으로 처리된다고 표현했기 때문에 뒤쪽에 다시 순차적인 처리를 중복해서 서술할 필요는 없어 보이네요~!

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +초창기에는 NVMe SSD 스토리지 미디어를 직접연결(DAS) 방식으로 사용했습니다. 하지만, PCIe 인터페이스를 통해 SSD 장치를 연결하는 NVMe 프로토콜 만으로는 그 이점이 어플라이언스에만 한정되고, 더불어 이러한 고속 스토리지를 독립적으로 사용하기에는 비용 대비 효율이 나지 않습니다. 이러한 NVMe 프로토콜을 네트워크 프로토콜로 활용하고자 *
* 직접연결 -> 직접 연결
* 비용 대비 효율이 나지 않습니다 -> 비용 대비 효율이 상대적으로 높지 않습니다

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe over Fabrics는 말 그대로 NVMe 프로토콜로 다양한 네트워크들(fabrics)을 통해 NVMe 장치들을 연결할 수 있게 해주는 네트워크 프로토콜의 개념입니다. 쉽게 말해, NVMe-oF는 네트워크를 통해 NVMe 프로토콜로 원격 장치에 접근하는 방식이라고 볼 수 있습니다. NVMe-oF는 지난 2016년, NVMe 사양을 정의한 NVM
* `NVMe over Fabrics` -> `NVMe over Fabrics(이하 NVMe-oF)`

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe 프로토콜은 로컬의 PCIe 스위치나 PCIe 버스를 통해 NVMe 장치들에 접근하지만, NVMe-oF 기술을 활용하면 파이버채널이나 이더넷과 같은 네트워크를 통해 네트워크 상에 존재하는 NVMe 장치에도 접근할 수 있게 됩니다. 무엇보다, NVMe-oF는 전용 네트워크가 아닌 기존의 파이버채널과 이더넷 환경을 활용하기 때문에 별도의 네트워크 환경
* 파이버채널 -> 파이버 채널

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe-oF는 파이버채널과 이더넷 기반의 RDMA 및 TCP/IP 환경에서 활용할 수 있습니다.
* 파이버채널 -> 파이버 채널

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +파이버채널을 활용하는 **NVMe/FC**는 기존에 파이버채널이 구축된 환경에서 도입이 가능합니다. 파이버채널은 기본적으로 SCSI와 NVMe 프로토콜을 동시에 매핑 가능하기 때문에, 파이버채널 기반의 인프라를 보유한 데이터센터에서 스위치의 소프트웨어 업그레이드를 통해 쉽게 도입할 수 있습니다. 다만, 이더넷 기반의 인프라에 비해 외부 네트워크와의 연결이
* 파이버채널 -> 파이버 채널

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +이더넷을 활용하는 NVMe-oF는 기본적으로 RDMA 기술을 활용합니다. 이전 포스트인 [스토리지 기초 지식 2편: 스토리지 프로토콜](https://tech.gluesys.com/blog/2019/12/17/storage_2_intro.html) 에서도 다루었습니다만, **RDMA(Remote Direct Access Memory)**는 같은 네트워크
* `NVMe-oF 캡슐` -> `NVMe-oF 프로토콜 패킷을 캡슐화하여`

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +기존에 이더넷 기반 인프라를 보유하고 있는 경우에는 네트워크 카드 추가 구축을 통해 도입이 가능하고, NVMe/RoCE의 경우에는 주로 매우 낮은 지연시간을 목표로 물리적으로 컴퓨팅 자원과 가깝게 단일 랙 환경에서 구축합니다. 이러한 RDMA 기반의 NVMe-oF는 워크로드 유형이나 인프라 규모에 따라 비교적 낮은 CPU 사용률과 마이크로초 수준의 지연시
* 지연시간 -> 지연 시간(Latency)

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +최근에는 TCP/IP를 기반으로 하는 **NVMe/TCP**가 주목받고 있습니다. 기존의 이더넷이나 파이버채널 기반의 NVMe-oF를 도입하는 경우, 별도의 호스트 어댑터나 드라이버 등의 조정이 필요해, 비용 및 복잡도 문제가 있었습니다. 하지만, NVMe-oF 1.1 버전에서부터 TCP 전송 바인딩을 지원하게 되면서 TCP/IP를 통해 NVMe-oF 캡
* 파이버채널 -> 파이버 채널
* NVMe-oF 캡슐 -> 상동

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +TCP 전송 바인딩은 어떠한 이더넷 네트워크 상에서도 사용할 수 있기 때문에 어떠한 표준 이더넷 어댑터나 범용 하드웨어와도 호환된다는 이점이 있습니다. 이로 인해, NVMe-oF를 별도의 설정 없이 도입 및 확장이 가능합니다. 특히, 파이버채널 기반 인프라가 없으면서 RDMA를 사용하지 않는 이더넷 기반 인프라에 NVMe-oF를 도입할 수 있습니다. NV
* 파이버채널 -> 파이버 채널
* 사일로화라는 용어에 대해 풀어서 서술할 수 있으면 좋을 것 같고, 어렵다면 용어 참조를 달아주는게 좋겠네요.

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe-oF 도입의 가장 큰 목적은 바로 NVMe 기반의 분산 스토리지 네트워크를 형성해 원격의 NVMe 장치의 지연시간을 로컬 수준으로 구현할 수 있다는 것에 있습니다. 이로 인해 고성능 저 지연 스토리지 워크로드를 필요로 하는 대규모 데이터센터에서 수요가 있을 것으로 보입니다. AI/머신러닝 분야의 경우, 대규모 데이터셋 훈련 시 GPU의 RAM의
* `GPU의 RAM의` -> `GPU 메모리의`
* 초 저 지연 -> 초저지연
* 지연시간 -> 지연 시간
* 분석 애플리케이션에 보다 많은 데이터를 제공 가능하게 -> 분석 애플리케이션이 동시간대비(혹은 동일 시간 내에) 더욱 많은 데이터를 처리할 수 있게

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +[지난 포스트](https://tech.gluesys.com/blog/2021/11/15/cxl_1.html) 에서 다룬 **CXL(Compute Express Link)** 인터커넥트의 경우, NVMe와 같이 PCIe를 활용하긴 하지만, 한동안은 경쟁 보다는 공존할 것으로 보입니다. CXL은 호스트 프로세서와 CXL 장치 간 메모리를 공유할 수 있어 서
* 경쟁 보다는 -> 경쟁보다는

2022-08-21 10:44 UTC, potatogim commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +클라우드와 고성능 컴퓨팅 환경이 점차 보편화 되면서 데이터센터 내 스토리지 성능에 대한 요구는 점점 커져가고 있습니다. NVMe-oF는 NVMe 장치를 노드 바깥의 네트워크 상에서 접근할 수 있게 해 차세대 플래시 미디어의 표준이 될 NVMe 기술을 한 단계 업그레이드했다는 평가를 받고 있습니다. NVMe-oF는 아직 등장한지 얼마 안된 기술로, 도입 시
* 보편화 되면서 -> 보편화되면서

2022-08-22 02:09 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +tags:       [NVMe, NVMe-oF, NVMe over Fabrics, RDMA, Storage, SSD, RoCE, iWARP, 파이버채널, Fibre Channel, 이더넷, Ethernet, TCP]
띄어서 수정 완료했습니다~!

2022-08-22 02:09 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +현재 스토리지 인터페이스의 주류인 SATA/SAS 인터페이스는 디스크가 회전하는 기계인 하드디스크에 최적화되었기 때문에, 전기 신호로 데이터를 읽고 쓰는 SSD에 적합하지 않습니다. 헤드 탐색시간이나 회전 지연시간 설정과 같이 불필요한 기능들이 많고, 순차적인 명령어 큐 또한 순차적으로 처리하기 때문에 플래시의 본래 성능을 끌어내기 어려웠습니다. 여기서
전부 제안하신 대로 변경 했습니다~!

2022-08-22 02:09 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +초창기에는 NVMe SSD 스토리지 미디어를 직접연결(DAS) 방식으로 사용했습니다. 하지만, PCIe 인터페이스를 통해 SSD 장치를 연결하는 NVMe 프로토콜 만으로는 그 이점이 어플라이언스에만 한정되고, 더불어 이러한 고속 스토리지를 독립적으로 사용하기에는 비용 대비 효율이 나지 않습니다. 이러한 NVMe 프로토콜을 네트워크 프로토콜로 활용하고자 *
전부 변경 완료했습니다~!

2022-08-22 02:09 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe over Fabrics는 말 그대로 NVMe 프로토콜로 다양한 네트워크들(fabrics)을 통해 NVMe 장치들을 연결할 수 있게 해주는 네트워크 프로토콜의 개념입니다. 쉽게 말해, NVMe-oF는 네트워크를 통해 NVMe 프로토콜로 원격 장치에 접근하는 방식이라고 볼 수 있습니다. NVMe-oF는 지난 2016년, NVMe 사양을 정의한 NVM
변경 했습니다~!

2022-08-22 02:09 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe 프로토콜은 로컬의 PCIe 스위치나 PCIe 버스를 통해 NVMe 장치들에 접근하지만, NVMe-oF 기술을 활용하면 파이버채널이나 이더넷과 같은 네트워크를 통해 네트워크 상에 존재하는 NVMe 장치에도 접근할 수 있게 됩니다. 무엇보다, NVMe-oF는 전용 네트워크가 아닌 기존의 파이버채널과 이더넷 환경을 활용하기 때문에 별도의 네트워크 환경
띄어서 썼습니다~!

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe-oF는 파이버채널과 이더넷 기반의 RDMA 및 TCP/IP 환경에서 활용할 수 있습니다.
띄어쓰기 했습니다~!

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +파이버채널을 활용하는 **NVMe/FC**는 기존에 파이버채널이 구축된 환경에서 도입이 가능합니다. 파이버채널은 기본적으로 SCSI와 NVMe 프로토콜을 동시에 매핑 가능하기 때문에, 파이버채널 기반의 인프라를 보유한 데이터센터에서 스위치의 소프트웨어 업그레이드를 통해 쉽게 도입할 수 있습니다. 다만, 이더넷 기반의 인프라에 비해 외부 네트워크와의 연결이
띄어쓰기 수정 했습니다~!

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +이더넷을 활용하는 NVMe-oF는 기본적으로 RDMA 기술을 활용합니다. 이전 포스트인 [스토리지 기초 지식 2편: 스토리지 프로토콜](https://tech.gluesys.com/blog/2019/12/17/storage_2_intro.html) 에서도 다루었습니다만, **RDMA(Remote Direct Access Memory)**는 같은 네트워크
그대로 변경했습니다~!

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +기존에 이더넷 기반 인프라를 보유하고 있는 경우에는 네트워크 카드 추가 구축을 통해 도입이 가능하고, NVMe/RoCE의 경우에는 주로 매우 낮은 지연시간을 목표로 물리적으로 컴퓨팅 자원과 가깝게 단일 랙 환경에서 구축합니다. 이러한 RDMA 기반의 NVMe-oF는 워크로드 유형이나 인프라 규모에 따라 비교적 낮은 CPU 사용률과 마이크로초 수준의 지연시
`지연 시간(latency)`으로 수정했습니다~!

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +최근에는 TCP/IP를 기반으로 하는 **NVMe/TCP**가 주목받고 있습니다. 기존의 이더넷이나 파이버채널 기반의 NVMe-oF를 도입하는 경우, 별도의 호스트 어댑터나 드라이버 등의 조정이 필요해, 비용 및 복잡도 문제가 있었습니다. 하지만, NVMe-oF 1.1 버전에서부터 TCP 전송 바인딩을 지원하게 되면서 TCP/IP를 통해 NVMe-oF 캡
동일하게 적용했습니다~!

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +TCP 전송 바인딩은 어떠한 이더넷 네트워크 상에서도 사용할 수 있기 때문에 어떠한 표준 이더넷 어댑터나 범용 하드웨어와도 호환된다는 이점이 있습니다. 이로 인해, NVMe-oF를 별도의 설정 없이 도입 및 확장이 가능합니다. 특히, 파이버채널 기반 인프라가 없으면서 RDMA를 사용하지 않는 이더넷 기반 인프라에 NVMe-oF를 도입할 수 있습니다. NV
* 띄어서 썼습니다~!
 * 사일로 부분은 없애고 `특히 초기에 비싼 비용으로 NVMe 기반 플래시 어레이를 도입한 기업의 경우, 별도의 추가 네트워크 구축 없이 TCP/IP 네트워크를 통해 NVMe 플래시 어레이의 NVMe 스토리지 자원을 공유할 수 있게 되었습니다.` 로 문장을 수정했습니다.

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe-oF 도입의 가장 큰 목적은 바로 NVMe 기반의 분산 스토리지 네트워크를 형성해 원격의 NVMe 장치의 지연시간을 로컬 수준으로 구현할 수 있다는 것에 있습니다. 이로 인해 고성능 저 지연 스토리지 워크로드를 필요로 하는 대규모 데이터센터에서 수요가 있을 것으로 보입니다. AI/머신러닝 분야의 경우, 대규모 데이터셋 훈련 시 GPU의 RAM의
그대로 변경 완료 했습니다~!

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +[지난 포스트](https://tech.gluesys.com/blog/2021/11/15/cxl_1.html) 에서 다룬 **CXL(Compute Express Link)** 인터커넥트의 경우, NVMe와 같이 PCIe를 활용하긴 하지만, 한동안은 경쟁 보다는 공존할 것으로 보입니다. CXL은 호스트 프로세서와 CXL 장치 간 메모리를 공유할 수 있어 서
띄어쓰기 수정했습니다~!

2022-08-22 02:10 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +클라우드와 고성능 컴퓨팅 환경이 점차 보편화 되면서 데이터센터 내 스토리지 성능에 대한 요구는 점점 커져가고 있습니다. NVMe-oF는 NVMe 장치를 노드 바깥의 네트워크 상에서 접근할 수 있게 해 차세대 플래시 미디어의 표준이 될 NVMe 기술을 한 단계 업그레이드했다는 평가를 받고 있습니다. NVMe-oF는 아직 등장한지 얼마 안된 기술로, 도입 시
띄어쓰기 붙였습니다~!

2022-08-22 07:08 UTC, potatogim approved these changes

2022-08-23 02:29 UTC, Gh0stSp1der approved these changes
좋은 글 잘 읽었습니다.
입사 초기에 NVMeoF에 대해서 여러 용어들을 헷갈려가며 공부했었던 기억이 떠오르네요.
다른 리뷰와 마찬가지로 의견일 뿐이니 참고되시면 좋을 것 같습니다.

2022-08-23 02:29 UTC, Gh0stSp1der commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +&nbsp;
마무리로 세 개의 유형을 비교할 수 있는 표가 추가되어도 좋을 것 같습니다. (주형씨가 포스터가 짧다고 느껴진다면?)
||NVMe/FC|NVMe/RDMA|NVMe/TCP
|---|---|---|---|
|하드웨어 요구사항|FC 환경|PFC 구성된 ethernet 환경(RoCE), IP를 사용한 ethernet 환경(iWARP)|Ethernet 환경|
|RDMA 지원 여부| 지원 | 지원 | 지원 |
|초기 구축 비용| SW 업그레이드 필요 | 스위치에서 PFC 지원 여부 확인 | 없음 |
|성능|?|?|?|
|...|...|...|...|

2022-08-23 02:29 UTC, Gh0stSp1der commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe-oF 도입의 가장 큰 목적은 바로 NVMe 기반의 분산 스토리지 네트워크를 형성해 원격의 NVMe 장치의 지연 시간을 로컬 수준으로 구현할 수 있다는 것에 있습니다. 이로 인해 고성능 저 지연 스토리지 워크로드를 필요로 하는 대규모 데이터센터에서 수요가 있을 것으로 보입니다. AI/머신러닝 분야에서 대규모 데이터셋을 훈련 시키는 경우, GPU 메
`특히 AI/머신러닝 분야에서 대규모 데이터셋을 훈련 시키는 경우 GPU의 성능에 따라 병목이 발생할 수 있는데, NVMe-oF를 활용하면 GPU가 NVMe 스토리지 풀에 직접 접근할 수 있어 분석 애플리케이션이 동일 시간 내에 더욱 많은 데이터를 처리할 수 있게 됩니다.`

2022-08-23 02:29 UTC, Gh0stSp1der commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +클라우드와 고성능 컴퓨팅 환경이 점차 보편화되면서 데이터센터 내 스토리지 성능에 대한 요구는 점점 커져가고 있습니다. NVMe-oF는 NVMe 장치를 노드 바깥의 네트워크 상에서 접근할 수 있게 해 차세대 플래시 미디어의 표준이 될 NVMe 기술을 한 단계 업그레이드했다는 평가를 받고 있습니다. NVMe-oF는 아직 등장한지 얼마 안된 기술로, 도입 시
`접근할 수 있게 해 차세대 플래시 미디어의 ...` -> `접근할 수 있게하여 차세대 플래시 미디어의 ...`
`NVMe-oF는 아직 등장한지 얼마 안된 기술로,` -> `NVMe-oF는 아직 등장한지 얼마 안 된 기술로,`

2022-08-23 02:29 UTC, Gh0stSp1der commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +
만약 당장 도입을 한다면? 어떤 순서로 도입하면 좋을지에 대한 안내도 있으면 좋을 것 같습니다.


현재 구성된 네트워크 인프라에서 NVMe SSD를 이용한 고성능 스토리지를 활용할 계획이 있을 경우 다음과 같은 방법으로 접근한다면 비용 절감에 도움이 될 것 같습니다.
먼저 이더넷 환경의 경우 NVMe 스토리지를 이터넷 스위치와 연결 후 NVMe/TCP를 이용하여 스토리지 외 추가 장비 없이 기존 서버에서 접근할 수 있습니다. 이후 NVMe 스토리지의 요구사항이 높아질 경우 한 단계 높은 대역폭을 갖는 이더넷 네트워크로 확장하는 방법이나, 인피니밴드를 이용한 별도의 네트워크를 추가로 구성할 수 있습니다.
파이버채널 환경의 경우 마찬가지로 NVMe 스토리지를 FC 스위치와 연결 후, NVMe/FC를 이용하여 서버에서 접근할 수 있습니다. 이후 사용 빈도가 높아질 경우 앞선 설명과 마찬가지로 별도의 네트워크 확장을 통해 서버의 요구사항을 만족할 수 있습니다.

필요에 따라서 넣어도, 넣지 않으셔도 괜찮습니다.

2022-08-23 02:56 UTC, lhjnano commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +이더넷을 활용하는 NVMe-oF는 기본적으로 RDMA 기술을 활용합니다. 이전 포스트인 [스토리지 기초 지식 2편: 스토리지 프로토콜](https://tech.gluesys.com/blog/2019/12/17/storage_2_intro.html) 에서도 다루었습니다만, **RDMA(Remote Direct Access Memory)**는 같은 네트워크
**RDMA(Remote Direct Access Memory)** 가 **RDMA(Remote Direct Memory Access)** 로 변경되어야 할 거 같습니다.

2022-08-23 07:51 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +이더넷을 활용하는 NVMe-oF는 기본적으로 RDMA 기술을 활용합니다. 이전 포스트인 [스토리지 기초 지식 2편: 스토리지 프로토콜](https://tech.gluesys.com/blog/2019/12/17/storage_2_intro.html) 에서도 다루었습니다만, **RDMA(Remote Direct Access Memory)**는 같은 네트워크
오 매의 눈 감사합니다~!

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +현재 스토리지 인터페이스의 주류인 SATA/SAS 인터페이스는 플래터가 회전하면서 데이터를 읽고 쓰는 하드디스크에 최적화되었기 때문에, 전기 신호로 데이터를 읽고 쓰는 SSD에 적합하지 않습니다. 헤드 탐색시간이나 회전 지연 시간 설정과 같이 물리적인 입출력 구조를 갖지 않는 SSD에서는 불필요한 고려가 전제되어 있고, 명령어 큐 또한 순차적으로 처리하기
전부 그대로 적용 했습니다~!

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +첫 NVMe 칩셋이 등장한 2012년 8월부터[^1] 정확히 10년 후인 지금, NVMe는 SSD 기술을 주도하는 핵심 프로토콜이 되었습니다. 시장조사 기관에 의하면, NVMe SSD는 기업용 SSD 시장에서 이미 2018년에 SATA나 SAS 기반의 SSD를 넘어 40%의 점유율을 기록한 바 있습니다[^2]. 이처럼 NVMe SSD 기술은 일반 소비자
변경했습니다~!

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +초창기에는 NVMe SSD 스토리지 미디어를 직접 연결(DAS) 방식으로 사용했습니다. 하지만, PCIe 인터페이스를 통해 SSD 장치를 연결하는 NVMe 프로토콜 만으로는 그 이점이 어플라이언스에만 한정되고, 더불어 이러한 고속 스토리지를 독립적으로 사용하기에는 비용 대비 효율이 상대적으로 높지 않습니다. 이러한 NVMe 프로토콜을 네트워크 프로토콜로
`하지만, NVMe 프로토콜의 이점이 스토리지 벤더의 하드웨어에 종속된 어플라이언스에만 한정되고, NVMe SSD로 구성된 고속의 스토리지를 공유 방식이 아닌 독립적으로만 사용하기에는 비용 대비 효율이 떨어진다는 문제가 있습니다. ` 로 내용을 다듬어 보았습니다~!

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +
말씀대로 허전하긴 하지만... 그림을 만들기에는 시간관계상 스킵하는게 좋을 것 같습니다....ㅠㅠ

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +TCP 전송 바인딩은 어떠한 이더넷 네트워크 상에서도 사용할 수 있기 때문에 어떠한 표준 이더넷 어댑터나 범용 하드웨어와도 호환된다는 이점이 있습니다. 이로 인해, NVMe-oF를 별도의 설정 없이 도입 및 확장이 가능합니다. 특히, 파이버 채널 기반 인프라가 없으면서 RDMA를 사용하지 않는 이더넷 기반 인프라에 NVMe-oF를 도입할 수 있습니다. N
`특히, 기존 인프라가 파이버 채널 기반이 아니거나,` 로 변경해 보았습니다~!

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +&nbsp;
말씀대로 추가해 보았습니다. 검토 부탁드립니다~!

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +NVMe-oF 도입의 가장 큰 목적은 바로 NVMe 기반의 분산 스토리지 네트워크를 형성해 원격의 NVMe 장치의 지연 시간을 로컬 수준으로 구현할 수 있다는 것에 있습니다. 이로 인해 고성능 저 지연 스토리지 워크로드를 필요로 하는 대규모 데이터센터에서 수요가 있을 것으로 보입니다. AI/머신러닝 분야에서 대규모 데이터셋을 훈련 시키는 경우, GPU 메
그대로 변경했습니다~!

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +클라우드와 고성능 컴퓨팅 환경이 점차 보편화되면서 데이터센터 내 스토리지 성능에 대한 요구는 점점 커져가고 있습니다. NVMe-oF는 NVMe 장치를 노드 바깥의 네트워크 상에서 접근할 수 있게 해 차세대 플래시 미디어의 표준이 될 NVMe 기술을 한 단계 업그레이드했다는 평가를 받고 있습니다. NVMe-oF는 아직 등장한지 얼마 안된 기술로, 도입 시
그대로 반영했습니다~!

2022-08-23 08:36 UTC, john3991005 commented on _posts/blog/2022-08-22-nvmeof_intro.markdown
> +
내용이 좋아보여 다음과 같이 적용했습니다:
`현재 구성된 네트워크 인프라에서 NVMe SSD가 탑재된 고성능 스토리지를 활용할 계획이 있을 경우, 다음과 같은 방법으로 접근한다면 비용 절감에 도움이 될 것 같습니다.  
먼저 이더넷 환경의 경우, NVMe 스토리지를 이터넷 스위치에 연결 후 NVMe/TCP를 이용하면 스토리지 외 추가 장비 없이도 기존 서버에서 접근할 수 있습니다. 이후 NVMe 스토리지의 요구사항이 높아지게 되면 한 단계 높은 대역폭을 갖는 이더넷 네트워크로 확장하거나, 인피니밴드를 이용한 별도의 네트워크를 추가로 구성하는 방법이 있겠습니다.
파이버 채널 환경의 경우에도 동일하게 NVMe 스토리지를 파이버 채널 스위치와 연결한 후, NVMe/FC를 이용하면 서버에서 접근할 수 있습니다. 이후 사용 빈도가 높아질 경우에는 마찬가지로 별도의 네트워크 확장을 통해 서버의 요구사항을 만족할 수 있습니다.`

2022-08-24 08:19 UTC, merged