xiRAID post
gluesys/tech-blog pull request #112
Opened 2023-01-05 10:16 UTC by hspark0582

xiRAID와 GRAID의 성능을 비교해 보았습니다.

2023-01-05 10:23 UTC, potatogim requested changes

2023-01-05 10:23 UTC, potatogim commented on _posts/blog/2023-01-06-xiRAID.markdown
> +## 다른 어플리케이션을 같이 구동해야 한다면?
s/어플리케이션/애플리케이션/

2023-01-05 10:24 UTC, kjy8901 approved these changes
맞춤법검사 한번만 돌려주십셔~

2023-01-05 10:27 UTC, hspark0582 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +## 다른 어플리케이션을 같이 구동해야 한다면?
앗 다른 곳은 검사기가 고치라고 해서 고쳤는데 소제목들은 맞춤법 검사를 안 했더니 이런 참사가

2023-01-06 05:58 UTC, john3991005 approved these changes
작성하시느라 고생 많으셨습니다. 일단은 미리 어프루브 해 놓도록 하겠습니다.

2023-01-06 05:58 UTC, john3991005 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +| 리빌드 중 4k 무작위 쓰기 | 8M IOPS | 1.1M IOPS | 18K IOPS |
* 띄어쓰기: 리빌드 부분 IOPS 단위의 띄어쓰기 통일이 필요해 보입니다.
 * 오타: `4k` --> `4K`, `512k` --> `512K`

2023-01-06 05:58 UTC, john3991005 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +제일 먼저 살펴볼 것은 xiRAID 사에서 발표한 성능 비교 결과입니다.
* 표기 오류: `...xiRAID 사에서 발표한...` 에서 기업 명을 잘못 쓰신 것 같습니다. 
제안--> `...Xinnor사에서 발표한 xiRAID와 SupremeRAID의 성능 비교...`

2023-01-06 05:58 UTC, john3991005 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +이 표의 결과만을 놓고 보자면 xiRAID가 SupremeRAID(위 표에서 GPU 하드웨어 RAID로 언급)에 비해 월등히 좋은 모습을 보여주고 있고, 4k 무작위 쓰기는 그 차이가 7배를 넘어갑니다.
* 확인 필요: `...SupremeRAID(위 표에서 GPU 하드웨어 RAID로 언급)...` 여기서 `(위 표...`가 아니라 `(출처에서는...` 로 수정이 필요해 보입니다.
 * 오타: `4k` --> `4K`

2023-01-06 05:58 UTC, john3991005 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +| 1MiB 순차 쓰기 | 5276 MiB/s | 3826 MiB/s |
* 의견: 이왕이면 천 단위 숫자는 쉼표로 구분하면 좋을 것 같습니다. 예: `2,451 kIOPS`
 * 오타: `4kiB` --> `4KiB`

2023-01-06 05:58 UTC, john3991005 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +| 1MiB 순차 쓰기 | 3826 MiB/s | 3450 MiB/s | -376 MiB/s | -9.8% |
* 의견: 이왕이면 천 단위 숫자는 쉼표로 구분
 * 오타: `4kiB` --> `4KiB`

2023-01-06 06:10 UTC, hspark0582 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +이 표의 결과만을 놓고 보자면 xiRAID가 SupremeRAID(위 표에서 GPU 하드웨어 RAID로 언급)에 비해 월등히 좋은 모습을 보여주고 있고, 4k 무작위 쓰기는 그 차이가 7배를 넘어갑니다.
원래는 받아적은 위 표에서도 GPU 하드웨어 RAID라고 적어놨었는데 표를 고치면서 같이 고치는 걸 놓쳤습니다.

지적 감사합니다. 수정하겠습니다.

2023-01-06 06:36 UTC, hspark0582 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +| 리빌드 중 4k 무작위 쓰기 | 8M IOPS | 1.1M IOPS | 18K IOPS |
수정했습니다!

2023-01-06 06:37 UTC, hspark0582 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +제일 먼저 살펴볼 것은 xiRAID 사에서 발표한 성능 비교 결과입니다.
헉 수정했습니다!

2023-01-06 06:37 UTC, hspark0582 commented on _posts/blog/2023-01-06-xiRAID.markdown
> +| 1MiB 순차 쓰기 | 5276 MiB/s | 3826 MiB/s |
반영했습니다!

2023-01-10 04:33 UTC, potatogim approved these changes
수고 많았습니다~!

2023-01-10 04:34 UTC, merged