Add content about penpot
gluesys/tech-blog pull request #125
Opened 2024-07-31 01:22 UTC by ht518

* This is about a mockup design tool called Penpot.
* This is about how to install penpot.
* You can easily create mockups through the library.

2024-07-31 01:31 UTC, lhjnano approved these changes

2024-07-31 02:21 UTC, potatogim requested changes
전체적으로 맞춤법 검사, 용어 표기 통일이 되면 가독성에 도움이 될 것 같습니다~

2024-07-31 02:21 UTC, potatogim commented on _posts/blog/2024-07-31-penpot.markdown
> +tags:       [Penpot, 목업, 디자인목업, 무료오픈소스]
- 태그에 공백이 허용되니까 띄어쓰기 해도 괜찮을 것 같아요~
- 무료오픈소스보다는 오픈 소스 정도로 표현하는게 좋을 것 같네요~ 펜팟도 서비스로 이윤을 남기는 회사라 :-)

2024-07-31 02:21 UTC, potatogim commented on _posts/blog/2024-07-31-penpot.markdown
> +펜팟은 무료 오픈소스로, Figma와 유사한 기능을 제공하며, 사용자들 사이에서 Figma보다 더 흥미로운 도구로 평가되기도 합니다. <br>
- 여기도 무료 오픈소스 -> 오픈 소스로 표현하되 구독형 서비스를 이용하거나 직접 호스팅해서 사용할 수도 있다 정도로 알려주는게 좋겠네요~

2024-07-31 02:21 UTC, potatogim commented on _posts/blog/2024-07-31-penpot.markdown
> +penpot은 Elestio와 Docker로 설치가 가능합니다.<br>
- Penpot, 펜팟 용어가 혼용되고 있어서 명칭을 통일해 주는게 좋겠습니다~

2024-07-31 02:21 UTC, potatogim commented on _posts/blog/2024-07-31-penpot.markdown
> +#### wls2 활성화후 Windows에 Linux를 설치
- wls2 -> WSL2
- 마찬가지로 Windows, Linux 등은 용어 표기를 통일하면 좋을 것 같습니다. (개인적으로는 국문 표기를 선호... ㅋㅋ)

2024-07-31 02:21 UTC, potatogim commented on _posts/blog/2024-07-31-penpot.markdown
> +## '펜팟(Penpot)' 활용하기
각 머릿글 다음에 공백 한 줄씩 추가 부탁할게요~

2024-07-31 05:53 UTC, AngeliKaroS reviewed
맞춤법 검사기 한번 돌려주세요!
고생하셨습니다!!

2024-07-31 05:53 UTC, AngeliKaroS commented on _posts/blog/2024-07-31-penpot.markdown
> +1. window - PowerShell - 관리자로 실행을 시켜줍니다.
Windows 에 s빠졌슴미다

2024-07-31 05:53 UTC, AngeliKaroS commented on _posts/blog/2024-07-31-penpot.markdown
> +Penpot은 Docker compose(v2)라는 Docker 컨테이너들을 정의하고 실행하기 위한 도구를 통해 Penpot 저장소에서 'docker-compose.yaml'파일을 다운로드하여 실행해야 합니다.<br>
파일명 같은거 `` 로 묶으면 가시성이 더  좋을 것 같습니당

2024-07-31 05:53 UTC, AngeliKaroS commented on _posts/blog/2024-07-31-penpot.markdown
> +물론 Penpot의 클라이언트와 서버 모두 느리고 비효율적인 부분도 있고, 신생 프로젝트인 만큼,  안정성이나 성능 면에서는 기존 도구들에 비해 부족할 수 도 있습니다.<br>
`만큼` 뒤에 띄어 쓰기가 2칸이네용

2024-08-02 05:20 UTC, hspark0582 approved these changes

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +저는 완전한 제어와 보안을 위해 툴킷을 내부적으로 호스팅 하는 것을 선호기 때문에 펜팟을 자체적으로 호스팅하고 사용하면서 느꼈던 장단점들과 활용 방법을 소개하도록 하겠습니다.
선호기 -> 선호하기

글 내용에 셀프 호스팅 방법이 상당부분을 차지하고 있는데, 이 문장만 보면 호스팅 후 사용만 하는 것으로 보일 수 있습니다. 굳이 독자를 여기서 놓칠 필요는 없으니 해당 부분을 강조해 주시면 좋겠습니다.

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +WSL2에서 별도로 Docker 인스턴스를 설치하고 실행할 수 있지만, 저는 초보자이기 때문에 Docker와 관련된 모든 설정을 수동으로 해야 하며 도커 데스크톱의 GUI를 통하여 관리하는 기능보다 부족하고 모든 작업을 CLI를 통해 작업할 자신이 없었습니다.<br>
```suggestion
WSL2에서 별도로 Docker 인스턴스를 설치하고 실행할 수 있지만, 저는 초보자이기 때문에 Docker와 관련된 모든 설정과 작업을 CLI를 통해 작업할 자신이 없었습니다.<br>
```

CLI에 기능이 빠져 있지는 않으니까요 ㅎ

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +그러므로 Windows용 Docker Desktop에서 지원되는 WSL2를 사용하여 Linux 기반 개발 환경에서 작업을 해야하기때문에 WSL2 활성화 후에 Windows에 Linux를 설치하는 방법을 알아보겠습니다.<br>
```suggestion
그러므로 여기서는 WSL2를 활성화 하고 Linux를 설치한 뒤, Docker Desktop을 사용하여 Penpot을 설치해보도록 하겠습니다.<br>
```

이유 설명을 또다시 할 필요는 없어보이고, 궁극적인 목적은 리눅스가 아니라 펜팟 설치이기 때문에 이를 보여주는 것이 더 자연스러울 것 같습니다.

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +| **Docker** | 소프트웨어를 실행하는 데 필요한 모든 파일, 라이브러리, 설정 파일 등을 포함하는 패키지를 컨테이너라 하는데, <br>컨테이너 기반의 오픈소스 가상화 시스템이다.|
```suggestion
| **Docker** | 컨테이너(소프트웨어를 실행하는 데 필요한 모든 파일, 라이브러리, 설정 파일 등을 포함하는 패키지) 기반의 오픈소스 가상화 시스템|
```

이게 다른 항목과의 통일성 측면에서 나을 것 같습니다.

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +#### WLS2 활성화후 Windows에 Linux를 설치
```suggestion
#### WSL2 활성화 후 Windows에 Linux를 설치
```

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +#### Docker Desktop설치 및 WSL2 설정
```suggestion
#### Docker Desktop 설치 및 WSL2 설정
```

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +그렇지만 Docker Desktop을 통해서 따로 설치할 필요 없이 배포되어 있기 때문에 명령어를 'docker-compose.yaml'파일만 다운로드 하면 됩니다.<br>
```suggestion
하지만 저희는 Docker Desktop을 설치했기 때문에 'docker-compose.yaml' 파일만 다운로드 하면 됩니다.<br>
```

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +[공식사이트](https://help.penpot.app/technical-guide/developer/) 가이드에 따라 penpot의 구성을 gitlab을 사용하여 인증을 구성하여 로그인 할 수 있게 옵션을 설정하여 사용하겠습니다.
```suggestion
[공식 사이트](https://help.penpot.app/technical-guide/developer/) 가이드에 따라 gitlab을 사용하여 로그인 할 수 있게 설정하겠습니다.
```

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +해당 파일의 확장자는 'yaml'파일이기 때문에 'docker-compose.yaml'파일의 속성에 들어가서 연결 프로그램을 '메모장'으로 변경 후 파일 내용을 수정을 했습니다.
> 메모장

~~으악~~

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +    센스 있는 사용자라면 'localhost'가 아닌 자신의 펜팟설치한 IP로 기입하셔야 한다는걸  눈치채셨을 겁니다.<br>
??? 굳이 이러지 말고 위에 URL `localhost` 자리에 `<penpot을 설치한 장비 IP>` 같은 식으로 넣어주세요...

2024-08-02 05:20 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +그렇지만 개발 중심의 조직이라면 별도의 비용 없이 자체적으로 호스팅 하여 사용할 수 있다는 점에선 최고의 장점이 않을까 생각합니다.
```suggestion
그렇지만 개발 중심의 조직이라면 별도의 비용 없이 자체적으로 호스팅 하여 사용할 수 있다는 점이 최고의 장점이지 않을까 생각합니다.
```

2024-08-08 06:46 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +그렇지만 개발 중심의 조직이라면 별도의 비용 없이 자체적으로 호스팅 하여 사용할 수 있다는 점에선 최고의 장점이 않을까 생각합니다.
@hspark0582 수정완료했씁니다

2024-08-08 06:46 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +[공식사이트](https://help.penpot.app/technical-guide/developer/) 가이드에 따라 penpot의 구성을 gitlab을 사용하여 인증을 구성하여 로그인 할 수 있게 옵션을 설정하여 사용하겠습니다.
@hspark0582 수정완료했씁니다

2024-08-08 06:46 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +그렇지만 Docker Desktop을 통해서 따로 설치할 필요 없이 배포되어 있기 때문에 명령어를 'docker-compose.yaml'파일만 다운로드 하면 됩니다.<br>
@hspark0582 수정완료했씁니다

2024-08-08 06:46 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +저는 완전한 제어와 보안을 위해 툴킷을 내부적으로 호스팅 하는 것을 선호기 때문에 펜팟을 자체적으로 호스팅하고 사용하면서 느꼈던 장단점들과 활용 방법을 소개하도록 하겠습니다.
@hspark0582 수정완료했씁니다

2024-08-08 06:46 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +디자인 도구로써 다양한 기능을 제공하며, 디자인 프로젝트를 효율적으로 관리할 수 있습니다.<br>
@hspark0582 수정완료했씁니다

2024-08-08 07:08 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +목업은 개발로 넘어가기 전에 애플리케이션 또는 웹사이트의 제품이나 디자인을 시각적으로 표현하는 것이므로
@hspark0582 수정완료

2024-08-08 07:24 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +    센스 있는 사용자라면 'localhost'가 아닌 자신의 펜팟설치한 IP로 기입하셔야 한다는걸  눈치채셨을 겁니다.<br>
@hspark0582 수정완료했씁니다

2024-08-08 07:24 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +펜팟은 오픈소스로, Figma와 유사한 기능을 제공하며, 사용자들 사이에서 Figma보다 더 흥미로운 도구로 평가되기도 합니다. <br>
@hspark0582 수정완료했씁니다

2024-08-08 07:24 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +글루시스에 웹 개발팀에서 근무하고 있는 이현태입니다.<br>
@hspark0582 수정완료했씁니다

2024-08-08 07:25 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +물론 Penpot의 클라이언트와 서버 모두 느리고 비효율적인 부분도 있고, 신생 프로젝트인 만큼,  안정성이나 성능 면에서는 기존 도구들에 비해 부족할 수 도 있습니다.<br>
@hspark0582 수정완료했씁니다

2024-08-08 07:25 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +1. window - PowerShell - 관리자로 실행을 시켜줍니다.
@AngeliKaroS 수정완료했습니다

2024-08-08 07:30 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +Penpot은 Docker compose(v2)라는 Docker 컨테이너들을 정의하고 실행하기 위한 도구를 통해 Penpot 저장소에서 'docker-compose.yaml'파일을 다운로드하여 실행해야 합니다.<br>
@AngeliKaroS 수정완료했습니다

2024-08-08 07:30 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +#### wls2 활성화후 Windows에 Linux를 설치
@potatogim  수정완료했습니다

2024-08-08 07:30 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +펜팟은 무료 오픈소스로, Figma와 유사한 기능을 제공하며, 사용자들 사이에서 Figma보다 더 흥미로운 도구로 평가되기도 합니다. <br>
@potatogim  수정완료했습니다

2024-08-08 07:31 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +tags:       [Penpot, 목업, 디자인목업, 무료오픈소스]
@potatogim  수정완료했습니다

2024-08-08 07:35 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +penpot은 Elestio와 Docker로 설치가 가능합니다.<br>
@potatogim 수정완료했습니다

2024-08-08 07:40 UTC, potatogim commented on _posts/blog/2024-07-31-penpot.markdown
> +![images_5.JPG](/assets/penpot/images_5.JPG)
목록 아래에 이미지를 넣을 때에는 106번 줄과 같이 들여쓰기를 해주면 보기에 더 좋습니다~!

2024-08-08 07:45 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +![images_5.JPG](/assets/penpot/images_5.JPG)
@potatogim 수정완료했습니다.

2024-08-08 08:59 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +글루시스에 웹 개발팀에서 근무하고 있는 이현태입니다.<br>
아.. 이제 보니 뒤에도 '에서'가 있네요.. 죄송하지만 다른 거로 바꿔주세요

2024-08-08 09:04 UTC, hspark0582 commented on _posts/blog/2024-07-31-penpot.markdown
> +펜팟은 오픈소스 프로그램으로, 등 Figma와 유사한 기능을 제공하며, 사용자들이 오픈소스와 커뮤니티라는 강력한 가치 기반이 있기 때문에 Figma보다 더 흥미로운 도구로 평가하기도 합니다. 디자인 도구로써 다양한 기능을 제공하며, 디자인 프로젝트를 효율적으로 관리할 수 있습니다.<br>
문장이 이상해졌습니다. 다듬어주세요

2024-08-08 09:14 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +펜팟은 오픈소스 프로그램으로, 등 Figma와 유사한 기능을 제공하며, 사용자들이 오픈소스와 커뮤니티라는 강력한 가치 기반이 있기 때문에 Figma보다 더 흥미로운 도구로 평가하기도 합니다. 디자인 도구로써 다양한 기능을 제공하며, 디자인 프로젝트를 효율적으로 관리할 수 있습니다.<br>
@hspark0582 깔끔하게 변경햇습니다

2024-08-08 09:14 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +글루시스에 웹 개발팀에서 근무하고 있는 이현태입니다.<br>
@hspark0582 수정햇습니다.

2024-08-08 09:16 UTC, AngeliKaroS commented on _posts/blog/2024-07-31-penpot.markdown
> +Penpot은 Docker compose(v2)라는 Docker 컨테이너들을 정의하고 실행하기 위한 도구를 통해 Penpot 저장소에서 'docker-compose.yaml'파일을 다운로드하여 실행해야 합니다.<br>
`''` 로 묶인 친구들도 변경 해주시면 좋을 것 같습니다 ㅎㅎ..

2024-08-08 09:24 UTC, ht518 commented on _posts/blog/2024-07-31-penpot.markdown
> +Penpot은 Docker compose(v2)라는 Docker 컨테이너들을 정의하고 실행하기 위한 도구를 통해 Penpot 저장소에서 'docker-compose.yaml'파일을 다운로드하여 실행해야 합니다.<br>
@AngeliKaroS 수정완료했습니다

2024-08-08 09:31 UTC, AngeliKaroS approved these changes

2024-08-08 09:32 UTC, potatogim approved these changes
고생 많았습니다~! ㅎㅎ

2024-08-08 09:32 UTC, merged