Nextcloud
gluesys/tech-blog pull request #52
Opened 2021-02-18 23:14 UTC by tmlee9930

Nextcloud

2021-02-18 23:53 UTC, potatogim reviewed
확인 플리즈~!

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +직접 설치하여 운영할 수 있고 Office , Google Drive , MatterMost , Calendar 통합된 기능이면서 로컬 컴퓨터 또는 외부 파일 스토리지 호스팅에 사용할 수 있어 NAS 기술을 접하는 사람으로써 클라우드 스토리지 서비스에 적합합니다.
* `MatterMost` -> `Mattermost`
* `... Calendar 통합된 기능이면서 ...` -> `... Calendar가 통합된 기능이면서 ...`
* `... NAS 기술을 접하는 사람으로써 ...` 이 부분은 좀 어색한 것 같네요.

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +위 표처럼 Nextcloud는 소프트웨어 플랫폼에서 통합된 기능들을 나열하고 보여 주고 있습니다.
* `위 표처럼` -> `위 표는`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +파일 저장 및 공유 서비스를 포함하여 문서 작업, 가상화, 클라우드 컴퓨팅 기술 등 하나의 플랫폼에서 사용할 수 있어서 효율적이라고 생각이 됩니다.
* `효율적이라고 생각이 됩니다`는 독자에게 저자 또한 확신이 없다는 느낌을 줍니다. 따라서 `효율적입니다`와 같이 의견을 명확히 전달하는 표현이 좋습니다.

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. 통합된 플러그인으로 사용자 간 전송할 수 있습니다.
통합된 플러그인으로 사용자 간에 무엇을 전송한다는 지 모르겠네요~
통합된 플러그인과 사용자 간 전송에 어떤 관계가 있는지도 모호하구요.

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. 삭제한 파일해도 기간 내 가져올 수 있으며, 파일 작업 시 자동으로 업데이트를 해줍니다.
* `삭제한 파일해도` -> 오타인 것 같네요!

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. NAS를 많은 사용자의 관점에서 단순히 백업용으로 생각하고 사용하고 있다. NAS는 파일 관리에 적합하여 기능에 대표적인 하나로 클라우드 서비스도 제공을 합니다.
* `NAS를 많은 사용자의 관점에서` -> 마찬가지로 문맥이 어색하게 느껴지네요.

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. Petabyte나 Exabyte 같은 단위가 이제는 기업에서 폭발적으로 사용하는 데이터 활용에 있어서 대응 및 서비스를 하기 위해 활용성이 떨어지는 데이터와 활용성이 높은 데이터를 분류할 수도 있습니다.
무슨 문장인지 알 수가 없네요...

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. NAS는 '네트워크 드라이브'나 '외부 저장장치의' 형태로만 사용되고 Cloud 서비스를 이용하면 '동기화 방식'이 기본으로 되어 용량이 늘어나면서 NAS와 같이 활용되는 목적으로 구축된다고 합니다.
* '외부 저장장치의' 를 따옴표로 표기한 이유가 강조인가요?
* Cloud -> 클라우드

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. NAS는 하드디스크에 의존하고, Raid구성으로 비용도 많이 드는데, 클라우드 서비스는 휴지통이나 , 파일 히스토리 기능을 지원하여 복구가 수월하다고 생각되어 안정성이 보장된다고 생각이 됩니다.
* `NAS는 하드디스크에 의존하고` -> 정확히는 물리적인 구성 환경을 필요로 한다고 보는게 맞지 않을까요?
* `휴지통이나 , ...` -> `휴지통이나, ...`
* `Raid` -> `RAID`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7.9 , PHP7.2 , MariaDB 배포하고 Apache에서 실행되는 Nextcloud를 배포합니다.
* `PHP7.2` -> `PHP 7.2`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +   # 디렉터리에 대한 액세서 허용
* `액세서` -> `접근`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7을 설치하여 성공적인 플랫폼을 제공하도록 구축 하였습니다.
* `구축 하였습니다` -> `구축했습니다.`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud는 PHP 프로그래밍 언어를 사용하여 새로운 모듈을 만들고 싶으면 (현재 최신) 7.3이상의 패키지를 설치합니다.
* `7.3이상의` -> `7.3 이상의`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* 이 작업을 완료 한 후 Nextcloud가 액세스 할 수 있도록 사용자 이름과 비밀번호로 데이터베이스를 생성합니다.
* `완료 한 후` -> `완료한 후`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud Server 다운로드 -> 다운로드 -> 서버 소유자 용 아카이브 파일로 이동하여 tar.bz2 다운로드 하였습니다.
* `소유자 용` -> `소유자용`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +2. GPG KEY 오류로 인한 yum install 실패시 해결하기 위한 조치사항입니다.
* `GPG KEY` -> `GPG 공개키`
* `실패시` -> `실패 시`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +3. RPM 기반의 패키지들은 GPG KEY 라는 공개키 기반의 디지털 서명과 검증을 통해서 각종 소스의 변조 유뮤를 검사해주고 무결성을 제공하여 허가된 사용자만 권한을 가질 수 있습니다.
* `GPG KEY` -> `GPG`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* URL 을 통해 접근하면 관리자 웹 화면이 나타나는 걸 확인할 수 있습니다.
* `URL 을 통해` -> `URL을 통해`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud 메인화면 입니다.
* `Nextcloud 메인화면 입니다.` -> `Nextcloud의 메인 화면입니다.`

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +1. Nextcloud Install 링크를 들어가면 Desktop과 Mobile 전용 탐색기 2개 에이전트가 있습니다.
* `Nextcloud Install 링크를 ...` -> `위 설치 링크로 ...`
* Desktop -> 데스크탑
* Mobile -> 모바일
* 2개의 -> 2 종류의

2021-02-18 23:53 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +7. 계정 접근이 활성화 되면 윈도우에서 Nextcloud 앱이 실행됨을 확인할 수 있습니다.
* `활성화 되면` -> `활성화되면`

2021-02-19 07:32 UTC, Gh0stSp1der reviewed
내용은 잘 이해되었습니다.
전반적으로 웹으로 보일 때 구독자가 보기 편하게 수정이 필요한 부분들이 군데군데 보이네요.
확인 부탁드립니다. 고생하셨습니다.

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +   # 실제 소스파일이 있는 Web Root 지정소
conf 파일의 옵션에 대한 설명(주석)은 ```<pre></pre>``` 밖에서 설명한다면 깔끔해질 것 같습니다.

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +#### 3.2 PHP 관련 패키지 설치
```3.1 Apache 설정``` 과 ```3.2 PHP 관련 패키지 설치``` 의 글씨 폰트가 다른 것 같은데 확인 부탁합니다.

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* 콘텐츠를 웹 서버의 루트 디렉터리로 복사한다. Apache 사용으로 **/var/www/html** 입니다.
문어체 ```... 복사한다.```
발표체 ```/var/www/html 입니다.```
통일이 필요해 보입니다.

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud 메인 화면입니다.
위 그림인 ```s1.jpg``` 이 메인 화면이며, s1.jpg를 설명하는 문장이라면 그림 이전에 문장이 먼저 설명되면 좋겠습니다.
아닐 경우 ```위 화면은 Nextcloud의 메인 화면입니다.``` 로 표기한다면 이 문장이 어떤 그림에 대한 설명인지 알 수 있겠습니다.

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +1. 위 설치 링크로 들어가면 데스크탑과 모바일 전용 탐색기 2 종류의 에이전트가 있습니다.
글에서는 간격이 적어 ```위 설치 링크```가 어디에 있는지 알 수 있겠지만, 웹에서 보일 때는 중간에 그림(```agent3.jpg```)가 끼여있어서 따라가기가 어렵습니다. 문장과 그림에 조정이 필요해보입니다.

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="center"><img src="/assets/s2.JPG" width="700px" height="400px">
포스트의 대부분의 스크린샷에 적힌 글씨들이 뚜렷하게 보이지 않습니다. 너비 조정이 필요해보입니다.

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +
글의 설명이 나뉘는 영역(ex, 4. -> 5.)에는 ```&nbsp;```를 사용해서 이전 글과 다음 글에 대한 구분이 필요해 보입니다.

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +|저장소|내용|
이 표가 위 그림의 어떤 부분을 설명하는 것인지 간다하게라도 코멘트가 있다면 표의 의미를 보다 빠르게 캐치할 것 같습니다.
예를 들어서, ```아래 표는 Nextcloud에서 마운트할 수 있는 외부 서비스 목록을 설명합니다.```

2021-02-19 07:32 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +작성 후기
```작성 후기``` 라는 느낌이 '기술 블로그를 작성하면서 느껴진 후기'로 생각되는데, 내용은 ```맺음말```로 느껴집니다.
따라서 ```작성 후기```보다 ```맺음말``` 또는 ```마치며``` 등의 표현이 자연스러워 보입니다.

2021-02-19 07:53 UTC, john3991005 reviewed
앞부분에 해당 제품의 기본적인 동향(시장 위치, 인기, 최근 소식 등)이 조금 더 보충이 되면 좋을 것 같습니다. 다만 관련 내용들이 공통 포스트에 포함될 예정이라면 전부 통합해서 다루는 거도 좋을 것 같습니다.

2021-02-19 07:53 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +2.클라우드와 NAS(Network-Attached Storage)
만일 해당 항목들이 클라우드와 NAS를 비교해서 클라우드의 장점을 부각시키기 위한 글이던, 단순히 클라우드와 NAS의 특징을 언급하는 것이던 비교표로 표현하시면 좋을 것 같습니다. 다만 해당 단락을 기술한 목적이 조금 불분명합니다. Nextcloud와 NAS의 관계에 대한 설명이 사전에 필요할 것 같습니다.

2021-02-19 07:53 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. 통합된 기능으로 서버 운영에만 집중할 수 있어 효율성이 높아진다.
'...효율성이 높아진다.' -> '...효율성이 높아집니다.'

2021-02-19 07:53 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +4.NextCloud 기능
* 'NextCloud 기능' -> 'Nextcloud의 기능'
* 각 기능 별 항목은 기능에 대한 설명이기 때문에 1, 2, 3,... 보다 그냥 불릿이나 하이픈으로 정리하면 좋을 것 같습니다.

2021-02-19 08:30 UTC, jhh9977 commented
'Nextcloud 란?'
> 2번째 문단
: 직접 설치하여 운영할 수 있고 `Office , Google Drive , Mattermost , Calendar` 등 통합된 기능을 로컬 컴퓨터 또는 외부 파일 스토리지 호스팅에 사용할 수 있어 클라우드 스토리지 서비스에 적합합니다.

>Office, Google Drive, Mattermost, Calendar
-> `','`를 포함한 문장들을 위처럼 수정하면 좋을 것 같습니다.

2021-03-16 05:31 UTC, potatogim requested changes

2021-03-16 05:31 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +tags:      Cloud-오픈소스-클라우드-기능리뷰-스토리지-파일스토리지
다른 문서에서 태그하는 방법을 다시 확인해보세요~!

2021-03-16 05:35 UTC, potatogim commented
test

2021-03-16 07:27 UTC, Gh0stSp1der reviewed
CLI가 아닌 웹 화면에서 글을 읽어본다면 전반적으로 그림 크기들이 깔끔하게 정리될 수 있을 것 같습니다.
주제와 내용, 흐름은 모두 잘 이해되었습니다.
다만 실습에서 `설명->실습`, `실습->설명`이 섞여 있어서 이 부분이 크게 정리되면 전반적으로 완성도가 높아질 것 같습니다.

2021-03-16 07:27 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Apache Web Service 데몬을 enable 시키고 start 시킵니다.
전반적으로 실습 명령어와 설명의 순서가 통일된다면 좋겠습니다.

어떨때에는 설명을 먼저하고 이후에 실습 명령이 나온다면, `3.1 Apache 설정`에서는 반대로 설명되어 있습니다.

참고:

* conf 파일을 수정하면 다음으로 아파치 웹 데몬을 enable & start 합니다.
<pre>
~]# 명령어
</pre>

2021-03-16 07:27 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +~]# gpg -import nextcloud.asc
`gpg ~` 관련 명령어는 `3. RPM 기반의 패키지..` 아래에 표기하면 설명-> 실습 순서로 깔끔해질 것 같습니다.

2021-03-16 07:47 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +tags:      [오픈소스, 클라우드, 스토리지, 파일 단위 데이터베이스]
파일 단위 데이터베이스 태그가 포함된 이유가 있나요?

2021-03-22 02:23 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. NAS는 파일 관리에 최적이며 파일 관리 시스템의 대표적인 하나로 클라우드 서비스도 제공합니다.
문장의 앞에 `클라우드와 NAS`라는 헤더가 있다보니 `클라우드의 기능`과 `NAS의 기능`이 어떤 의도로 설명하려는지 고민하게 됩니다.
앞에 헤더로 봤을때는 '클라우드와 NAS가 기능이 합쳐진다.' 라는 의미인데, `클라우드의 기능` 을 읽어보면 '클라우드 기능'만을 설명합니다.
하지만 `NAS의 기능`에는 'NAS와 클라우드 서비스가 합쳐진 기능'을 설명하고 있습니다.

그렇다면 `NAS의 기능`에 첫 설명이 굉장히 중요하게 됩니다. 첫 설명에 의도가 분명해야 뒷 설명들도 '어떤 의도로 이야기하려하고 있구나~' 라고 이해하면서 읽게 됩니다.

아래처럼 설명을 풀어봤습니다. 참고 되시길 바랍니다.

`NAS는 본래 데이터 공유를 목적으로 갖지만, 파일 공유 이외에 다양한 기능이 지속적으로 추가되어 현재로서 클라우드의 일부 기능까지 제공하게 되었습니다.`

2021-03-22 02:26 UTC, Gh0stSp1der commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="center"><img src="/assets/2.JPG" width="1000px" height="400px">
설명이 필요 없다는?? 그림이 필요 없다는?? 이해를 못했어요 😥

2021-03-24 05:33 UTC, potatogim requested changes

2021-03-24 05:33 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +tags:      [Nextcloud, 오픈소스, 클라우드, 스토리지 ]
불필요한 공백은 제거하는게 좋겠네요~!

2021-03-24 06:04 UTC, tmlee9930 reviewed
> 'Nextcloud 란?'
> 
> > 2번째 문단
> > : 직접 설치하여 운영할 수 있고 `Office , Google Drive , Mattermost , Calendar` 등 통합된 기능을 로컬 컴퓨터 또는 외부 파일 스토리지 호스팅에 사용할 수 있어 클라우드 스토리지 서비스에 적합합니다.
> 
> > Office, Google Drive, Mattermost, Calendar
> > -> `','`를 포함한 문장들을 위처럼 수정하면 좋을 것 같습니다.

2021-03-24 06:05 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +직접 설치하여 운영할 수 있고 Office , Google Drive , MatterMost , Calendar 통합된 기능이면서 로컬 컴퓨터 또는 외부 파일 스토리지 호스팅에 사용할 수 있어 NAS 기술을 접하는 사람으로써 클라우드 스토리지 서비스에 적합합니다.
남겨주신 내용으로 수정하였습니다.

2021-03-24 06:07 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +위 표처럼 Nextcloud는 소프트웨어 플랫폼에서 통합된 기능들을 나열하고 보여 주고 있습니다.
내용 자체를 바꿧으며, 2차리뷰에서 바뀐 내용에 대한 코멘트는 없어서 완료 처리하겠습니다.

2021-03-24 06:08 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +파일 저장 및 공유 서비스를 포함하여 문서 작업, 가상화, 클라우드 컴퓨팅 기술 등 하나의 플랫폼에서 사용할 수 있어서 효율적이라고 생각이 됩니다.
"효율적입니다" 로 수정하였습니다.

2021-03-24 06:09 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. 통합된 플러그인으로 사용자 간 전송할 수 있습니다.
해당 내용 자체를 2차 리뷰 전 내용을 바꿔서 2차 리뷰와는 크게 상관이 없는 내용입니다.
완료 처리하겠습니다.

2021-03-24 06:09 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. 삭제한 파일해도 기간 내 가져올 수 있으며, 파일 작업 시 자동으로 업데이트를 해줍니다.
오타 수정하였습니다.

2021-03-24 06:09 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +3. RPM 기반의 패키지들은 GPG KEY 라는 공개키 기반의 디지털 서명과 검증을 통해서 각종 소스의 변조 유뮤를 검사해주고 무결성을 제공하여 허가된 사용자만 권한을 가질 수 있습니다.
GPG로 수정하였습니다.

2021-03-24 06:10 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* URL 을 통해 접근하면 관리자 웹 화면이 나타나는 걸 확인할 수 있습니다.
URL을 통해로 수정하였습니다.

2021-03-24 06:13 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud 메인화면 입니다.
남겨주신 내용으로 수정하였습니다.

2021-03-24 06:14 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +1. Nextcloud Install 링크를 들어가면 Desktop과 Mobile 전용 탐색기 2개 에이전트가 있습니다.
* 위 설치 링크로.....
* 데스크탑
* 모바일
* 2 종류의
수정하였습니다.

2021-03-24 06:14 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +7. 계정 접근이 활성화 되면 윈도우에서 Nextcloud 앱이 실행됨을 확인할 수 있습니다.
남겨주신 내용으로 수정하였습니다.

2021-03-24 06:15 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +</code</pre>
확인 후 수정하였습니다.

2021-03-24 06:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +   # Apache Web Service 데몬을 enable 시키고 start 시킵니다.
1차 리뷰에서 나온 내용으로 수정하였으며, 2차 리뷰 때 남겨주신 내용으로 수정 후 확인 받았습니다.

2021-03-24 06:17 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +   # 실제 소스파일이 있는 Web Root 지정소
설명(주석)은 <pre></pre> 안에서 잘 보이도록 공간 이동을 하였습니다.

2021-03-24 06:17 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +#### 3.2 PHP 관련 패키지 설치
확인 후 같은 글씨 폰트로 수정하였습니다.

2021-03-24 06:20 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* 콘텐츠를 웹 서버의 루트 디렉터리로 복사한다. Apache 사용으로 **/var/www/html** 입니다.
/var/www/html 입니다. 부분은 설명과 영향이 깊지 않아 삭제하고 ... 복사합니다로 수정하였습니다.

2021-03-24 06:21 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +1. 위 설치 링크로 들어가면 데스크탑과 모바일 전용 탐색기 2 종류의 에이전트가 있습니다.
설명과 그림을 간격으로 나눠 보기 편하게 수정하였습니다.

2021-03-24 06:22 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="center"><img src="/assets/s2.JPG" width="700px" height="400px">
2차 리뷰 때 간격 너비에 관한 코멘트는 수정하였고 확인 받았습니다.

2021-03-24 06:22 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +작성 후기
'마치며'로 항목을 추가하여 내용을 작성하였습니다.
코멘트 확인 감사합니다.

2021-03-24 06:23 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +위 표는 Nextcloud는 소프트웨어 플랫폼에서 통합된 기능들을 나열하고 보여 주고 있습니다.
해당 내용은 2차 리뷰 때 변경하였으며, 주형씨가 요청하신 해당 내용에 대한 "어떠한 이유로 하게 됐는지?" 문장을 추가하여
독자들이 이해하도록 수정하였습니다.

2021-03-24 06:24 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +2.클라우드와 NAS(Network-Attached Storage)
2차 리뷰 후 주형씨가 따로 내용 작성하신 부분으로 수정하였습니다.

2021-03-24 06:24 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. 통합된 기능으로 서버 운영에만 집중할 수 있어 효율성이 높아진다.
"효울성이 높아집니다." 로 수정하였습니다.

2021-03-24 06:26 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +4.NextCloud 기능
'Nextcloud의 기능' 수정과 불릿으로 수정하였습니다.

2021-03-24 06:28 UTC, tmlee9930 commented
해당 내용을 '내용, 내용'으로 수정하였습니다.

2021-03-24 06:33 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +tags:      [Nextcloud, 오픈소스, 클라우드, 스토리지 ]
변경 전 - tags: [Nextcloud, 오픈소스, 클라우드, 스토리지 ]
변경 후 - tags: [Nextcloud, 오픈소스, 클라우드, 스토리지] & 다른 항목 문단 공백과 동일하게 수정하였습니다.

2021-03-24 07:14 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +~]# yum update -y
1. 요청하신 커맨드라인은 실제로 root에서 작업한 [root@localhost ~]# 의 형태로 수정하였습니다.
2. 코드블럭에 ~]# 커맨드라인, #설명 으로 헷갈리신 부분은 
  - 3.1 Apache 설정은 커맨드라인 백틱과 설명으로 나눴습니다.
  - 3.1.1 설정 파일 생성은 코드블럭안에 설명은 들어가나 html 코드로 헷갈리지는 않을 것 같아 그대로 두었습니다.
나머지는 <pre></pre> 코드블럭에 설명은 없어서 그대로 두었습니다.

2021-03-24 07:15 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. NAS를 많은 사용자의 관점에서 단순히 백업용으로 생각하고 사용하고 있다. NAS는 파일 관리에 적합하여 기능에 대표적인 하나로 클라우드 서비스도 제공을 합니다.
해당 내용은 2차 리뷰에서 삭제된 문장이라 한번 더 확인 부탁드립니다.

2021-03-24 07:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. Petabyte나 Exabyte 같은 단위가 이제는 기업에서 폭발적으로 사용하는 데이터 활용에 있어서 대응 및 서비스를 하기 위해 활용성이 떨어지는 데이터와 활용성이 높은 데이터를 분류할 수도 있습니다.
해당 문장은 삭제하여 다른 문장으로 수정하였습니다.

2021-03-24 07:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. NAS는 '네트워크 드라이브'나 '외부 저장장치의' 형태로만 사용되고 Cloud 서비스를 이용하면 '동기화 방식'이 기본으로 되어 용량이 늘어나면서 NAS와 같이 활용되는 목적으로 구축된다고 합니다.
해당 내용은 2차 리뷰에서는 삭제된 문장입니다. 
확인 부탁드립니다,

2021-03-24 07:17 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> + 1. NAS는 하드디스크에 의존하고, Raid구성으로 비용도 많이 드는데, 클라우드 서비스는 휴지통이나 , 파일 히스토리 기능을 지원하여 복구가 수월하다고 생각되어 안정성이 보장된다고 생각이 됩니다.
대체 할 내용으로 수정하였습니다.

2021-03-24 07:17 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7.9 , PHP7.2 , MariaDB 배포하고 Apache에서 실행되는 Nextcloud를 배포합니다.
PHP 7.2 로 수정하였습니다.

2021-03-24 07:18 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +   # 디렉터리에 대한 액세서 허용
'접근'으로 수정하였습니다.

2021-03-24 07:18 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7을 설치하여 성공적인 플랫폼을 제공하도록 구축 하였습니다.
'구축했습니다' 로 수정하였습니다.

2021-03-24 07:18 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud는 PHP 프로그래밍 언어를 사용하여 새로운 모듈을 만들고 싶으면 (현재 최신) 7.3이상의 패키지를 설치합니다.
'7.3 이상의' 내용으로 수정하였습니다.

2021-03-24 07:18 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* 이 작업을 완료 한 후 Nextcloud가 액세스 할 수 있도록 사용자 이름과 비밀번호로 데이터베이스를 생성합니다.
'완료한 후' 로 수정하였습니다.

2021-03-24 07:19 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud Server 다운로드 -> 다운로드 -> 서버 소유자 용 아카이브 파일로 이동하여 tar.bz2 다운로드 하였습니다.
'소유자용' 으로 수정하였습니다.

2021-03-24 07:19 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +2. GPG KEY 오류로 인한 yum install 실패시 해결하기 위한 조치사항입니다.
* GPG 공개키
* 실패 시 
수정하였습니다.

2021-03-24 07:21 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +====
해당 내용은 오타여서 수정하였습니다.

2021-03-24 07:24 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +tags:      Cloud-오픈소스-클라우드-기능리뷰-스토리지-파일스토리지
태그 확인 후 수정하였습니다.

2021-03-24 07:26 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud 메인 화면입니다.
요청 하셨던 설명 -> 그림으로 수정하여 순서를 맞췄습니다.

2021-03-24 08:56 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +베이스가 된 ownCloud와 마찬가지로 파일 호스팅 서비스 환경을 제공하고 기능도 비슷하지만, 커뮤니티 버전만 오픈소스로 공개하고 있는 ownCloud에 비해 기업용까지 오픈소스로 제공하고 있는 점에서 차이가 있으며, 무엇보다 Nextcloud만의 차츰 늘려가고 있다고 합니다.
아.. 네 '기능'도 차츰 늘려가고 있다고 합니다. 
내용이 빠져서 추가하여 수정하였습니다.
확인 감사합니다.

2021-03-24 10:59 UTC, john3991005 reviewed
전반적으로 맞춤법/문법 검사를 진행하면 좋을 것 같습니다. 코멘트 확인 부탁드립니다. 감사합니다.

2021-03-24 10:59 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +통합된 OnlyOffice를 지원하는 Nextcloud는 가정용 컴퓨터 또는 외부 파일 스토리지 호스팅을 사용할 수 있습니다.
* 특별히 온리오피스 지원한다는 것을 언급한 이유가 있으신가요? 써드파티 앱을 지원하는 것에 대한 언급이라면 위에 이미 되어 있는 것으로 보입니다.
* 로컬 또는 외부 파일 스토리지 호스팅 관련 내용은 위에 이미 언급되어 있습니다.

2021-03-24 10:59 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +인터넷을 통해 호스팅하여 사용자에게 제공하는 인프라, 플랫폼의 클라우드 서비스인 Nextcloud 소프트웨어를 NAS 스토리지에 설치하였습니다.
* 이미 위에서 Nextcloud가 인터넷 호스팅이나 클라우드 서비스라는 점을 이미 몇번 언급한 바 있어서 이 이상으로 언급 안해도 좋을 것 같습니다. 
* '...NAS 스토리지에 설치하였습니다.'에서 문단이 끝났기 때문에 설치 관련 내용이 다음에 나오는 것처럼 보였는데 다음 내용이 클라우드 서비스와 NAS의 특징에 대한 설명이라 내용이 이어지는 느낌이 조금 부족한 것 같습니다.

2021-03-24 10:59 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +위 사진은 물리적인 NAS 스토리지에 Nextcloud 소프트웨어를 설치하여 구성한 구조입니다.
* '...사진은' -> '...이미지는' 로 변경 부탁드립니다.

2021-03-24 10:59 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +운영체제는 CentOS 7에 Nextcloud를 설치하도록 하겠습니다..!
* 클라우드 및 NAS의 특징을 설명하는 부분에서 이미지 설명 및 설치에 대한 안내까지 내용이 이어지는 느낌이 약간 부족한 것 같습니다. 제가 이전에 매터모스트로 보내드린 내용을 참고 부탁드립니다. 
* 이 문장부터 이후 설치 과정에 대한 설명 전반에서 과거형과 현재형이 혼재되어 있습니다. 하나로 통일하는 것이 필요해 보입니다. 같이 설치를 진행하는 식으로 표현하고 싶으시면 현재형, 이미 설치한 것에 대한 내용을 설명하는 것이라면 과거형으로 하시면 좋을 것 같습니다.

2021-03-24 10:59 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +클라우드 서비스를 제공하는 오픈소스 기반의 Nextcloud 를 소개하였습니다. NAS 엔지니어로서 파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서 구축하여 진행하였습니다. 통합된 정보를 저장하고 운영할 수 있는 공용 데이터들을 쉽고 안정성있게 관리할 수 있다고 깨달았습니다. 오픈소스 기반의 인프라 및 플랫폼 기술을
* 해당 문단 전반적으로 문장이 서로 이어지는 느낌이 부족합니다. 확인 부탁드립니다.
* 'NAS 엔지니어로서 파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서 구축하여 진행하였습니다.': 문장을 다듬는 작업이 필요합니다. 다음 내용을 확인해 주시기 바랍니다.
1. 'NAS 엔지니어로서': 해당 표현을 넣은 목적이 불분명합니다. NAS 엔지니어인 입장에서 한번 Nextcloud를 설치해 보았다는 부분을 강조하고 싶으신 건가요? NAS 엔지니어라는 부분을 강조하고 싶으시면 단순히 설치했다는 점 보다는 경험적인 부분을 표현해 주시는 것이 필요할 것으로 보입니다. 전문가로서 해당 설치 과정에서 어떤 점을 느꼈고, 어떤 부분을 어떻게 평가한다는 등의 내용이 들어가면 좋을 것 같습니다.
2. '...파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서...': 파일 시스템 기반의 스토리지로서의 Nextcloud와 파일 호스팅 서비스인 Nextcloud 두개가 통합된 서버 환경이라는 의미인가요? 아니면 Nextcloud는 파일 시스템 기반의 스토리지와 파일 호스팅 서비스를 제공하는데 이 두 기능을 통합적으로 제공하는 서버를 구축했다는 건가요?
3. '...Nextcloud가 통합된 서버에서 구축하여 진행하였습니다.': Nextcloud가 통합된 서버에서 추가적으로 무엇을 구축해서 진행하신게 아니라 Nextcloud를 서버에 구축한거 아닌가요?
* '통합된 정보를 저장하고 운영할 수 있는...': 통합된 정보라는게 어떤 정보를 의미하는 건가요? 그리고 이 정보를 운영한다는건 데이터를 관리하는걸 의미하는 건가요?

2021-03-25 00:36 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +### 3.8 agent 접속 확인
알려주신 내용으로 수정하였습니다.

2021-03-25 00:37 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +2. 네트워크 기반의 클라우드 서비스로 액세스하는 사용자 데이터 흐름을 원할하게 해줍니다.
오타 내용 수정하였습니다.

2021-03-25 00:38 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +3. SMB , SFTP , WebDAV 프로토콜을 통해 외부 저장소에서 파일을 관리 및 공유할 수 있습니다.
해당 내용 수정하였습니다.

2021-03-25 00:38 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +3. 스프레드시트 , 프레젠테이션 제공하는 편집기를 통해 작업 가능하며 문서 작성을 위한 많은 플러그인 기능을 제공합니다.
해당 내용 수정하였습니다.

2021-03-25 00:39 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +|WebDAV|하이퍼텍스트 전송 프로토콜(HTTP)의 확장으로 , 월드 와이드 웹 서버에 저장된 문서와 파일을 편집하고 관리하도록 합니다.|
해당 내용 확인하여 수정하였습니다.

2021-03-25 00:40 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +|사용자는 데이터베이스에 저장|“사용자 이름과 암호”와 같은 방식으로 메커니즘의 작업을 하지만 자격 증명은 개별적으로 각 사용자에 의해 지정 될 필요가 있다. 해당 마운트에 처음 액세스하기 전에 사용자에게 자격 증명을 입력하라는 메시지가 표시됩니다.|
내용 확인하여 수정하였습니다.

2021-03-25 00:45 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +통합된 OnlyOffice를 지원하는 Nextcloud는 가정용 컴퓨터 또는 외부 파일 스토리지 호스팅을 사용할 수 있습니다.
올리신 두 문장은 위에 있어서 필요 없을 것 같습니다.
해당 내용 삭제하겠습니다.

2021-03-25 00:46 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +위 사진은 물리적인 NAS 스토리지에 Nextcloud 소프트웨어를 설치하여 구성한 구조입니다.
해당 내용 변경하였습니다.

2021-03-25 00:55 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +인터넷을 통해 호스팅하여 사용자에게 제공하는 인프라, 플랫폼의 클라우드 서비스인 Nextcloud 소프트웨어를 NAS 스토리지에 설치하였습니다.
* 인터넷을 통해 호스팅하여 사용자에게 제공하는 인프라, 플랫폼의 클라우드 서비스와 외부 파일 스토리지 호스팅에 사용할 수 있어 이에 적합한 NAS의 기능에 대해 설명을 하겠습니다.

해당 내용으로 수정을 하였는데 확인이 필요할 것 같습니다!

2021-03-29 04:39 UTC, Gh0stSp1der approved these changes

2021-03-29 06:33 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +운영체제는 CentOS 7에 Nextcloud를 설치하도록 하겠습니다..!
주형씨가 피드백 주신 내용과 설치합니다. 현재형 으로 표현하였습니다.

2021-04-07 06:26 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +클라우드 서비스를 제공하는 오픈소스 기반의 Nextcloud 를 소개하였습니다. NAS 엔지니어로서 파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서 구축하여 진행하였습니다. 통합된 정보를 저장하고 운영할 수 있는 공용 데이터들을 쉽고 안정성있게 관리할 수 있다고 깨달았습니다. 오픈소스 기반의 인프라 및 플랫폼 기술을
2번, 3번, 마지막 불릿에 대한 추가 설명을 드리고자 합니다.

2021-04-07 06:27 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +클라우드 서비스를 제공하는 오픈소스 기반의 Nextcloud 를 소개하였습니다. NAS 엔지니어로서 파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서 구축하여 진행하였습니다. 통합된 정보를 저장하고 운영할 수 있는 공용 데이터들을 쉽고 안정성있게 관리할 수 있다고 깨달았습니다. 오픈소스 기반의 인프라 및 플랫폼 기술을
2번, 3번, 마지막 불릿에 대한 추가 설명을 드리고자 합니다.

2021-04-07 06:40 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +클라우드 서비스를 제공하는 오픈소스 기반의 Nextcloud 를 소개하였습니다. NAS 엔지니어로서 파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서 구축하여 진행하였습니다. 통합된 정보를 저장하고 운영할 수 있는 공용 데이터들을 쉽고 안정성있게 관리할 수 있다고 깨달았습니다. 오픈소스 기반의 인프라 및 플랫폼 기술을
2번, 3번, 마지막 불릿의 피드백 중 대안에 대한 설명이 부족한 것 같아 보충 설명을 드리겠습니다.
2. '...파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서...': 위에 글루시스 제품인 애니스토 엔터프라이즈에 Nextcloud를 탑재했다고 언급한 부분이 있으니 파일 스토리지인 애니스토 엔터프라이즈에 파일 호스팅 서비스인 Nextcloud를 설치해 보았다는 식으로 작성하면 좋을 것 같습니다. 
3. 2번에 적힌 느낌으로 정리하면 좋을 것 같습니다.
 * '통합된 정보를 저장하고 운영할 수 있는...': 이 부분 없이 '공용 데이터들을...' 부터 시작하거나 앞을 1번의 NAS 엔지니어로써 느낀점을 기술하면서 이어 나가면 좋을 것 같습니다.

2021-04-07 06:46 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +클라우드 서비스를 제공하는 오픈소스 기반의 Nextcloud 를 소개하였습니다. NAS 엔지니어로서 파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서 구축하여 진행하였습니다. 통합된 정보를 저장하고 운영할 수 있는 공용 데이터들을 쉽고 안정성있게 관리할 수 있다고 깨달았습니다. 오픈소스 기반의 인프라 및 플랫폼 기술을
해당 내용 개인적으로 변형하여 수정했습니다. 
확인부탁드립니다.

2021-04-07 07:41 UTC, kjy8901 approved these changes

2021-04-07 07:43 UTC, hgichon commented
인스톨을 다룬 블로그는 더러 볼수 있는거 같아서 ..
세부 기능에 대한 리뷰가 좀더 상세하면 사람들에게 도움이 될거 같습니다.
가령 파일러의 속성이 일반 NDrive 나 Dropbox 기능과 어떤차이가 있는지... 혹은 개인적으로나마 느낀 쓸만한 가치라든가.
캘린터 채팅등의 기능은 사용 느낌/스샷 은 어떻고... 추천할만 한지 등의 내용이 있으면 어떨까 하네요.
저도 다른 블로그들 돌아다니면.. 좀 길더라도 여러가지 스샷들이 많은게 도움이 되더라구요.
개인적인 소견이였습니다.

2021-04-15 06:48 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +인터넷을 통해 호스팅하여 사용자에게 제공하는 인프라, 플랫폼의 클라우드 서비스인 Nextcloud 소프트웨어를 NAS 스토리지에 설치하였습니다.
확인했습니다!

2021-04-15 06:48 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +클라우드 서비스를 제공하는 오픈소스 기반의 Nextcloud 를 소개하였습니다. NAS 엔지니어로서 파일 시스템 기반의 스토리지와 파일 호스팅 서비스인 Nextcloud가 통합된 서버에서 구축하여 진행하였습니다. 통합된 정보를 저장하고 운영할 수 있는 공용 데이터들을 쉽고 안정성있게 관리할 수 있다고 깨달았습니다. 오픈소스 기반의 인프라 및 플랫폼 기술을
구두로 전달드렸습니다.

2021-04-15 06:49 UTC, john3991005 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +2.클라우드와 NAS(Network-Attached Storage)
따로 전달 드렸습니다!

2021-04-15 06:49 UTC, john3991005 approved these changes

2021-04-15 07:29 UTC, AngeliKaroS approved these changes

2021-04-21 09:13 UTC, potatogim approved these changes

2021-04-21 10:41 UTC, tmlee9930 reviewed
최종 확인

2021-05-18 02:59 UTC, potatogim requested changes
확인 부탁해요~!

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +1.Nextcloud 란?
* 1.Nextcloud -> 1. Nextcloud

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +2.클라우드 서비스와 NAS(Network-Attached Storage)
* 2.클라우드와 ... -> 2. 클라우드와 ...

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +3.Nextcloud 설치
* 3.Nextcloud 설치 -> 3. Nextcloud 설치

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +1. [Nextcloud Install](https://nextcloud.com/install/)
제목이랑 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* 이 작업을 완료한 후 Nextcloud가 액세스 할 수 있도록 사용자 이름과 비밀번호로 데이터베이스를 생성합니다.
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* httpd 설치 경로 /opt/rh/httpd24에서 Nextcloud 설정 경로와 심볼릭 링크를 설정합니다.
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud는 PHP 프로그래밍 언어를 사용하여 새로운 모듈을 만들고 싶으면 (21.03.16, 최신 버전) 7.3 이상의 패키지를 설치합니다.
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7.9, PHP 7.2, MariaDB 배포하고 Apache에서 실행되는 Nextcloud를 배포합니다.
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud 설치가 끝났으면 **/var/www/html/nextcloud/config/config.php** 파일에서 웹 접근을 위한 경로를 확인합니다.
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s2.JPG" width="700px" height="400px">
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s3.JPG" width="700px" height="400px">
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s4.JPG" width="700px" height="400px">
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s5.JPG" width="700px" height="400px">
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s6.JPG" width="700px" height="400px">
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s7.JPG" width="700px" height="400px">
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +Nextcloud 에서 제공하는 기능으로 외부 저장소에서 외부 저장소나 서비스 장치를 Nextcloud 장치로 마운트할 수 있으며, 사용자가 개별 외부 저장소 서비스를 마운트할 수 있도록 허용 가능합니다.
제목이랑 여기 사이에 개행 추가~

2021-05-18 02:59 UTC, potatogim commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/ex1.png" width="700px" height="400px">
제목이랑 여기 사이에 개행 추가~

2021-05-18 04:09 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +1.Nextcloud 란?
수정하였습니다.

2021-05-18 04:09 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +2.클라우드 서비스와 NAS(Network-Attached Storage)
수정하였습니다.

2021-05-18 04:09 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +3.Nextcloud 설치
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +1. [Nextcloud Install](https://nextcloud.com/install/)
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* 이 작업을 완료한 후 Nextcloud가 액세스 할 수 있도록 사용자 이름과 비밀번호로 데이터베이스를 생성합니다.
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* httpd 설치 경로 /opt/rh/httpd24에서 Nextcloud 설정 경로와 심볼릭 링크를 설정합니다.
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud는 PHP 프로그래밍 언어를 사용하여 새로운 모듈을 만들고 싶으면 (21.03.16, 최신 버전) 7.3 이상의 패키지를 설치합니다.
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7.9, PHP 7.2, MariaDB 배포하고 Apache에서 실행되는 Nextcloud를 배포합니다.
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* Nextcloud 설치가 끝났으면 **/var/www/html/nextcloud/config/config.php** 파일에서 웹 접근을 위한 경로를 확인합니다.
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s2.JPG" width="700px" height="400px">
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s3.JPG" width="700px" height="400px">
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s4.JPG" width="700px" height="400px">
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s5.JPG" width="700px" height="400px">
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s6.JPG" width="700px" height="400px">
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/s7.JPG" width="700px" height="400px">
수정하였습니다.

2021-05-18 04:16 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +Nextcloud 에서 제공하는 기능으로 외부 저장소에서 외부 저장소나 서비스 장치를 Nextcloud 장치로 마운트할 수 있으며, 사용자가 개별 외부 저장소 서비스를 마운트할 수 있도록 허용 가능합니다.
수정하였습니다.

2021-05-18 04:17 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +<p align="left"><img src="/assets/ex1.png" width="700px" height="400px">
수정하였습니다.

2021-05-18 05:24 UTC, kjy8901 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7을 설치하여 성공적인 플랫폼을 제공하도록 구축합니다.
64, 65라인에서 목록 처리?가 제대로 안된것 같아요 확인부탁드려요 
![image](https://user-images.githubusercontent.com/48935285/118594471-7f3c0b00-b7e4-11eb-8efb-48d7864a346c.png)

2021-05-18 05:24 UTC, kjy8901 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7을 설치하여 성공적인 플랫폼을 제공하도록 구축합니다.
전체적으로 개행 때문인지 중간중간 기능적용이 안된부분이 많이 있네요 전체적으로 한번 확인부탁드려요
![image](https://user-images.githubusercontent.com/48935285/118594646-bf02f280-b7e4-11eb-8307-b878f245490e.png)

2021-05-18 05:45 UTC, tmlee9930 commented on _posts/blog/2021-02-15-Nextcloud.markdown
> +* CentOS 7을 설치하여 성공적인 플랫폼을 제공하도록 구축합니다.
코멘트 달아 주신 내용 확인하여 수정하였습니다.

2021-05-18 06:19 UTC, AngeliKaroS approved these changes

2021-05-18 07:25 UTC, kjy8901 approved these changes

2021-05-18 08:03 UTC, Gh0stSp1der approved these changes

2021-05-18 08:23 UTC, kjy8901 approved these changes

2021-05-18 08:34 UTC, potatogim approved these changes

2021-05-18 08:35 UTC, merged