Add NVMe_1 post
gluesys/tech-blog pull request #56
Opened 2021-03-09 10:44 UTC by AngeliKaroS

=================== 리뷰용 PR ====================

여러군데 맞춤법 고치고 NVMe 문단쪽 기능 조금 추가 하였습니다.
현재 그림은 아직 구하지 못했습니다. 내용 위주로 봐주시면 감사하겠습니다.

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +위 그림은 플래시 메모리의 구조입니다. Floating Gate에 전자가 있으면 0, 없으면 1로 데이터를 저장합니다. p-substate와 Floating Gate의 사이에 Oxide라는 층이 있는데 이것이 산화막입니다. 원래 전자가 통과하지 못하는 산화막을 Control Gate에 고전압(+극)을 걸고 전자(-극)를 억지로 Floating Gate로
* Floating Gate -> 플로팅 게이트(Floating Gate)
* Control Gate -> 상판 게이트(Top Gate 혹은 Control Gate)
* Oxide -> 산화물(Oxide)

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +위의 그림은 저장방식 별로 어떻게 데이터를 저장하는지를 나타낸 것입니다. 셀에 들어 있는 전자의 양에 따라 데이터를 판별합니다. 바로 이 구조 때문에 셀의 수명이 달라지는 것인데 셀에 전자를 계속 집어넣다 보면 산화막이 점점 손상되어 원하는 데이터와는 다르게 저장이 됩니다. 따라서 한 셀에 데이터를 많이 저장하면 할수록 셀의 수명이 짧아지게 되는 것입니다
* 저장방식 -> 저장 방식
* 테스트단계 -> 테스트 단계

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +SSD는 Solid State Drive의 약자로 비휘발성 플래시 메모리를 사용한 저장장치입니다. SSD는 보조기억장치라는 점에서는 HDD와 같지만 실제로 물리적인 플래터를 돌려서 데이터를 쓰거나 읽어 들이는 HDD와는 다르게 전기신호를 사용하여 데이터를 읽고 쓰기를 수행합니다. 바로 이 점이 HDD와 SSD의 속도 차이가 큰 이유입니다. 직접 플래터를
* 저장장치 -> 저장 장치
* 보조기억장치 -> 보조 기억 장치
* 전기신호 -> 전기 신호
* 갖다 대어 읽어 들이고 하는 과정이 없이 -> 갖다 대어 읽어 들이는 과정 없이

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +그 뿐만 아니라 SSD는 HDD처럼 기계적으로 작동하는 방식이 아니기 때문에 물리적인 충격에도 꽤 잘 버티며 자기를 통한 기록이 아닌 전자로 데이터를 기록 하므로 자기장에도 잘 버틸 수 있습니다. HDD보다 빠르고 튼튼한 SSD 역시 장점만 있는 것은 아닙니다. 플래시 메모리의 한계로 데이터를 저장할 수 있는 셀에 수명이 정해져 있다는 단점과 전기적/논리
* 그 뿐만 아니라 -> 그뿐만 아니라
* 기록 하므로 -> 기록하므로

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> + PCIe는 상호호환이 가능합니다. 이것은 PCI와의 호환을 이야기하는 것이 아닙니다. 예를 들면 PCIe 3.0 x16의 슬롯에 PCIe 2.0 x16의 확장 카드를 장착한다면 PCIe 2.0 x16의 성능으로 사용 할 수 있습니다. 최대성능을 낼 수 없을 뿐 사용은 가능합니다. 반대로 PCIe 3.0 x16슬롯에 PCIe 2.0 x16의 확장 카드를
* 최대성능 -> 최대 성능
* x16슬롯에 -> x16 슬롯에
* 문제 없이 -> 문제없이
* 버전뿐만 -> 버전 뿐만
* 하위호환 -> 하위 호환

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> + * NVMe oF
* NVMe oF -> NVMe-oF

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> + * NVMe MI
* NVMe MI -> NVMe MI

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +이 중 NVMe oF는 외부에 있는 저장장소에 접근한다는 방식으로 인해 주목을 받는 기술 중 하나입니다. 다만 일반 PC에서는 많이 볼 일이 없으니 생소하실 수도 있을 것 같네요.
* NVMe oF -> NVMe-oF

2021-03-09 11:13 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +이 외에도 NVMe에는 수많은 기능들이 존재합니다. 버전이 올라갈때마다 추가되기도 하고 사양마다 또 다른 기능들을 제공하기도 합니다. 제가 NVMe에 대해 찾아보고 공부하면서 가장 많이 보였던 기능들을 조금 적어봤는데 도움이 되셨으면 좋겠습니다.
* 올라갈때마다 -> 올라갈 때마다

2021-03-15 09:19 UTC, potatogim requested changes

2021-03-15 09:19 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +tags:       ""
태그가 없네요~!

다른 문서 참고해서 태그를 넣어주세요~!

2021-03-15 09:38 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +tags:       ""
테스트

2021-03-15 09:59 UTC, potatogim commented
test

2021-03-15 10:02 UTC, potatogim commented
test

2021-03-15 10:04 UTC, potatogim commented
test

2021-03-15 10:17 UTC, potatogim commented
test

2021-03-15 11:51 UTC, potatogim commented
test

2021-03-16 05:42 UTC, Gh0stSp1der reviewed
글을 작성하시고 웹에서 읽어본다면, 실제 적용되었을 때 보여지는 화면으로 리뷰가 가능합니다.
웹에서 리뷰하여 어색한 위치등을 조절한다면 보다 더 글이 깔끔해 보이겠습니다.
주제와 내용, 흐름은 보았을 때 전반적으로 이해가 잘 되는것 같습니다.

2021-03-16 05:42 UTC, Gh0stSp1der commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +요즘 어떤 저장 장치를 사용하고 계시나요? 이에 대한 답으로 SSD(Solid State Drive)만, 혹은 두 개 다! 라고 하시는 분들이 매우 많을 것이라는 생각이 드네요. 예전과 달리 높은 용량 대비 싼 가격이라는 HDD(Hard Disk Drive)의 강점이 SSD와 거의 차이가 없게 되면서 나타나는 현상인 것 같습니다. 심지어 SSD는 HDD
대화형 문장에는 쌍따옴표를 넣는게 읽기 좋습니다.

`"요즘 어떤 저장 장치를 사용하고 계시나요?"` <- 대화형 질문
이에 대한 답으로 <- 본문의 글
`"SSD만"` 혹은 `"두 개 다!"` <- 대화형 대답

2021-03-16 05:42 UTC, Gh0stSp1der commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +요즘 어떤 저장 장치를 사용하고 계시나요? 이에 대한 답으로 SSD(Solid State Drive)만, 혹은 두 개 다! 라고 하시는 분들이 매우 많을 것이라는 생각이 드네요. 예전과 달리 높은 용량 대비 싼 가격이라는 HDD(Hard Disk Drive)의 강점이 SSD와 거의 차이가 없게 되면서 나타나는 현상인 것 같습니다. 심지어 SSD는 HDD
예전과 달리 높은 용량 대비 `싼 가격`이라는 HDD의 강점이
->
예전과 달리 높은 용량 대비 `저렴한 가격`이라는 HDD의 강점이

2021-03-16 05:42 UTC, Gh0stSp1der commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +SSD를 설명하기 전에 먼저 SSD를 구성하고 있는 플래시 메모리에 대해 설명을 드려야 할 것 같습니다. 플래시 메모리는 전원이 공급되지 않아도 지워지지 않는 비휘발성 반도체 저장 장치입니다. 컴퓨터에 부착된 DRAM은 전원이 꺼지면 저장되어있던 내용이 전부 사라지지만 플래시 메모리는 꺼져도 데이터가 남아있다는 것이죠. 둘 다 전기로 저장을 하는데 뭐가
DRAM 단어가 처음 나오는데, 앞서서 SSD와 HDD와 같이 첫 언급에는 풀네임 설명이 있으면 좋겠습니다.
이러한 작은 규칙들이 글 전체에 통일성을 느끼게해주며, 깔끔하게 보이는 효과가 있습니다.

DRAM(DRAM, Dynamic random-access memory)

2021-03-16 05:42 UTC, Gh0stSp1der commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +위의 그림은 저장 방식 별로 어떻게 데이터를 저장하는지를 나타낸 것입니다. 셀에 들어 있는 전자의 양에 따라 데이터를 판별합니다. 바로 이 구조 때문에 셀의 수명이 달라지는 것인데 셀에 전자를 계속 집어넣다 보면 산화막이 점점 손상되어 원하는 데이터와는 다르게 저장이 됩니다. 따라서 한 셀에 데이터를 많이 저장하면 할수록 셀의 수명이 짧아지게 되는 것입니
`바로 이 구조 때문에 셀의 수명이 달라지는 것인데 셀에 전자를 계속 집어넣다 보면 산화막이 점점 손상되어 원하는 데이터와는 다르게 저장이 됩니다.`

문장이 너무 길지요?
이 문장은 실제로 두 문장으로 나눌 수 있습니다.

`바로 이 구조 때문에 셀의 수명이 달라집니다.`, `그 이유는 셀에 전자를 계속 집어넣다 보면 산화막이 점점 손상되어 원하는 데이터와는 다르게 저장이 됩니다.` 

하지만 문장을 나눠보니 앞 문장이 짧군요. 그래서 한 문장으로 작성하신 것 같은데, 이러한 문장과 문장이 연결되는 부위에 쉼표( , ) 를 넣게되면 글을 읽는 사람이 한 템포 쉬어가게 되어 긴 문장이 더욱 자연스럽게 읽혀지게 됩니다.

`바로 이 구조 때문에 셀의 수명이 달라지는 것인데, 셀에 전자를 계속 집어넣다 보면 산화막이 점점 손상되어 원하는 데이터와는 다르게 저장이 됩니다.`

이 차이가 생각보다 큽니다. 쉼표의 사용도가 익숙하지 않을 때에는 문장을 나눠보고, 나뉘어진다면 쉼표를 넣으시면 됩니다. 하지만 절대적인 룰은 없습니다. 긴 문장을 보다 안정감있게 표현하고 싶을 때 사용하시면 됩니다.

(그렇다고 한 문장에 쉼표가 많다면 애초에 너무 많은 문장을 하나로 합친 것이니 나눌 필요가 있습니다.)

2021-03-16 05:42 UTC, Gh0stSp1der commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +그뿐만 아니라 SSD는 HDD처럼 기계적으로 작동하는 방식이 아니기 때문에 물리적인 충격에도 꽤 잘 버티며 자기를 통한 기록이 아닌 전자로 데이터를 기록하므로 자기장에도 잘 버틸 수 있습니다. HDD보다 빠르고 튼튼한 SSD 역시 장점만 있는 것은 아닙니다. 플래시 메모리의 한계로 데이터를 저장할 수 있는 셀에 수명이 정해져 있다는 단점과 전기적/논리적인
나눈 문단이 실제로 markdown으로 보여지면 아래처럼 한 줄로 표기되네요. 이럴 때에는 한줄 더 개행하시면 됩니다.
`... 데이터를 찾을 수 있기 때문입니다. 그뿐만 아니라 SSD는 HDD처럼 ...`

2021-03-16 05:42 UTC, Gh0stSp1der commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +
`## 플래시 메모리` 헤더가 끝나고 `## SSD` 헤더가 시작하는데, 개행이 빠져있어서 실제로 웹에서 읽을 때에는 연결된 느낌이 듭니다.
이후 언급되는 `## SATA`와 `##PCIe` 사이에는 개행(`&nbsp;`)이 존재하는데, 빠진 것 같습니다.

2021-03-16 05:42 UTC, Gh0stSp1der commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +다음 포스팅에서는 2020년 9월 Storage Developer Conference에서 소개된 NVMe 2.0에 대해 써볼까 합니다. 그럼 다음 포스팅에서 만나요~
글과 다음 라인인 `각주` 사이에 개행이 없어서 각주 표기로 따라가지는것 같은데?? 확인 부탁드려요.

2021-03-16 07:48 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +tags:       "[NVMe, 플래시 메모, PCIe, SATA]"
태그 문법이 잘못된 것 같은데...

2021-03-17 05:07 UTC, john3991005 reviewed
오타 정도로만 확인해 주시면 될 것 같습니다. 감사합니다.

2021-03-17 05:07 UTC, john3991005 commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +다음 포스팅에서는 2020년 9월 Storage Developer Conference에서 소개된 NVMe 2.0에 대해 써볼까 합니다. 그럼 다음 포스팅에서 만나요~
* 불릿 제목 다음에 개행을 위한 스페이스 두번이 없어서 이어진 것 같습니다.

2021-03-18 09:35 UTC, kjy8901 commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +<center>&#60; SD 카드 &#62;</center>
개행이 제대로 안된 것 같네요

2021-03-18 09:40 UTC, kjy8901 commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +<center>&#60; 플래시 메모리 구조 - [출처](https://mikrokontroler.pl/2018/01/26/zrozumiec-pamiec-flash/)&#62;</center>
출처는 하단에 별도로 표기하는 것은 어떨까요? 개인적인 의견입니다.
그리고 출처를 표기할때는 사진의 명확한 출처를 확인하고 원저자에게 허락을 받아야 하는 것으로 알고 있는데 그런 과정이 진행된건지요

2021-03-18 10:32 UTC, potatogim commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +<center>&#60; 플래시 메모리 구조 - [출처](https://mikrokontroler.pl/2018/01/26/zrozumiec-pamiec-flash/)&#62;</center>
출처는 가능하면 각주로 달아주면 더 좋을 것 같네요~!

2021-03-19 04:47 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +요즘 어떤 저장 장치를 사용하고 계시나요? 이에 대한 답으로 SSD(Solid State Drive)만, 혹은 두 개 다! 라고 하시는 분들이 매우 많을 것이라는 생각이 드네요. 예전과 달리 높은 용량 대비 싼 가격이라는 HDD(Hard Disk Drive)의 강점이 SSD와 거의 차이가 없게 되면서 나타나는 현상인 것 같습니다. 심지어 SSD는 HDD
수정했습니다. 확인부탁드립니다.

2021-03-19 04:47 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +다음 포스팅에서는 2020년 9월 Storage Developer Conference에서 소개된 NVMe 2.0에 대해 써볼까 합니다. 그럼 다음 포스팅에서 만나요~
수정했습니다 확인부탁드립니다.

2021-03-19 04:47 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +tags:       "[NVMe, 플래시 메모, PCIe, SATA]"
수정했습니다 확인부탁드립니다.

2021-03-19 04:48 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +<center>&#60; 플래시 메모리 구조 - [출처](https://mikrokontroler.pl/2018/01/26/zrozumiec-pamiec-flash/)&#62;</center>
수정했습니다 확인부탁드립니다.

2021-03-19 04:55 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +SSD를 설명하기 전에 먼저 SSD를 구성하고 있는 플래시 메모리에 대해 설명을 드려야 할 것 같습니다. 플래시 메모리는 전원이 공급되지 않아도 지워지지 않는 비휘발성 반도체 저장 장치입니다. 컴퓨터에 부착된 DRAM은 전원이 꺼지면 저장되어있던 내용이 전부 사라지지만 플래시 메모리는 꺼져도 데이터가 남아있다는 것이죠. 둘 다 전기로 저장을 하는데 뭐가
`DRAM` -> `DRAM(DRAM, Dynamic random-access memory)`
변경 완료했습니다. 확인 부탁드립니다

2021-03-19 04:59 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +위의 그림은 저장 방식 별로 어떻게 데이터를 저장하는지를 나타낸 것입니다. 셀에 들어 있는 전자의 양에 따라 데이터를 판별합니다. 바로 이 구조 때문에 셀의 수명이 달라지는 것인데 셀에 전자를 계속 집어넣다 보면 산화막이 점점 손상되어 원하는 데이터와는 다르게 저장이 됩니다. 따라서 한 셀에 데이터를 많이 저장하면 할수록 셀의 수명이 짧아지게 되는 것입니
반점 추가 했습니다.
확인 부탁드립니다

2021-03-19 04:59 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +그뿐만 아니라 SSD는 HDD처럼 기계적으로 작동하는 방식이 아니기 때문에 물리적인 충격에도 꽤 잘 버티며 자기를 통한 기록이 아닌 전자로 데이터를 기록하므로 자기장에도 잘 버틸 수 있습니다. HDD보다 빠르고 튼튼한 SSD 역시 장점만 있는 것은 아닙니다. 플래시 메모리의 한계로 데이터를 저장할 수 있는 셀에 수명이 정해져 있다는 단점과 전기적/논리적인
개행 완료했습니다. 확인 부탁드립니다.

2021-03-19 05:00 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +
수정 완료했습니다. 확인 부탁드립니다.

2021-03-19 05:00 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +위 그림은 플래시 메모리의 구조입니다. 플로팅 게이트(Floating Gate)에 전자가 있으면 0, 없으면 1로 데이터를 저장합니다. p-substate와 플로팅 게이트의 사이에 산화물(Oxide)라는 층이 있는데 이것이 산화막입니다. 원래 전자가 통과하지 못하는 산화막을 상판 게이트(Control Gate)에 고전압(+극)을 걸고 전자(-극)를 억지로
수정 완료했습니다. 확인 부탁드립니다.

2021-03-19 05:01 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +이것은 SATA(Serial ATA)입니다. SATA는 현재 버전 3까지 존재하고 6.0GB/s의 대역폭을 가지며 HDD는 물론 SSD도 장착이 가능합니다. 다만 HDD나 ODD(Optical Disk Drive)에서의 데이터 전송을 목적으로 만들어져 HDD 속도의 몇 배를 내는 SSD는 최대의 성능을 이끌어 낼 수 없었습니다.
기가 비트가 맞았습니다 ㅎㅎ..
수정하였으니 확인 부탁드립니다.

2021-03-19 05:01 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> + PCIe는 상호호환이 가능합니다. 이것은 PCI와의 호환을 이야기하는 것이 아닙니다. 예를 들면 PCIe 3.0 x16의 슬롯에 PCIe 2.0 x16의 확장 카드를 장착한다면 PCIe 2.0 x16의 성능으로 사용 할 수 있습니다. 최대 성능을 낼 수 없을 뿐 사용은 가능합니다. 반대로 PCIe 3.0 x16 슬롯에 PCIe 2.0 x16의 확장 카드
`... 장착한는면 ...` -> `장착한다면` 수정 완료했습니다. 확인 부탁드립니다.

2021-03-19 05:02 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +NVMe는 위에서 잠깐 설명해 드렸듯이 고성능 플래시 메모리를 위한 매우 빠른 속도의 인터페이스입니다. PCIe를 사용하여 만들어졌기 때문에 6GB/s 이상의 높은 대역폭도 구현이 쉽게 가능합니다. 또한 SATA는 1개의 명령어 큐를 가지고 32개의 명령어만 저장할 수 있지만 NVMe는 64,000개의 명령어 큐를 가지고 각 큐당 64,000개의 명령어를
마찬가지로 수정 완료했습니다. 확인 부탁드립니다.

2021-03-19 05:03 UTC, AngeliKaroS commented on _posts/blog/2021-02-04-NVMe_1.markdown
> +<center>&#60; SD 카드 &#62;</center>
`&nbsp;` 추가 완료했습니다.
확인 부탁드립니다.

2021-03-22 01:36 UTC, merged