ownCloud Tech-Blog
gluesys/tech-blog pull request #62
Opened 2021-03-24 10:33 UTC by dhy02014

ownCloud Tech-Blog pull request 요청드립니다.

2021-03-24 10:35 UTC, potatogim requested changes

2021-03-24 10:35 UTC, potatogim commented on _posts/blog/2021-03-22-OwnCloud.markdown
> +<img src="/assets/owncloud_photo/user.PNG" width="100%" height="100%" title="사용자 관리 :사진" >
* `사용자 관리 :사진` -> `사용자 관리: 사진`

2021-03-24 10:39 UTC, dhy02014 commented on _posts/blog/2021-03-22-OwnCloud.markdown
> +<img src="/assets/owncloud_photo/user.PNG" width="100%" height="100%" title="사용자 관리 :사진" >
220 `<img src="/assets/owncloud_photo/user.PNG" width="100%" height="100%" title="사용자 관리: 사진" >`

반영 완료하였습니다.

2021-03-29 02:22 UTC, potatogim commented on _posts/blog/2021-03-22-OwnCloud.markdown
> +<img src="/assets/owncloud_photo/user.PNG" width="100%" height="100%" title="사용자 관리 :사진" >
* 사용자 관리 :사진 -> 사용자 관리: 사진

2021-03-29 02:24 UTC, potatogim approved these changes

2021-03-29 02:27 UTC, dhy02014 commented
@AngeliKaroS @jhyuno 

검증된 pull request 입니다. Approve 한번씩 부탁드리겠습니다.

2021-03-29 02:36 UTC, jhyuno approved these changes

2021-03-29 02:44 UTC, AngeliKaroS requested changes

2021-03-29 02:44 UTC, AngeliKaroS commented on _posts/blog/2021-03-22-OwnCloud.markdown
> +개인적으로 외근을 많이 나가는 입장으로써 외근을 나가는 경우 사내에 있는 문서 또는 파일들을 사용하고 싶을 때 이용한다면 유용하게 쓰일 수 있는 오픈소스라고 생각이 많이 드네요.
232 Line `외근을 많이 나가는 입장으로써`가 아니라 `로서`가 아닌가 싶습니다 ㅎ

2021-03-29 02:49 UTC, dhy02014 commented on _posts/blog/2021-03-22-OwnCloud.markdown
> +개인적으로 외근을 많이 나가는 입장으로써 외근을 나가는 경우 사내에 있는 문서 또는 파일들을 사용하고 싶을 때 이용한다면 유용하게 쓰일 수 있는 오픈소스라고 생각이 많이 드네요.
spellcheck 했을때는 `으로써` `으로서` 의 차이는 없다고 나오네요.

일부 참고 문헌을 봤을때도 어떤 입장이 되어 다루는 문맥은 `으로써`로 사용을 한다고 합니다.

2021-03-29 02:50 UTC, dhy02014 commented on _posts/blog/2021-03-22-OwnCloud.markdown
> +개인적으로 외근을 많이 나가는 입장으로써 외근을 나가는 경우 사내에 있는 문서 또는 파일들을 사용하고 싶을 때 이용한다면 유용하게 쓰일 수 있는 오픈소스라고 생각이 많이 드네요.
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=102161

2021-03-29 04:28 UTC, AngeliKaroS approved these changes

2021-03-29 04:30 UTC, dhy02014 commented
approve 3명 완료하였습니다. Pull Request 확인 부탁드리겠습니다!

2021-03-29 04:55 UTC, potatogim commented
@john3991005 리뷰 좀 부탁할게요~!

2021-03-29 04:58 UTC, john3991005 approved these changes

2021-03-29 05:19 UTC, merged