Add NVMe 2.0 ZNS post
gluesys/tech-blog pull request #74
Opened 2021-07-21 02:58 UTC by jhyuno

Add New Spec NVMe ZNS 

Signed-off-by: Hyuno <jhh9977@gluesys.com>

2021-07-21 04:32 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +NVMe 2.0 버전이 출시되면서 ZNS(Zoned Namespace)라는 새로운 개념이 도입되었습니다. NVMe 입장에서만 새로운 개념이지, 비슷한 개념으로 이미 ZAC/ZBC의 형태로 SMR HDD에 도입되어 있는 구조를 바탕으로 NVMe SSD에 도입되었습니다. 그렇다면 왜 NVMe에 ZNS 개념이 도입된 것일까요? Random Write 데이터를
ZAC, ZBC, SMR 등과 같은 약어의 경우에는 최초 작성시 풀네임을 같이 표기해주면 좋을 것 같습니다.

2021-07-21 04:32 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +Zone은 호스트에 의해 관리되기 때문에, 기존 SSD의 약점인 가비지 컬렉션이 발생하지 않습니다. 이로 인해 쓰기 증폭의 발생이 줄어들며, SSD 내부 저장 공간 관리의 필요성이 적어지므로 OP(Over Provisioning)의 비율을 줄일 수 있습니다.
음... 가비지 컬렉션을 특징이나 기능으로 볼 수는 있겠지만 약점이라고 하기에는 오해의 소지가 발생할 것 같습니다. `약점인 가비지 컬렉션`이라기 보다는 `불필요한 I/O 가 발생하지 않습니다`와 같은 형태로 바꾸는게 더 맞는것 같습니다.

2021-07-21 04:32 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +NVMe 2.0 버전이 출시되면서 ZNS(Zoned Namespace)라는 새로운 개념이 도입되었습니다. NVMe 입장에서만 새로운 개념이지, 비슷한 개념으로 이미 ZAC/ZBC의 형태로 SMR HDD에 도입되어 있는 구조를 바탕으로 NVMe SSD에 도입되었습니다. 그렇다면 왜 NVMe에 ZNS 개념이 도입된 것일까요? Random Write 데이터를
SMR, ZAC, ZBC 등과 같은 약어를 처음 사용하는 부분에서는 풀네임을 같이 표시해주는 게 좋을 것 같습니다.

2021-07-21 04:32 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +Zone은 호스트에 의해 관리되기 때문에, 기존 SSD의 약점인 가비지 컬렉션이 발생하지 않습니다. 이로 인해 쓰기 증폭의 발생이 줄어들며, SSD 내부 저장 공간 관리의 필요성이 적어지므로 OP(Over Provisioning)의 비율을 줄일 수 있습니다.
가비지 컬렉션을 약점이라고 표현하기에는 오해의 소지가 생길 수 있을 것 같네요. 위 표현보다는 `불필요한 I/O가 발생하지 않습니다`와 같은 형태가 어떨까요?

2021-07-21 04:35 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +Zone Management Receive 명령어는 Zone에 대한 정보(Zone Type, Zone State, Zone Attributes 등)가 포함된 데이터 버퍼를 반환합니다. 반환된 데이터를 통해 해당 Zone에 대한 정보를 알 수 있습니다.
성은씨랑 함께 쓰는 형태라 글에 대한 마무리가 없는 건지 헷갈리네요
일단 파일이 다른 파일로 올라가면 읽는 사람 입장에서는 글에 대한 마무리가 필요할 것 같습니다.

제 기억이 맞으면 파일명도 기존 형식과 같이 통일해야 기술블로그에서 표시된다고 알고 있습니다.

2021-07-21 04:40 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +> 1. 일반적으로 새 드라이브의 초기 상태는 ZSE 상태입니다.
음.. 이런 설명 부분이 기술블로그의 핵심적인 부분이 될것 같은데
명령어 설명하는 부분과 같은 처리가 되어 있어서 눈에 잘 들어오지 않습니다.

2021-07-21 04:43 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +![Alt text](/assets/ZNS_FIG2.png){: width="700"}
이미지를 혹시 직접만드신건가요?
직접 만드신게 아니라면 라이센스에 따라서 출처표시나 사용이 불가할 수도 있는데 어떤 라이센스의 이미지를 쓰셨는지.....모르겠네요

2021-07-21 05:02 UTC, jhyuno commented on _posts/blog/zns.markdown
> +![Alt text](/assets/ZNS_FIG2.png){: width="700"}
음~ snia 홈페이지에서 다운받은 PDF 자료에서 퍼온건데, 블로그 하단에 출처 표시만 따로 남겨도 될까요 ?

2021-07-21 05:02 UTC, jhyuno commented on _posts/blog/zns.markdown
> +> 1. 일반적으로 새 드라이브의 초기 상태는 ZSE 상태입니다.
음~ 상태 머신에 대한 설명 이전에 놓아도 될까요 ?

2021-07-21 05:02 UTC, jhyuno commented on _posts/blog/zns.markdown
> +Zone은 호스트에 의해 관리되기 때문에, 기존 SSD의 약점인 가비지 컬렉션이 발생하지 않습니다. 이로 인해 쓰기 증폭의 발생이 줄어들며, SSD 내부 저장 공간 관리의 필요성이 적어지므로 OP(Over Provisioning)의 비율을 줄일 수 있습니다.
괜찮은 것 같습니다. `가비지 컬렉션으로 인한 불필요한 I/O가 발생하지 않습니다`의 표현은 어떨까요 ?

2021-07-21 05:27 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +> 1. 일반적으로 새 드라이브의 초기 상태는 ZSE 상태입니다.
위치는 현호씨 생각대로 하면 될것 같아요
다만 위에 명령어 설명 부분이 man page같은 느낌을 주는데
명령어 설명은 괜찮지만 과정에 대한 설명은 좀 잘보였으면 해서요

2021-07-21 05:31 UTC, kjy8901 commented on _posts/blog/zns.markdown
> +![Alt text](/assets/ZNS_FIG2.png){: width="700"}
음 스니아쪽 라이센스를 한번 확인해봐얄것 같네요
일단 출처라도 표시하는게 좋을 것 같습니다.

2021-07-21 05:57 UTC, jhyuno commented on _posts/blog/zns.markdown
> +Zone은 호스트에 의해 관리되기 때문에, 기존 SSD의 약점인 가비지 컬렉션이 발생하지 않습니다. 이로 인해 쓰기 증폭의 발생이 줄어들며, SSD 내부 저장 공간 관리의 필요성이 적어지므로 OP(Over Provisioning)의 비율을 줄일 수 있습니다.
수정했습니다.

2021-07-21 05:59 UTC, jhyuno commented on _posts/blog/zns.markdown
> +![Alt text](/assets/ZNS_FIG2.png){: width="700"}
수정 완료했습니다.

2021-07-21 06:26 UTC, jhyuno commented on _posts/blog/zns.markdown
> +> 1. 일반적으로 새 드라이브의 초기 상태는 ZSE 상태입니다.
해당 항목을 좀 더 눈에 띄게 변경하였습니다.

2021-07-21 06:28 UTC, jhyuno commented on _posts/blog/zns.markdown
> +NVMe 2.0 버전이 출시되면서 ZNS(Zoned Namespace)라는 새로운 개념이 도입되었습니다. NVMe 입장에서만 새로운 개념이지, 비슷한 개념으로 이미 ZAC/ZBC의 형태로 SMR HDD에 도입되어 있는 구조를 바탕으로 NVMe SSD에 도입되었습니다. 그렇다면 왜 NVMe에 ZNS 개념이 도입된 것일까요? Random Write 데이터를
수정완료하였습니다.

2021-07-22 07:49 UTC, john3991005 reviewed
한번 맞춤법 문법 검사기(http://speller.cs.pusan.ac.kr/)로 검사를 추천드립니다. 나머지는 코멘트 확인 부탁드립니다~!

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Random Write 데이터를 저장하는 방식을 사용하는 기존 SSD는 저장되는 데이터를 관리하기 위해 가비지컬렉션 방식을 사용해왔습니다. 문제는 이러한 가비지컬렉션 과정에서 유효 데이터를 찾기 위한 Read, 그리고 다른 블록으로 옮겨 쓰기 위한 Write의 불필요한 I/O가 발생한다는 것입니다. 그만큼 SSD의 수명이 짧아질 수 밖에 없는데, ZNS는
* 'Random Write 데이터를 저장하는 방식을 사용하는 기존 SSD는...' : 'Random Write 방식으로 데이터를 저장하는 기존 SSD는...' 는 어떠신가요? 단순 제안입니다.

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + * ZSIO:Implicitly
* 찾아보니 'ZSIO: Implicitly Opened' 까지 쓰는 것 같습니다.

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + * ZSEO:Explicitly
* 찾아보니 'ZSIO: Explicitly Opened' 까지 쓰는 것 같습니다.

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + * ZSC:Close
* 찾아보니 'ZSC: Closed' 인 것 같습니다.

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   Write 명령어를 실행하여 암시적으로 오픈된 상태이며, 리소스 부족 시, 호스트에 의한 Open에 의해 닫힐 수 있습니다.
* '...호스트에 의한 Open에 의해 닫힐 수 있습니다.' : 이게 open 명령어에 의해 닫힌다는 건가요? 제가 잘 몰라서 질문 드립니다.

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +아래 사진은 NVMe에서 사용하는 Common Command Format입니다.
* '아래 사진은...' 보다는 '아래 그림은...' 이나 '아래 도식은...' 정도로 표현하는게 좋을 것 같습니다.

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   각 Zone의 writable한 다음 논리 블록 주소를 정의합니다.
* '해당 zone에서 write 할 수 있는 논리 블록 주소의 속성을 정의합니다.' 는 어떠신가요?

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   각 헤Zone의 writable한 논리 블록의 총량을 정의합니다.
* 오타: '각 헤Zone의...'

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +ZNS Command의 종류는 **Zone Append, Zone Management Send, Zone Management Recieve**의 총 3가지가 있습니다.
* 오타: '...Zone Management Recieve...' -> '...Zone Management Receive...'

2021-07-22 07:49 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +  * Set Zone Descriptor Extension Zone
* 찾아보니 'Set Zone Descriptor Extension Zone' 뒤에 'Zone'은 없는 것 같습니다.

2021-07-22 09:01 UTC, jhyuno reviewed
수정사항 반영 완료했습니다. 
리뷰 감사합니다 !

2021-07-23 00:36 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   Write 명령어를 실행하여 암시적으로 오픈된 상태이며, 리소스 부족 시, 호스트에 의한 Open에 의해 닫힐 수 있습니다.
넵 좋은 설명 감사합니다~!

2021-07-23 01:02 UTC, john3991005 approved these changes
고생하셨습니다~!!

2021-07-23 06:16 UTC, potatogim reviewed
우선 이것부터...

2021-07-23 06:16 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Random Write 방식으로 데이터를 저장하는 기존 SSD는 저장되는 데이터를 관리하기 위해 가비지 컬렉션 방식을 사용해왔습니다. 문제는 이러한 가비지 컬렉션 과정에서 유효 데이터를 찾기 위한 Read, 그리고 다른 블록으로 옮겨 쓰기 위한 Write의 불필요한 I/O가 발생한다는 것입니다. 그만큼 SSD의 수명이 짧아질 수밖에 없는데, ZNS는 이러
* 국문 표기를 할 수 있는 부분들은 국문으로 표기해주세요~
* Random Write로 쓰는 방식이 왜 가비지 컬렉션을 했는지에 대한 이유가 없네요.

2021-07-23 06:16 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Zone은 호스트에 의해 관리되기 때문에, 기존 SSD의 약점인 가비지 컬렉션으로 인한 불필요한 I/O가 발생하지 않습니다. 이로 인해 **쓰기 증폭**의 발생이 줄어들며, SSD 내부 저장 공간 관리의 필요성이 적어지므로 **OP(Over Provisioning)**의 비율을 줄일 수 있습니다.
* **OP(Over Provisioning)** -> **오버 프로비저닝(Over-Provisioning)**
  * 약어를 쓰고자한다면 **오버 프로비저닝(Over-Provisioning, 이하 OP)** 와 같이 약어 사용에 대해 독자에게 미리 정보를 제공해주세요.
  * 오버 프로비저닝이 무엇인지에 대한 설명이 없네요~

2021-07-23 08:02 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Random Write 방식으로 데이터를 저장하는 기존 SSD는 저장되는 데이터를 관리하기 위해 가비지 컬렉션 방식을 사용해왔습니다. 문제는 이러한 가비지 컬렉션 과정에서 유효 데이터를 찾기 위한 Read, 그리고 다른 블록으로 옮겨 쓰기 위한 Write의 불필요한 I/O가 발생한다는 것입니다. 그만큼 SSD의 수명이 짧아질 수밖에 없는데, ZNS는 이러
국문 표기로 수정 및 Random Write 방식과 가비지 컬렉션의 관계에 대한 설명을 추가하였습니다.

2021-07-23 08:02 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Zone은 호스트에 의해 관리되기 때문에, 기존 SSD의 약점인 가비지 컬렉션으로 인한 불필요한 I/O가 발생하지 않습니다. 이로 인해 **쓰기 증폭**의 발생이 줄어들며, SSD 내부 저장 공간 관리의 필요성이 적어지므로 **OP(Over Provisioning)**의 비율을 줄일 수 있습니다.
OP에 대한 설명을 추가하였습니다 !

2021-07-23 09:00 UTC, potatogim requested changes
전반적으로 국문 표기가 가능한 영문 표기들이 너무 많네요~

2021-07-23 09:25 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +이에 대한 해결책으로 SSD는 재사용될 수 없는 페이지들을 효율적으로 관리하기 위해 가비지컬렉션(Garbage Collection) 방식을 사용합니다. 재사용될 수 없는 페이지가 포함된 블록 내에서 유효 데이터를 찾기 위한 **읽기** 및 다른 블록으로 옮겨 쓰기 위한 **쓰기** 작업이 발생합니다. 즉 불필요한 I/O가 발생합니다.
수정 완료했습니다!

2021-07-23 09:25 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +그만큼 SSD의 수명이 짧아질 수밖에 없는데, ZNS는 이러한 단점을 보완하기 위해 도입된 기술입니다.
맞춤법 검사기 돌린 결과입니다 ㅠㅠ  
![image](https://user-images.githubusercontent.com/66467411/126762014-749a37ee-8259-4acc-aded-8297a2cc851d.png)

2021-07-23 09:25 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + 2. `ZSE:Empty` 상태에서 Write 명령어를 통해 쓰기 시작하는 경우, 자동으로 `ZSIO:Implicitly Opened` 상태로 전환됩니다.
수정 완료했습니다 !

2021-07-23 09:25 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + 4. `ZSC:Closed` 상태는 Zone Send Action의 Finish Zone 명령 or Zone Active Excursion의 Finish Zone Recommended 속성에 의해 `ZSF:Full` 상태로 전환되어 최종 완료 처리됩니다.
수정 완료했습니다 !

2021-07-23 09:25 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +컨트롤러는`CID(Command Identifier)` 필드를 통해 어떤 Command Set을 사용할 것인지 식별합니다. 그리고 `NSID` 필드의 값에 따라 특정 Namespace에 대한 Command Set을 사용할 수 있습니다. 최종 식별된 Command Set의 Command는 `Opcode` 필드로 구분하여 사용할 수 있습니다.
수정 완료했습니다 !

2021-07-23 09:25 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Zone은 호스트에 의해 관리되기 때문에, 기존 SSD의 약점인 가비지 컬렉션으로 인한 불필요한 I/O가 발생하지 않습니다. 이로 인해 **쓰기 증폭**의 발생이 줄어들며, SSD 내부 저장 공간 관리의 필요성이 적어지므로 **OP(Over-Provisioning, 이하 OP)**의 비율을 줄일 수 있습니다.
수정 완료했습니다 !

2021-07-26 13:14 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +그만큼 SSD의 수명이 짧아질 수밖에 없는데, ZNS는 이러한 단점을 보완하기 위해 도입된 기술입니다.
:open_mouth:

2021-07-26 13:21 UTC, potatogim requested changes

2021-07-26 13:21 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +ZNS 스펙에 대해 알아보기에 앞서, NVMe 프로토콜은 적합한 I/O Command Set을 어떻게 식별하여 사용할까요?
* Command Set을 명령 집합 혹은 명령어 집합 등으로 용어 통일을 하면 어떨까요?

2021-07-26 13:21 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +<center>&#60;NVMe 명령어 셋 포맷&#62;</center>
* 명령어 셋 포맷 -> 명령어 집합 형식

2021-07-26 13:21 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +마무리
마무리는 헤더 처리~!

2021-07-26 13:21 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +출처
출처는 성은씨 수정 내용 기반해서 양식 수정 부탁할게요~!

2021-07-26 13:22 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +ZNS 스펙에 대해 알아보기에 앞서, NVMe 프로토콜은 적합한 I/O Command Set을 어떻게 식별하여 사용할까요?
수정 완료했습니다 !

2021-07-26 13:23 UTC, potatogim requested changes

2021-07-26 13:23 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +### Zone State Machine
* Zone State Machine -> Zone 상태 기계

2021-07-26 13:23 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +<center>&#60;Zone 상태 머신&#62;</center>
* 상태 머신 -> 상태 기계

2021-07-26 13:23 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Zone의 상태를 크게 활성 Zone, 비활성 Zone의 2 가지 상태 집합으로 분류하여 정리해봤습니다.
* 2 가지 -> 2가지

2021-07-26 13:23 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +모든 Zone의 초기 상태는 ZSE:Empty이며, 나머지는 Zone의 활동에 따라 변하는 고유 상태입니다.
각 상태는 코드 하이라이팅 해주면 좋을 듯~!

2021-07-26 13:26 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +<center>&#60;NVMe 명령어 셋 포맷&#62;</center>
수정 완료했습니다 !

2021-07-26 13:26 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +출처
수정 완료했습니다 !

2021-07-26 13:28 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +### Zone State Machine
수정 완료했습니다 !

2021-07-26 13:28 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +<center>&#60;Zone 상태 머신&#62;</center>
수정 완료했습니다 !

2021-07-26 13:28 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Zone의 상태를 크게 활성 Zone, 비활성 Zone의 2 가지 상태 집합으로 분류하여 정리해봤습니다.
미호크 !

2021-07-26 13:28 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +모든 Zone의 초기 상태는 ZSE:Empty이며, 나머지는 Zone의 활동에 따라 변하는 고유 상태입니다.
수정 완료했습니다 !

2021-07-26 13:32 UTC, AngeliKaroS requested changes

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +이에 대한 해결책으로 기존 SSD는 재사용될 수 없는 페이지들을 효율적으로 관리하기 위해 **가비지 컬렉션(Garbage Collection)** 방식을 사용했습니다. 하지만, 이는 재사용될 수 없는 페이지가 포함된 블록 내에서 유효 데이터를 찾기 위한 **읽기** 및 다른 블록으로 옮겨 쓰기 위한 **쓰기** 작업 유발시킵니다. 즉 불필요한 I/O가 발
**쓰기** 작업 유발시킵니다.
이것이 쓰기 증폭이라는것을 미리 언급해두는것이 좋을 것 같습니다

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +Zone의 상태를 크게 활성 Zone, 비활성 Zone의 2 가지 상태 집합으로 분류하여 정리해봤습니다.
활성 Zone (Active Zone), 비활성 Zone(Inactive Zone) 으로 부가 설명이 있으면 좋을 것 같습니다.

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   Zone에 데이터가 비어있음을 의미하고 WP는 해당 Zone의 첫 번째 LBA입니다.
WP(Write Pointer) 부가설명이 있으면 좋을 것 같습니다

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   수명이 다한 상태로, Zone 용량 중 일부가 작동을 중지한 후에도 호스트가 해당 Zone에 대한 네임스페이스를 계속 사용할 수 있습니다
`이름 공간`으로 통일하는게 좋을 것 같습니다.

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   Write 명령어를 실행하여 암시적으로 오픈된 상태이며, 오픈 할 수 있는 리소스가 포화 상태일 경우, 호스트의 Open Zone 명령어에 의해 우선순위가 밀려 닫힐 수 있습니다.
`Write`, `Open Zone` 으로 명령어는 하이라이팅을 주는게 어떨까요?

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +위에 상태도에 따라, 실제로 드라이브에 데이터가 쓰여질 때 Zone의 상태가 어떻게 변할까요?
위에 -> 위의 가 맞는것 같습니다.

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + 2. `ZSE:Empty` 상태에서 `Write` 명령어와 같은 쓰기 명령어를 통해 Zone이 오픈되는 경우, 자동으로 `ZSIO:Implicitly Opened` 상태로 전환됩니다.
오픈되는경우 -> `open`되는 경우 ?

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + 4. `ZSC:Closed` 상태는 Zone Send Action의 `Finish Zone` 명령 or Zone Active Excursion의 `Finish Zone R commended` 속성에 의해 `ZSF:Full` 상태로 전환되어 최종 완료 처리됩니다.
`Finish Zone` 명령 or Zone Active Excursion의 -> `Finish Zone` 명령 또는 `Zone Active Excursion`

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +컨트롤러는`CID(Command Identifier)` 필드를 통해 어떤 명령어 집합을 사용할 것인지 식별합니다. 그리고 `NSID` 필드의 값에 따라 특정 이름 공간에 대한 명령어 집합을 사용할 수 있습니다. 최종 식별된 명령어 집합의 Command는 `Opcode` 필드로 구분하여 사용할 수 있습니다.
최종 식별된 명령어 집합의 Command는 -> 최종 식별된 명령어 집합의 명령(Command)은 이 어떨까용

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +  각 Zone의 write 할 수 있는 논리 블록의 총량을 정의합니다.
`write` 하이라이팅이 빠진것 같습니다.

2021-07-26 13:32 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +    ZSE:Empty 상태라면, ZSC:Closed 상태로 전환시킵니다.
ZSE:~~~ 들의 하이라이팅이 빠진것 같습니다 ㅎ

2021-07-26 13:46 UTC, jhyuno reviewed
매의눈 감사합니다 ㅎㅎ

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +이에 대한 해결책으로 기존 SSD는 재사용될 수 없는 페이지들을 효율적으로 관리하기 위해 **가비지 컬렉션(Garbage Collection)** 방식을 사용했습니다. 하지만, 이는 재사용될 수 없는 페이지가 포함된 블록 내에서 유효 데이터를 찾기 위한 **읽기** 및 다른 블록으로 옮겨 쓰기 위한 **쓰기** 작업 유발시킵니다. 즉 불필요한 I/O가 발
뒷부분에 해당 내용을 미리 언급하도록 수정하였습니다 !
> `즉 불필요한 I/O인 쓰기 증폭이 발생합니다`

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   수명이 다한 상태로, Zone 용량 중 일부가 작동을 중지한 후에도 호스트가 해당 Zone에 대한 네임스페이스를 계속 사용할 수 있습니다
수정했습니다 !

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   Write 명령어를 실행하여 암시적으로 오픈된 상태이며, 오픈 할 수 있는 리소스가 포화 상태일 경우, 호스트의 Open Zone 명령어에 의해 우선순위가 밀려 닫힐 수 있습니다.
아 수정했습니다 !

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +위에 상태도에 따라, 실제로 드라이브에 데이터가 쓰여질 때 Zone의 상태가 어떻게 변할까요?
앗 수정했습니다 !

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + 2. `ZSE:Empty` 상태에서 `Write` 명령어와 같은 쓰기 명령어를 통해 Zone이 오픈되는 경우, 자동으로 `ZSIO:Implicitly Opened` 상태로 전환됩니다.
👍

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + 4. `ZSC:Closed` 상태는 Zone Send Action의 `Finish Zone` 명령 or Zone Active Excursion의 `Finish Zone R commended` 속성에 의해 `ZSF:Full` 상태로 전환되어 최종 완료 처리됩니다.
수정했습니다 !

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +컨트롤러는`CID(Command Identifier)` 필드를 통해 어떤 명령어 집합을 사용할 것인지 식별합니다. 그리고 `NSID` 필드의 값에 따라 특정 이름 공간에 대한 명령어 집합을 사용할 수 있습니다. 최종 식별된 명령어 집합의 Command는 `Opcode` 필드로 구분하여 사용할 수 있습니다.
`최종 식별된 명령어 집합의 명령어는` 으로 수정했는데 어떤가요 ?

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +  각 Zone의 write 할 수 있는 논리 블록의 총량을 정의합니다.
수정했습니다 !

2021-07-26 13:46 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +    ZSE:Empty 상태라면, ZSC:Closed 상태로 전환시킵니다.
수정 완료했습니다 !

2021-07-26 14:29 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +   Zone에 데이터가 비어있음을 의미하고 WP는 해당 Zone의 첫 번째 LBA입니다.
수정 완료했습니다 !

2021-07-26 14:29 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +title:      "NVMe 2.0: Zoned Namespace 명령어"
수정 완료 !

2021-07-26 14:36 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + 4. `ZSC:Closed` 상태는 Zone Send Action의 `Finish Zone` 명령 or Zone Active Excursion의 `Finish Zone R commended` 속성에 의해 `ZSF:Full` 상태로 전환되어 최종 완료 처리됩니다.
`or`을 `또는`  국문 통일하면 좋을것 같습니다

2021-07-26 15:30 UTC, AngeliKaroS requested changes

2021-07-26 15:30 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> + 4. `ZSC:Closed` 상태는 Zone Send Action의 `Finish Zone` 명령 or `Zone Active Excursion`의 `Finish Zone Recommended` 속성에 의해 `ZSF:Full` 상태로 전환되어 최종 완료 처리됩니다.
`Finish Zone` 명령 or `Zone Active Excursion` 에서 `or`이 특별한 의미가 있지 않다면 또는 으로 바꾸는게 좋을 것 같습니다.

2021-07-26 15:34 UTC, potatogim requested changes

2021-07-26 15:34 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +NVMe 2.0 버전이 출시되면서 ZNS(Zoned Namespace)라는 새로운 개념이 도입되었습니다. NVMe 입장에서만 새로운 개념이지, 비슷한 개념으로 이미 ZAC(Zoned Device ATA Command Set) 및 ZBC(Zoned Block Command)의 형태로 SMR(Shingled Magnetic Recording) HDD에 도입된
흠... `비슷한 개념으로 ...` 문장이 조금 어색하게 느껴지네요.

* 비슷한 개념으로 ... NVMe 2.0 스펙에 추가되었습니다 -> 비슷한 개념으로 이미 SMR(...) HDD에 도입된 ... ZBC(...)가 있어왔으며, 이러한 개념들을 바탕으로 하여 NVMe 2.0에 새롭게 추가된 것입니다.

요런 식은 어때요?

2021-07-26 15:37 UTC, potatogim requested changes

2021-07-26 15:37 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +##### ZSA(Zone Send Action)
제목 사이 개행이랑 문단 전체가 들여쓰기 되어 있네요~!

2021-07-26 15:45 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +NVMe 2.0 버전이 출시되면서 ZNS(Zoned Namespace)라는 새로운 개념이 도입되었습니다. NVMe 입장에서만 새로운 개념이지, 비슷한 개념으로 이미 ZAC(Zoned Device ATA Command Set) 및 ZBC(Zoned Block Command)의 형태로 SMR(Shingled Magnetic Recording) HDD에 도입된
괜찮은 것 같습니다.
* 비슷한 개념으로 이미 SMR(...) HDD에 도입된 ZBC(...)가 존재하여, 이러한 개념들을 기반으로 NVMe 2.0 스펙에 새롭게 추가된 것입니다. 
어떠한가요 ?

2021-07-26 15:45 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +##### ZSA(Zone Send Action)
수정하였습니다 !

2021-07-26 15:58 UTC, AngeliKaroS approved these changes

2021-07-26 15:59 UTC, potatogim approved these changes
고생 많았습니다~! :smiley: :+1:

2021-07-26 16:00 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_ZNS.markdown
> +NVMe 2.0 버전이 출시되면서 ZNS(Zoned Namespace)라는 새로운 개념이 도입되었습니다. NVMe 입장에서만 새로운 개념이지, 비슷한 개념으로 이미 ZAC(Zoned Device ATA Command Set) 및 ZBC(Zoned Block Command)의 형태로 SMR(Shingled Magnetic Recording) HDD에 도입된
좋네요~!

2021-07-26 16:02 UTC, merged