Add NVMe 2.0 KV post
gluesys/tech-blog pull request #75
Opened 2021-07-22 00:54 UTC by AngeliKaroS

Signed-off-by: iKaroS <plumno1@gluesys.com>

2021-07-23 01:25 UTC, john3991005 reviewed
문서 전반적으로 '네임스페이스' 와 '이름 공간' 용어를 혼용하고 있어 통일하면 좋을 것 같습니다.
확인 부탁드립니다~!

2021-07-23 01:25 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +title:      "NVMe 2.0 새로운 기능 - KV"
* 현호씨 포스트와 연관성을 고려해서 제목 구성을 통일하면 좋을 것 같습니다
* 'KV' 를 'Key-Value 명령어' 또는 '키-값 명령어' 로 풀어 쓰면 어떨까요?

2021-07-23 01:25 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +안녕하세요! NVMe 관련 포스트를 추운 겨울에 썼던 것 같은데 벌써 뜨거운 여름이 되었네요. 꽤 긴 시간이 지난 만큼 그사이에 NVMe 2.0이 출시됐습니다! 그런 만큼 이번 포스트는 NVMe 2.0에서 새로 추가된 새로운 기능, 그중에서도 키-값 명령어(키-값 명령어)를 메인으로 다루어 보도록 하겠습니다.
* '...키-값 명령어(키-값 명령어)...' : 단어가 중복되었습니다

2021-07-23 01:25 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +이런 놀라운 기술을 만들 수 있었던 그 배경에는 이름 공간(Namespace)이 있었다고 합니다. NVMe 2.0에서 새로 출시된 기능인 `Namespace Types`에 대한 기능으로 각 네임스페이스의 특수한 접근 방법을 설정할 수 있게 되었습니다. 이것으로 인하여 각각의 이름 공간을 하나의 테이블처럼 사용할 수 있게 되었습니다.
* 'NVMe 2.0에서 새로 출시된 기능인 `Namespace Types`에 대한 기능으로...' : 'NVMe 2.0에서 새로 출시된 기능인 `Namespace Types`로...' 정도로 수정하면 어떨까요?

2021-07-23 01:25 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +2. 프로비저닝 오버헤드가 사라짐
* 문장 뒤에 마침표 부탁드립니다.
* 전 문장과 동일하게 '...사라졌다.' 로 통일하면 좋을 것 같습니다.

2021-07-23 01:25 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +비정형 데이터를 저장하는 데에 있어 둘이 비슷한 공통점을 가지고 있긴 하지만 그 외에는 전혀 다른 장치라고 할 수 있습니다. 먼저 키-값 저장장치는 블록 저장장치가 아니라는 것 입니다. 앞서 말씀드렸듯이 가변 길이의 `키`를 주소로 사용하여 데이터를 저장하는 방식을 사용합니다. 반면에 오브젝트 스토리지는 블록 저장장치에 고정된 길이의 오브젝트 구분자를 사
* '...비슷한 공통점...' : 의미가 중복되는 것 같습니다. '비슷한 점' 이나 '공통점' 으로 통일하면 좋을 것 같습니다.

2021-07-23 01:34 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +비정형 데이터를 저장하는 데에 있어 둘이 비슷한 공통점을 가지고 있긴 하지만 그 외에는 전혀 다른 장치라고 할 수 있습니다. 먼저 키-값 저장장치는 블록 저장장치가 아니라는 것 입니다. 앞서 말씀드렸듯이 가변 길이의 `키`를 주소로 사용하여 데이터를 저장하는 방식을 사용합니다. 반면에 오브젝트 스토리지는 블록 저장장치에 고정된 길이의 오브젝트 구분자를 사
수정완료했습니다!

2021-07-23 01:34 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +2. 프로비저닝 오버헤드가 사라짐
수정완료했습니다!

2021-07-23 01:34 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +이런 놀라운 기술을 만들 수 있었던 그 배경에는 이름 공간(Namespace)이 있었다고 합니다. NVMe 2.0에서 새로 출시된 기능인 `Namespace Types`에 대한 기능으로 각 네임스페이스의 특수한 접근 방법을 설정할 수 있게 되었습니다. 이것으로 인하여 각각의 이름 공간을 하나의 테이블처럼 사용할 수 있게 되었습니다.
수정완료했습니다!

2021-07-23 01:34 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +안녕하세요! NVMe 관련 포스트를 추운 겨울에 썼던 것 같은데 벌써 뜨거운 여름이 되었네요. 꽤 긴 시간이 지난 만큼 그사이에 NVMe 2.0이 출시됐습니다! 그런 만큼 이번 포스트는 NVMe 2.0에서 새로 추가된 새로운 기능, 그중에서도 키-값 명령어(키-값 명령어)를 메인으로 다루어 보도록 하겠습니다.
바꾸기 하고나서 잘못 바꿨나보네요 ㅎㅎ 수정 완료했습니다!

2021-07-23 01:51 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +title:      "NVMe 2.0 새로운 기능 - KV"
수정 완료 했습니다!

2021-07-23 05:00 UTC, john3991005 approved these changes
고생하셨습니다~!

2021-07-23 06:11 UTC, potatogim requested changes

2021-07-23 06:11 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +여기서 주의할 점은 `키`는 최대 `16 bytes`에서 `1 byte` 단위로 최소`1 byte` 길이를 가지는 가변적인 값입니다. 또한 `키`는 길이가 다르면 서로 다른 `키`로 인식됩니다. 예를 들어 16진수 `0x55`와 `0x0055`는 서로 다른 `키`로 인식됩니다. `값`은 최대 `4GB`의 크기를 가질 수 있으며 길이가 `0`일 수도 있습니
나열식 서술을 그대로 이어붙인 느낌이라 문장이 매끄럽게 이어지지 않는 것 같아요.

차라리 아예 나열식으로 서술하는 건 어때요?

2021-07-23 06:11 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +* List command - 리스트
리스트라는 표기보다는 나열 혹은 조회 등으로 표기하는게 앞뒤 표현과 맥락이 맞을 것 같네요.

2021-07-23 06:11 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +키-값 데이터베이스는 연관 배열(Hash), 딕셔너리(Dictionary)와 같은 자료구조처럼 어떤 `키`를 사용하여 데이터베이스에 저장된 `값`을 찾아내는 방식의 데이터베이스입니다. 이때 `키`는 테이블별로 고유한 값을 지니고 있습니다. 예전에는 관계형 데이터베이스에 밀려 잘 쓰이지 않았다고 합니다. 하지만 정형 데이터밖에 넣을 수 없는 관계형 데이터베
* 국문 표현을 쓰려면 국문 표현을, 외래어 표기를 쓰려면 외래어 표기를 하는게 일관성이 있어 보입니다.
  * 연관 배열/사전
  * 해시/딕셔너리
* 자료구조
  * 자료 구조

2021-07-23 06:11 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +키-값 명령어들이 새로 나오게 된 배경에는 위에서 잠깐 언급 드렸지만 최근 정형 데이터보다 비정형 데이터를 많이 저장하게 되었다는 것에 있습니다. 기존의 블록 저장 장치를 사용하는 경우, `키`와 논리 블록 주소(Logical Block Address)를 변환하는 별도의 소프트웨어가 필요하게 되는데, 그러면 만들어져 있는 키-값 데이터베이스 소프트웨어를
SSD 하드웨어가 키-값 데이터베이스로 사용될 수 있어서 나온게 아니라, 그렇게 하기 위해서 만들어진게 KV 사양이죠.

전후 관계에 대해 반대로 서술되어 있습니다.

2021-07-23 06:11 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +* Store command - 저장
`Store`는 스펙 상의 명확한 용어 정의이니 별도 강조가 필요해보이고, command는 굳이 표기할 필요가 없어보입니다.

2021-07-23 06:11 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +  검색된 `값`의 길이(byte 단위)도 검색 결과로 볼 수 있습니다.
* byte 단위 -> 바이트 단위

2021-07-23 06:11 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +1. 기존 블록 저장 장치의 논리 블록 주소(LBA, Logical Block Address)를 `키`로 변환하는 과정이 필요 없다.
* (Logical Block Address, 이하 LBA)

2021-07-23 06:11 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +### Key-Value vs Object Storage
어디에서는 Key-Value고 어디에서는 키-값이네요.

표기 통일 해주세요~!

2021-07-23 07:07 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +여기서 주의할 점은 `키`는 최대 `16 bytes`에서 `1 byte` 단위로 최소`1 byte` 길이를 가지는 가변적인 값입니다. 또한 `키`는 길이가 다르면 서로 다른 `키`로 인식됩니다. 예를 들어 16진수 `0x55`와 `0x0055`는 서로 다른 `키`로 인식됩니다. `값`은 최대 `4GB`의 크기를 가질 수 있으며 길이가 `0`일 수도 있습니
먼저 저장(Store) 입니다. 저장 명령어는 SSD에 주어진 `키`와 `값`으로 데이터를 저장하는 명령어입니다. 새로 저장되는 데이터(`값`)를 압축(compress)/비압축(raw) 설정, 덮어쓰기(수정) 금지, 해당 `키`로는 `값`을 저장하지 않도록 생성 금지 명령     등이 가능합니다. 중요한 명령인 만큼 데이터베이스에서 트랜잭션처럼 원자성(atomicity)을 띄고 있습니다. 다음은 검색(Retrieve) 입니다. 검색 명령어는 주어진 `키`로 `값`을 찾아주는 명령어입니다. 압축된 `값`을 압축 해제하여 검색, 비압축 검색>    도 가능하며 검색된 `값`의 길이(바이트 단위)도 검색 결과로 볼 수 있습니다. `키`로 검색을 하는 만큼 `키`를 알고 있어야 데이터(`값`) 검색이 가능하겠죠? 하지만 모든 `키`를 전부 기억하실 필요는 없습니다. 이 조회(List) 명령을 사용하면 해당 >    이름 공간에 존재하는 모든 `키`들을 검색하여 사용자에게 반환합니다. 하지만 항상 모든 키를 검색할 필요가 없을 수도 있을 겁니다. 그럴 때는 존재(Exist) 명령을 사용하면 해당 `키`가 있는지 없는지 알 수 있습니다. 이때 반환되는 값은 `키`를 찾>    으면 `0x00`을 반환하고 찾지 못했다면 입력받았던 `키`를 다시 반환합니다. 저장, 검색이 나왔으니 한 가지만 더 나오면 될 것 같습니다. 삭제(Delete) 명령입니다. 주어진 `키`와 `키`에 연관된 `값`을 삭제하는 명령입니다. 이 명령도 저장과 마찬가>    지로 중요한 명령인 만큼 원자성을 띄고 있습니다.

위와 같이 고쳐봤는데 의견주시면 감사하겠습니다.

2021-07-26 07:20 UTC, dhy02014 approved these changes

2021-07-26 07:41 UTC, john3991005 reviewed
요청하신 추가 내용 검토 완료했습니다. 확인 부탁드립니다~!

2021-07-26 07:41 UTC, john3991005 commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +위 그림은 일반 블록 저장장치에 키-값 데이터베이스를 설치한 것과 키-값 SSD의 임의 쓰기 시 QPS(Queries Per Second, 데이터베이스에서 1초 동안 수신하는 요청 수)를 비교한 것입니다. 이 실험은 1.2테라바이트의 데이터로 SSD 24개에 임의의 `키`를 입력 시켜 그 속도를 측정한 것인데 블록 저장장치를 사용한 `Rocks DB`는
* 두개 그래프의 설명 위치를 명확히 하고 순서대로 설명하면 좋을 것 같습니다. 제가 다음과 같이 내용을 변경해 보았으니 한번 확인 부탁드립니다:

> 위 그림은 일반 블록 저장장치에 키-값 데이터베이스를 설치한 것과 키-값 SSD의 임의 쓰기 시 QPS(Queries Per Second, 데이터베이스에서 1초 동안 수신하는 요청 수)를 비교한 것으로, 1.2테라바이트의 데이터로 SSD 24개에 임의의 `키`를 입력 시켜 그 속도를 측정했습니다. 우선 오른쪽 그래프를 보시면, 블록 저장장치를 사용한 `Rocks DB`는 6개 이상의 SSD에 쓰기 명령을 내렸을 때부터 쓰기 증폭으로 인한 과부하가 일어나는 것으로 보입니다. 그러나 키-값 SSD는 18개에 쓰기 명령을 내려도 멀쩡하네요. Device IO/User IO는 쓰기 증폭 값을 나타내는 것인데 약 7배가량 차이가 나는 것으로 보입니다. 왼쪽 그래프를 보시면, 이 그래프에는 18 까지 밖에 나오지 않았지만, CPU 코어의 수와 같은 수의 키-값 SSD를 사용하면 일반 블록 저장장치보다 약 15배의 QPS 차이가 난다고 합니다. 이처럼 키-값 명령어를 사용하는 SSD는 키-값 데이터베이스로 사용했을 때 일반 SSD보다 더 큰 용량과 빠른 성능을 보이는 강점이 있습니다.

2021-07-26 07:45 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +위 그림은 일반 블록 저장장치에 키-값 데이터베이스를 설치한 것과 키-값 SSD의 임의 쓰기 시 QPS(Queries Per Second, 데이터베이스에서 1초 동안 수신하는 요청 수)를 비교한 것입니다. 이 실험은 1.2테라바이트의 데이터로 SSD 24개에 임의의 `키`를 입력 시켜 그 속도를 측정한 것인데 블록 저장장치를 사용한 `Rocks DB`는
수정 완료했습니당

2021-07-26 07:45 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +### Key-Value vs Object Storage
수정완료했습니다!

2021-07-26 07:45 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +1. 기존 블록 저장 장치의 논리 블록 주소(LBA, Logical Block Address)를 `키`로 변환하는 과정이 필요 없다.
수정완료했습니다!

2021-07-26 07:45 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +  검색된 `값`의 길이(byte 단위)도 검색 결과로 볼 수 있습니다.
수정완료했습니다!

2021-07-26 07:45 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +* Store command - 저장
수정완료했습니다!

2021-07-26 07:45 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +키-값 명령어들이 새로 나오게 된 배경에는 위에서 잠깐 언급 드렸지만 최근 정형 데이터보다 비정형 데이터를 많이 저장하게 되었다는 것에 있습니다. 기존의 블록 저장 장치를 사용하는 경우, `키`와 논리 블록 주소(Logical Block Address)를 변환하는 별도의 소프트웨어가 필요하게 되는데, 그러면 만들어져 있는 키-값 데이터베이스 소프트웨어를
수정완료했습니다!

2021-07-26 07:46 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +키-값 데이터베이스는 연관 배열(Hash), 딕셔너리(Dictionary)와 같은 자료구조처럼 어떤 `키`를 사용하여 데이터베이스에 저장된 `값`을 찾아내는 방식의 데이터베이스입니다. 이때 `키`는 테이블별로 고유한 값을 지니고 있습니다. 예전에는 관계형 데이터베이스에 밀려 잘 쓰이지 않았다고 합니다. 하지만 정형 데이터밖에 넣을 수 없는 관계형 데이터베
수정완료했습니다!

2021-07-26 07:46 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +* List command - 리스트
수정완료했습니다!

2021-07-26 12:23 UTC, potatogim requested changes

2021-07-26 12:23 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +[참고]
참고/출처의 양식은 https://raw.githubusercontent.com/gluesys/tech-blog/master/_posts/blog/2021-04-20-storage_9_intro.markdown 이 글을 참고하면 좋을 것 같네요!

2021-07-26 12:27 UTC, potatogim requested changes

2021-07-26 12:27 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +조금 어려운 내용이 나왔습니다. 위 그림은 키-값 SSD를 만들 때 필요한 구성요소입니다. 각 층에 관해 설명하겠습니다. 먼저 가장 아래층인 장치 드라이버들입니다. 아무래도 새롭게 만들어지는 장치이다 보니 필요한 드라이버들에 관한 내용이 있습니다. 여기에는 새로운 명령어들과 새로운 기능들이 추가됩니다. 그 위층인 KV Abstract Device Inte
* KV Abstract Device Interface -> `KV Abstract Device Interface`
* Key Value Library & Tools -> `Key Value Library & Tools`
* Page cache -> 페이지 캐시

2021-07-26 12:46 UTC, potatogim requested changes

2021-07-26 12:46 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +여기서 주의할 점은 `키`는 최대 `16 바이트`에서 `1 바이트` 단위로 최소`1 바이트` 길이를 가지는 가변적인 값입니다. 또한 `키`는 길이가 다르면 서로 다른 `키`로 인식됩니다. 예를 들어 16진수 `0x55`와 `0x0055`는 서로 다른 `키`로 인식됩니다. `값`은 최대 `4GB`의 크기를 가질 수 있으며 길이가 `0`일 수도 있습니다. 즉
* 최소`1 바이트` -> 최소 `1 바이트`

2021-07-26 12:54 UTC, potatogim approved these changes
고생 많았습니다~! :smiley: :+1:

2021-07-26 13:49 UTC, potatogim requested changes

2021-07-26 13:49 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +[^1]: WAF
```
[^1]: 쓰기 증폭(Write Amplification, WAF): 덮어쓰기가 ...
```

2021-07-26 13:58 UTC, potatogim requested changes

2021-07-26 13:58 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +title:      "NVMe 2.0: Key-Value 명령어 집합"
* Key-Value 명령어 집합 -> 키-값(Key-Value) 명령어 집합

2021-07-26 14:00 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +title:      "NVMe 2.0: Key-Value 명령어 집합"
수정 완료했습니다!

2021-07-26 14:00 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +[^1]: WAF
수정 완료했습니다!

2021-07-26 14:06 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +위 그림은 일반 블록 저장장치에 키-값 데이터베이스를 설치한 것과 키-값 SSD의 임의 쓰기 시 QPS(Queries Per Second, 데이터베이스에서 1초 동안 수신하는 요청 수)를 비교한 것으로, 1.2테라바이트의 데이터로 SSD 24개에 임의의 `키`를 입력 시켜 그 속도를 측정했습니다. 우선 오른쪽 그래프를 보시면, 블록 저장장치를 사용한 `R
왼쪽 그래프를 보시면, 이 그래프에는 18 까지 밖에 나오지 않았지만, 
> 왼쪽 그래프를 보시면, 18개 쓰기 명령의 사용만으로도  

어떻습니까 ?

2021-07-26 14:11 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +위 그림은 일반 블록 저장장치에 키-값 데이터베이스를 설치한 것과 키-값 SSD의 임의 쓰기 시 QPS(Queries Per Second, 데이터베이스에서 1초 동안 수신하는 요청 수)를 비교한 것으로, 1.2테라바이트의 데이터로 SSD 24개에 임의의 `키`를 입력 시켜 그 속도를 측정했습니다. 우선 오른쪽 그래프를 보시면, 블록 저장장치를 사용한 `R
해당 숫자는 쓰기 명령의 갯수가 아니라 SSD의 갯수를 뜻합니다.

2021-07-26 14:27 UTC, jhyuno commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +위 그림은 일반 블록 저장장치에 키-값 데이터베이스를 설치한 것과 키-값 SSD의 임의 쓰기 시 QPS(Queries Per Second, 데이터베이스에서 1초 동안 수신하는 요청 수)를 비교한 것으로, 1.2테라바이트의 데이터로 SSD 24개에 임의의 `키`를 입력 시켜 그 속도를 측정했습니다. 우선 오른쪽 그래프를 보시면, 블록 저장장치를 사용한 `R
위에 18개의 쓰기 명령이라는줄 알았네요. 
> 키-값 SSD는 18개의 SSD에 쓰기 명령을 내려도

이런식으로 하시는거 어떤가요 ?

2021-07-26 14:29 UTC, AngeliKaroS commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +위 그림은 일반 블록 저장장치에 키-값 데이터베이스를 설치한 것과 키-값 SSD의 임의 쓰기 시 QPS(Queries Per Second, 데이터베이스에서 1초 동안 수신하는 요청 수)를 비교한 것으로, 1.2테라바이트의 데이터로 SSD 24개에 임의의 `키`를 입력 시켜 그 속도를 측정했습니다. 우선 오른쪽 그래프를 보시면, 블록 저장장치를 사용한 `R
뒤의 문장과 잘 이어지지 않는 느낌이 들어용..

2021-07-26 14:34 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +title:      "NVMe 2.0: Key-Value 명령어 집합"
:+1:

2021-07-26 14:34 UTC, potatogim commented on _posts/blog/2021-07-16-NVMe_2_KV.markdown
> +[^1]: WAF
:+1:

2021-07-26 15:25 UTC, jhyuno approved these changes
고생 많으셨씁니다.

2021-07-26 16:02 UTC, potatogim approved these changes

2021-07-26 16:02 UTC, merged