storage10 initial commit
gluesys/tech-blog pull request #83
Opened 2021-09-23 00:53 UTC by john3991005

스토리지 기초지식 10: 데이터 보호: 데이터 백업 초안입니다.

2021-09-23 01:14 UTC, kjy8901 commented
cold backup 이나 hot backup 내용도 추가하는건 어떤가요?

2021-09-23 01:34 UTC, AngeliKaroS approved these changes

2021-09-23 04:21 UTC, john3991005 commented
> cold backup 이나 hot backup 내용도 추가하는건 어떤가요?

방금 '백업의 종류' 쪽에 핫/콜드 백업 내용 추가했습니다!

2021-09-23 07:00 UTC, kjy8901 approved these changes

2021-09-23 09:09 UTC, potatogim requested changes

2021-09-23 09:09 UTC, potatogim commented on _posts/blog/2021-09-23-storage_10.markdown
> +tags:       [백업, backup, 서비스 수준 협약, service level agreement, 전체 백업, full backup, 증분 백업, incremental backup, 차등 백업, differential backup]
태그는 대문자 처리~

2021-09-23 09:09 UTC, potatogim commented on _posts/blog/2021-09-23-storage_10.markdown
> +tags:       [백업, backup, 서비스 수준 협약, service level agreement, 전체 백업, full backup, 증분 백업, incremental backup, 차등 백업, differential backup]
https://tech.gluesys.com/tags/

2021-09-23 09:14 UTC, john3991005 commented on _posts/blog/2021-09-23-storage_10.markdown
> +tags:       [백업, backup, 서비스 수준 협약, service level agreement, 전체 백업, full backup, 증분 백업, incremental backup, 차등 백업, differential backup]
태그 대문자로 변경했습니다~!

2021-09-23 09:15 UTC, potatogim commented on _posts/blog/2021-09-23-storage_10.markdown
> +tags:       [백업, backup, 서비스 수준 협약, service level agreement, 전체 백업, full backup, 증분 백업, incremental backup, 차등 백업, differential backup]
:+1:

2021-09-23 09:15 UTC, potatogim approved these changes
LGTM!

2021-09-23 09:16 UTC, merged

2021-09-23 09:18 UTC, Gh0stSp1der reviewed
어? 머지되었네, 고생하셨습니다.

2021-09-23 09:18 UTC, Gh0stSp1der commented on _posts/blog/2021-09-23-storage_10.markdown
> +데이터 백업은 원본 데이터를 잃게 되는 상황에 대비해 다른 위치에 안전하게 복제해 놓은 사본 데이터를 말합니다. 원본 데이터에 문제가 발생할 시 이 사본 데이터를 통해 신속하게 원래의 상태로 복구하는 것이 주목적으로, 이와 같은 일련의 작업을 재해 복구(disaster recovery)라고 합니다.
`문제가 발생할 시 '이' 사본 데이터를 통해 ... , '이'와 같은 일련의`
쉼표로 이어지는 하나의 문장에서 앞 문장의 `이`는 `사본 데이터`를 의미하고, 뒷 문장의 `이`는 `과정`을 뜻하는군요.
앞 문장의 `이`는 이어서 `사본 데이터가` 곧바로 나오기 때문에 제거해도 무방할 것 같습니다. (의견일 뿐입니다)

2021-09-23 09:18 UTC, Gh0stSp1der commented on _posts/blog/2021-09-23-storage_10.markdown
> +백업 작업은 주로 백업 전용 어플라이언스(purpose-built backup appliance, PBBA)에서 관리합니다. 현재는 하드디스크 기반의 백업 어플라이언스가 주류를 이루고 있지만, 2000년대만 해도 많은 기업들이 테이프 기반의 스토리지를 주요 백업 스토리지로 사용해 왔습니다. 요즘에도 테이프 스토리지를 활용하기는 하지만 주로 빠른 복구가 필
_백업 장치_ 에 대한 설명으로 **하드디스크 기반 스토리지**, **테이프 기반 스토리지**에 대한 설명에 이어서,
갑자기 _추상적 개념_ 인 **클라우드**가 언급되어 약간 어색하게 느껴집니다.
왜 클라우드로 대체되고 있는 추세인지 간단한 이유가 추가되면 좋겠습니다.
예를 들어, 백업 시스템을 구축하는 비용보다 클라우드가 유지 관리 측면에서 저렴해져서??

2021-09-24 09:31 UTC, john3991005 commented on _posts/blog/2021-09-23-storage_10.markdown
> +글로벌 보안 컨설팅 업체인 Ponemon Institute에 의하면, 지난 2020년 전 세계적으로 데이터 유출로 인한 기업의 평균 피해 금액이 무려 386만 달러(약 45억 원)였다고 합니다. 게다가 백업 소프트웨어 기업인 Veeam의 보고서에 의하면, 2020년 다운타임으로 발생한 기업의 손실은 시간당 약 84,650 달러(약 1억원)에 달한다고 합니
참고에 있던 링크를 각주로 변경했습니다!

2021-09-24 09:32 UTC, john3991005 commented on _posts/blog/2021-09-23-storage_10.markdown
> +데이터 백업은 원본 데이터를 잃게 되는 상황에 대비해 다른 위치에 안전하게 복제해 놓은 사본 데이터를 말합니다. 원본 데이터에 문제가 발생할 시 이 사본 데이터를 통해 신속하게 원래의 상태로 복구하는 것이 주목적으로, 이와 같은 일련의 작업을 재해 복구(disaster recovery)라고 합니다.
말씀대로 내용 반영 했습니다!

2021-09-24 09:33 UTC, john3991005 commented on _posts/blog/2021-09-23-storage_10.markdown
> +백업 작업은 주로 백업 전용 어플라이언스(purpose-built backup appliance, PBBA)에서 관리합니다. 현재는 하드디스크 기반의 백업 어플라이언스가 주류를 이루고 있지만, 2000년대만 해도 많은 기업들이 테이프 기반의 스토리지를 주요 백업 스토리지로 사용해 왔습니다. 요즘에도 테이프 스토리지를 활용하기는 하지만 주로 빠른 복구가 필
클라우드 백업 관련 내용을 다른 문단으로 돌려서 추가 설명 넣었습니다!

2021-09-24 09:34 UTC, john3991005 commented on _posts/blog/2021-09-23-storage_10.markdown
> +백업 작업은 주로 백업 전용 어플라이언스(purpose-built backup appliance, PBBA)에서 관리합니다. 현재는 하드디스크 기반의 백업 어플라이언스가 주류를 이루고 있지만, 2000년대만 해도 많은 기업들이 테이프 기반의 스토리지를 주요 백업 스토리지로 사용해 왔습니다. 요즘에도 테이프 스토리지를 활용하기는 하지만 주로 빠른 복구가 필
수정 풀리퀘스트 참고 바랍니다!
https://github.com/gluesys/tech-blog/pull/84