MOP 소개 포스트
gluesys/tech-blog pull request #91
Opened 2022-01-10 09:14 UTC by kjy8901

Meta Object Porotocol에 대해서 perl 코드를 이용하여 간단히 소개하는 포스트입니다.

Signed-off-by: KwonJinyoung <kjy8901@gluesys.com>

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +그래서 MOP에 관련된 내용을 perl의 OOP 중 경량화 버전인 Mouse를 사용해서 설명해보려고 합니다.
* perl -> Perl
* Mouse 패키지 주소를 링크로 걸어주면 좋겠네요~!

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +MOP 개념에서는 Class나 Method, Attribute 모두 다 Meta Class에 의해 생성된 객체입니다.
국문 표현이 가능한 부분들은 국문으로 표현하는게 좋겠네요~!

* Class -> 클래스
* Method -> 메서드
* Attribute -> 속성
* Meta Class -> 메타 클래스

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +오늘은 Meta Object Protocol(이하 MOP)에 대해서 블로그를 작성해보려고 합니다.
* `Meta Object Protocol(이하 MOP)` -> `메타 객체 프로토콜(Meta Object Protocol, 이하 MOP)` 혹은 `메타 오브젝트 프로토콜(Meta Object Protocol, 이하 MOP)` 등으로 표기하는게 좋겠네요.
* `블로그를 작성해보려고 합니다` -> `공유해보려고 합니다`가 조금 더 자연스러운 표현이 될 수 있을 것 같네요.

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +(MOP 예시는 p5-Mouse version v2.5.10을 기준으로 설명)
* 따로 괄호로 설명하기보다는 서술형으로 자연스레 이어서 설명하는게 좋겠네요.
    * `이 글은 Mouse v2.5.10 버전을 기준으로 작성되었습니다` 등과 같이~

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +많은 키워드가 있겠지만 가장 익숙한 키워드인 속성과 Method를 예시로 보면서 MOP에 대해서 알아보려고 합니다.
마찬가지로 영문/국문 혼용은 가능하면 국문으로~!

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +평소 속성을 선언하거나 혹은 Method를 수정할 때 `has`, `around`, `override` 같은 예약어를 사용하셨을 것 같습니다.
* `~했을 것 같습니다` 보다는 `~합니다`의 형태로 작성해주는 것이 좋을 것 같네요~!

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +perl OOP에서 속성을 선언할 때 위와 같은 형태로 선언을 합니다.
* perl -> Perl

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +아래는 Mouse.pm의 코드입니다. 그중 일부를 보면 `setup_import_methods`라는 함수로 일반적으로 perl에서 속성을 선언할 때 위와 같은 형태로 작성할 텐데 MOP를 사용하지 않는 언어에서 `has`는 일반적인 예약어로 볼 수 있을 것 같습니다.
* `Mouse.pm`의 경로는 패키지 소스의 루트 경로를 기준으로 표기해주는게 좋겠네요~!

2022-01-10 09:48 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +MOP가 사용되는 언어는 Java(Javassist), JS(Joose), perl(Moose), 오픈 C++, 오픈 Java 등이 있습니다.
MOP를 지원하는 각 언어 혹은 시스템에 대한 참조 링크가 있으면 좋겠네요~!

2022-01-10 09:52 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +MOP 개념에서는 Class나 Method, Attribute 모두 다 Meta Class에 의해 생성된 객체입니다.
이걸 어떻게 해야하나 고민했는데 감사합니다!

2022-01-10 10:00 UTC, potatogim commented
아래와 같은 도식들이 있으면 이해에 많은 도움이 될 것 같네요~!

* 기본 개념에 대한 도식
* 인라인 생성자가 만들어지는 과정에 대한 도식

추가로 클래스/메서드/속성 각각에 대한 기본 메타 클래스들이 존재하는데 이러한 메타 클래스들이 어떤 녀석들인지와 어디로부터 기본 정의가 이루어지는지(XS 코드)를 포함하면 추후 우리가 모델 클래스에 대해 메타롤(Meta-role)을 어떻게 사용하고 있는지에 대해 서술하기가 더 용이하겠네요 :)

2022-01-11 01:55 UTC, jhyuno commented on _posts/blog/2022-01-10-MOP.markdown
> +1. Meta::Class->inittialize
오타가 있는 것 같습니다.
> `inittialize` -> `initialize`

2022-01-11 01:55 UTC, jhyuno commented on _posts/blog/2022-01-10-MOP.markdown
> +다시 돌아와서 `has`라는 예약어는 `setup_import_methods`를 사용하여 만들었다는 것은 알게 되었습니다.
> `setup_import_methods`를 사용하여 만들었다 -> `setup_import_methods`를 사용하여 만들어졌다

어떠하십니까?

2022-01-11 02:02 UTC, AngeliKaroS requested changes

2022-01-11 04:41 UTC, potatogim requested changes

2022-01-11 04:41 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +위 코드는 `lib/Mouse.pm` 코드인데 Exporter 패키지의 `setup_import_methods` 함수를 사용하여 사용자가 지정한 import 메서드나 unimport 메서드를 빌드합니다.
* Exporter와 같이 고유 명사를 나타내는 경우에는 링크를 같이 걸어주세요~
    * `[Exporter](https://metacpan.org/pod/Exporter)`
* import -> \`import\`
* unimport -> \`unimport\`

2022-01-11 04:41 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +`_construct_meta`에서는 `do` Block에 있는 내용을 꾸며서 변수에 넣어 주고 `_initialize_object`를 호출합니다.
* Block -> 블록 혹은 코드 블록

2022-01-11 04:41 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +1. Meta::Class->initialize
요기에도 각각 하이라이팅~!

2022-01-11 04:41 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +이런 형태로 클래스, 속성, 메서드 모두 필요한 정보를 체크하여 코드를 리턴합니다.
* 리턴합니다 -> 반환합니다

2022-01-11 04:41 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +내부적으로는 객체가 생성될 때 관련 속성값들이 etcd랑 연동이 되도록 변경하여 사용하고 있습니다.
여기에 대해서도 도식이 추가되면 좋겠네요~!

2022-01-11 04:41 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +참고
참고는 기존에 작성되었던 포스팅들 참고해서 양식 맞춰주세요~!

2022-01-11 04:42 UTC, potatogim requested changes

2022-01-11 04:42 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +title:      "Meta Object Protocol(MOP)에 대하여"
타이틀도~!

2022-01-11 05:32 UTC, potatogim commented
테스트

2022-01-11 05:35 UTC, potatogim commented
테스테

2022-01-11 06:36 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +내부적으로는 객체가 생성될 때 관련 속성값들이 etcd랑 연동이 되도록 변경하여 사용하고 있습니다.
테스트

2022-01-11 06:36 UTC, potatogim commented
테스트

2022-01-12 02:40 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +Perl OOP에서 속성을 선언할 때 위와 같은 형태로 선언을 합니다.
* `Perl OOP에서 속성을 선언할 때 위와 같은 형태로 선언을 합니다.` 
    * 선언이라는 단어가 반복되어 가독성이 떨어진다는 느낌이 드네요.
    * 이런 형태는 어때요?
        * `Mouse를 사용하여 클래스의 속성을 선언할 때에는 has 키워드를 사용합니다.`
* 각 키워드(`has`, `is`, `isa`, `default`)에 대해서 간단하게 설명해줄 필요가 있겠네요~!

2022-01-12 06:02 UTC, john3991005 approved these changes
기술 블로그 포스트 작성하시느라 고생 많으셨습니다. 미리 어프루브 눌러 놓겠습니다~!

2022-01-17 02:00 UTC, Gh0stSp1der commented on _posts/blog/2022-01-10-MOP.markdown
> +    for my $n(ref($name) ? @{$name} : $name){
아래 코드에서는 조건 괄호(`)`)랑 바디 괄호(`{`)랑 띄었으면서 힝
`for my $n(ref($name) ? @{$name} : $name) {`

2022-01-17 02:00 UTC, Gh0stSp1der commented on _posts/blog/2022-01-10-MOP.markdown
> +    if(ref($self) ne __PACKAGE__){
여기도, 그리고 if 예약어랑 조건 괄호 사이에 띄어쓰기 없엉
`if (ref($self) ne __PACKAGE__) {`

2022-01-17 02:05 UTC, Gh0stSp1der commented on _posts/blog/2022-01-10-MOP.markdown
> +sub _initialize_object{
메서드명이랑 대괄호랑 띄어줘용 
`sub _initialize_object {`

2022-01-17 02:06 UTC, Gh0stSp1der commented on _posts/blog/2022-01-10-MOP.markdown
> +etcd_keygen sub { test => shift;};
`sub` 바디안에 `shift;`뒤는 안 띄었넹
`etcd_keygen sub { test => shift; };`

2022-01-17 02:13 UTC, Gh0stSp1der approved these changes

2022-01-17 02:13 UTC, Gh0stSp1der commented on _posts/blog/2022-01-10-MOP.markdown
> +4. `_generate_initialize_object`
여기도 개행

2022-01-17 05:27 UTC, john3991005 commented on _posts/blog/2022-01-10-MOP.markdown
> +2. `class->_construct_meta`
* `initalize` -> 'initialize' 오타입니다~!

2022-01-17 06:37 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +2. `class->_construct_meta`
오타 수정했습니다.
실제 렌더링 되면 정상적으로 동작합니다. https://kjy8901.github.io/blog/2022/01/10/MOP.html

2022-01-17 06:37 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +3. `_initialize_object`
실제 렌더링 되면 정상적으로 동작합니다. https://kjy8901.github.io/blog/2022/01/10/MOP.html

2022-01-17 06:38 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +그래서 MOP에 관련된 내용을 Perl의 OOP 중 경량화 버전인 [Mouse](https://metacpan.org/pod/Mouse)를 사용해서 설명해보려고 합니다.
수정했습니다

2022-01-17 06:38 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +`has` 메서드를 보면 Meta::Class의 `initialize` 함수를 호출하는 것을 알 수 있습니다. 순서대로 의미 있는 부분을 추적해보면
수정했습니다.

2022-01-17 06:38 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +3. `_initialize_object`
실제 렌더링 되면 정상적으로 동작합니다. https://kjy8901.github.io/blog/2022/01/10/MOP.html

2022-01-17 06:38 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +마지막 `_generate_initialze_object` 함수까지 왔습니다. 함수 이름에서도 알 수 있듯이 이 함수에서는 객체를 생성합니다.
수정했습니다.

2022-01-17 06:38 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +이 함수의 코드 일부를 보면 `has`로 속성을 선언하면서 사용한 옵션들(`has_default`, `is_lazy` 등)을 체크하여 코드를 변경하여서
실제 렌더링 되면 정상적으로 동작합니다. https://kjy8901.github.io/blog/2022/01/10/MOP.html

2022-01-17 06:39 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +그리고 아랫부분의 `init_meta` 메서드를 보면 `apply_metaroles`를 사용하는 데 이 메서드를 사용하여 기존의 메타 클래스의 역할을 변경할 수 있습니다.
수정했습니다

2022-01-17 06:39 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +);
헤헿ㅅ 수정완료

2022-01-17 06:40 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +    if(ref($self) ne __PACKAGE__){
마우스 코드원본이라 그냥 가지고 왔는데 수정하는게 좋을까요? 아래껏도여

2022-01-17 06:40 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +etcd_keygen sub { test => shift;};
수정했습니당

2022-01-17 06:56 UTC, potatogim requested changes

2022-01-17 06:56 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +`has`     : 속성을 선언하기위한 예약어
요 부분은 마크다운 목록으로 표현하면 좋겠네요~!

2022-01-17 06:56 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +아래는 `lib/Mouse.pm`의 코드입니다. 그중 일부를 보면 `setup_import_methods`라는 함수로 일반적으로 Perl에서 속성을 선언할 때 위와 같은 형태로 작성할 텐데 MOP를 사용하지 않는 언어에서 `has`는 일반적인 예약어로 볼 수 있습니다.
MOP를 사용하지 않는 언어는 너무 포괄적인 서술인 것 같네요.

Moose/Mouse 등의 MOP를 구현한 프레임워크로 국한되도록 정확히 표현을 해주는게 좋겠습니다.

`또한 일반적으로 Perl에서 속성을 선언할 때` 라는 표현도 Perl에서 Moose/Mouse를 사용하지 않는 경우가 있음을 고려해볼 때에 정확한 표현이라고 보기 어렵다고 보여집니다.

2022-01-17 06:56 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +그리고 `eval $source`부분을 통해 코드를 생성해 반환합니다.
* \`eval $source\`부분을 -> \`eval $source\` 부분을

2022-01-17 06:56 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +Mouse에서 Class 마지막에 `__PACKAGE__->meta->make_immutable`또는 `__PACKAGE__->meta->make_immutable(inline_constructor => 0)`을 작성하는데요.
* Class 마지막에 -> 클래스 마지막에
* \`\_\_PACKAGE\_\_->meta->make_immutable\`또는 -> \`\_\_PACKAGE\_\_->meta->make_immutable\` 또는

2022-01-17 09:52 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +`has`     : 속성을 선언하기위한 예약어
수정했습니다~

2022-01-17 09:52 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +아래는 `lib/Mouse.pm`의 코드입니다. 그중 일부를 보면 `setup_import_methods`라는 함수로 일반적으로 Perl에서 속성을 선언할 때 위와 같은 형태로 작성할 텐데 MOP를 사용하지 않는 언어에서 `has`는 일반적인 예약어로 볼 수 있습니다.
수정했습니다~

2022-01-17 09:52 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +Mouse에서 Class 마지막에 `__PACKAGE__->meta->make_immutable`또는 `__PACKAGE__->meta->make_immutable(inline_constructor => 0)`을 작성하는데요.
수정했습니다~

2022-01-18 00:28 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +그리고 `eval $source`부분을 통해 코드를 생성해 반환합니다.
수정했습니다

2022-01-18 00:28 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +sub _initialize_object{
여기도 마우스 코드 원본이기는 한데 여기는 수정했습니다

2022-01-19 06:54 UTC, potatogim commented
테스트

2022-01-21 09:01 UTC, potatogim commented on _posts/blog/2022-01-10-MOP.markdown
> +* `Mouse::Meta::Method` -> `lib/Mouse/Meta/Method.pm`
```
* 클래스(`package Sample`): `Mouse:Meta::Class`
* 속성(`has 'test'`): `Mouse::Meta::Attribute`
* 메서드(`sub method`): `Mouse::Meta::Attribute`
```

요런 식으로 표현하면 조금 더 읽기가 편하게 느껴지는데 어때요?

2022-01-24 01:35 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +MOP에 관련된 내용을 Perl의 객체 지향 프로그래밍(Object-Oriented Programming) 중 경량화 버전인 [Mouse](https://metacpan.org/pod/Mouse)를 사용해서 설명해보려고 합니다.
수정했습니다~

2022-01-24 01:35 UTC, kjy8901 commented on _posts/blog/2022-01-10-MOP.markdown
> +* `Mouse::Meta::Method` -> `lib/Mouse/Meta/Method.pm`
수정했습니다~

2022-01-24 05:08 UTC, jhyuno approved these changes

2022-01-24 05:31 UTC, merged