spdk post initial commit
gluesys/tech-blog pull request #92
Opened 2022-02-15 08:59 UTC by john3991005

SPDK 개요 및 특징에 대한 소개(를 시도한) 포스트입니다.

피드백 부탁드립니다.

감사합니다.

2022-02-16 02:29 UTC, Gh0stSp1der approved these changes
Approve는 미리 눌러놓겠습니다~

2022-02-16 02:29 UTC, Gh0stSp1der commented on _posts/blog/2022-02-21-SPDK_1.markdown
> +&nbsp;
이렇게 끝낼 수는 없지, 간단하게 성능 비교 내용이 추가되면 좋을 것 같습니다.
간단하게는 요 사이트를 참고하시면 좋을 것 같구요. : https://spdk.io/news/2021/12/23/Performance_Regression_Dashboards/
포스팅 내용으로는 performance report를 매 버전마다 제공하고 있으며 : https://spdk.io/doc/performance_reports.html
상세한 데이터 값은 자체 구축한 grafana 인터페이스를 통해 확인할 수 있다. : https://performance.spdk.io/
정도면 될 것 같습니다.

2022-02-16 07:18 UTC, Gh0stSp1der approved these changes

2022-02-17 12:14 UTC, john3991005 commented on _posts/blog/2022-02-21-SPDK_1.markdown
> +최신 NVMe 기술을 적용한 고성능 저 지연 스토리지 미디어의 사용이 보편화되면서, 스토리지 소프트웨어 단에서의 오버헤드가 주목받게 되었습니다. 지금까지 CPU, 메모리, 그리고 스토리지를 잇는 구조에서 입출력 성능을 좌지우지하는 것은 항상 스토리지 하드웨어였습니다. 하드디스크를 위시한 전통적인 스토리지 미디어는 CPU나 메모리에 비해 현저히 느리고, 그
스토리지 소프트웨어 계층에서의~ 로 변경했습니다!

2022-02-17 12:15 UTC, john3991005 commented on _posts/blog/2022-02-21-SPDK_1.markdown
> +&nbsp;
마지막에 성능 결과 보고서 관련 내용 추가했습니다~!

2022-02-17 14:08 UTC, AngeliKaroS requested changes

2022-02-18 01:00 UTC, john3991005 commented on _posts/blog/2022-02-21-SPDK_1.markdown
> +**SPDK**는 고성능 스토리지 애플리케이션을 개발하기 위해 드라이버, 라이브러리, 애플리케이션을 모아 놓은 오픈소스 개발 키트입니다. 최신 저 지연 플래시 스토리지 미디어, 특히 NVMe SSD의 본 성능을 최대한 뽑아내기 위해 디자인되었습니다. SPDK 프로젝트는 인텔의 주도로 2013년에 시작되었으며, 2015년에 BSD 라이선스 기반으로 깃허브(
관련 부분에 전부 띄어쓰기 넣었습니다~!

2022-02-18 01:00 UTC, john3991005 commented on _posts/blog/2022-02-21-SPDK_1.markdown
> +SPDK는 각종 드라이브와 헤더파일 등을 모아 놓은 라이브러리와 해당 라이브러리를 기반으로 구성된 애플리케이션 들의 집합입니다. SPDK 라이브러리는 기본적으로 C로 구성된 코드들이 담겨 있으며, 하위 디렉토리로 lib과 module가 있습니다. lib 디렉토리는 SPDK를 구성하는 기본 라이브러리가 있으며, 이를 응용한 플러그인들이 module 디렉토리
'...lib와 module이 있습니다.' 로 변경했습니다~!

2022-02-18 01:09 UTC, AngeliKaroS approved these changes

2022-02-18 06:24 UTC, kjy8901 approved these changes

2022-02-18 07:59 UTC, merged