lustre-tech-blog
gluesys/tech-blog pull request #98
Opened 2022-06-30 04:47 UTC by weed700

Lustre, GPU_Direct_Storage

2022-06-30 05:22 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +# Lustre FS 특징 및 기능
해당 포스팅의 목적성이 무엇인지 파악하기가 어렵네요~

제목은 Lustre 파일시스템 소개와 더불어 GDS에 대한 개요 정도로 보여지는데 실제 내용은 HSM과 PCC에 초점이 맞춰져 있어서 정확히 어떤 말을 전달하고 싶은지 파악이 어렵습니다.

* Lustre 개요에 대한 내용이 보강되면 좋겠습니다.
* GDS에 대한 내용이 보강이 필요해보입니다.

앞서 Lustre/GDS에 관한 포스팅이 기본 내용을 충분하게 서술하고 있지 않기 때문에 이러한 개요를 먼저 소개한 후에 HSM/PCC에 대한 내용을 소개하는게 좋겠네요.

2022-06-30 05:27 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +title:      "Lustre File System과 GPU Direct Storage 소개"
* File System -> 파일시스템

2022-06-30 05:27 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +High Performance Computing(HPC) 클러스터는 대규모 애플리케이션에 최고의 컴퓨팅 성능을 제공하기 위해 사용됩니다. `HPC` 클러스터에서는 많은 양의 데이터를 처리합니다. 꽤 오랜 시간 동안 프로세서와 메모리의 속도는 급격히 증가했지만 I/O 시스템의 성능은 이보다 뒤처지고 있습니다. 따라서 상대적으로 성능이 떨어지는 I/O 성능은
* `고성능 컴퓨팅(High Performance Computing, 이하 HPC)` 등과 같이 국문 서술을 우선하되 약어에 대한 정보와 해당 표기를 사용할 것임을 명시해주는게 좋겠습니다.
* lustre File System` -> Lustre 파일시스템

2022-06-30 05:27 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +`러스터(Lustre)`는 병렬 분산 파일 시스템으로 주로 고성능 컴퓨팅의 대용량 파일 시스템으로 사용되고 있습니다.
국문/영문에 대한 표기는 매번 반복해서 괄호로 병행 표기할 필요는 없습니다.

글 내에서 처음 해당 표현이 나타날 때에 이후부터는 어떻게 표기할 것임을 명시하고 병행 표기하지 않도록 해주세요.

2022-06-30 05:27 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +* Lustre clients
* `Lustre clients` -> `Lustre 클라이언트`

2022-06-30 05:39 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +* HSM Architecture
* `HSM Architecture` -> `HSM 아키텍처` 혹은 `HSM 구조`

2022-06-30 05:39 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +<center>그림 2. HSM Architecture </center>
마찬가지~!

2022-06-30 05:39 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +  * 파일을 `HSM` 스토리지에 복사하는 프로세스를 `아카이브(Archive)`라고 하고 아카이브가 완료되면 러스터 파일 시스템에 존재하는 데이터를 삭제할 수 있습니다. 이것을 `Release`라고 말합니다. `HSM`스토리지에서 러스터 파일 시스템으로 데이터를 반환하는 프로세스를 `restore`라 하고 여기서 말하는 restore와 archive는
국문/영문 표기가 많이 섞여있네요~

국문 표기를 우선하되 용어 표기는 통일해주면 좋겠습니다.

2022-06-30 05:39 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +  * archive : 러스터 파일 시스템 파일에서 `HSM` 솔루션으로 데이터를 복사합니다.
이러한 용어들은 구문 강조를 넣어주면 좋겠네요.

* `archive`: ...
* `release`: ...
* ...

2022-06-30 05:39 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +참고
본문의 특정 내용과 직접적인 연관이 있는 링크들은 각주로 처리해주고, 링크들은 아래 예시를 참고해서 해당 링크의 제목을 병행 표기해주세요.

* Introduction to Lustre - Lustre Wiki: https://wiki.lustre.org/Introduction_to_Lustre

2022-06-30 06:26 UTC, john3991005 reviewed
작성하시느라 고생 많으셨습니다.
오타랑 양식 통일 부분 확인 부탁드립니다~!

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +`PCC`는 데이터 동기화를 위해 `HSM` 기술을 사용합니다. `HSM copytool`을 사용하여 로컬 캐시에서 `OST`로 파일을 복원합니다. 각 `PCC`에는 고유한 아카이브 번호로 실행되는 copytool 인스턴스가 있고 다른 러스터 클라이언트에서 접근하게 되면 데이터 동기화가 진행됩니다. `PCC`가 있는 클라이언트가 오프라인 될 시 캐시 된
* (양식) `고유한 아카이브 번호로 실행되는 copytool 인스턴스가 있고...` 에서 copytool을 일관성 있게 `copytool` 로 하는게 필요해 보입니다.

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +## OverStriping
* (오타) `OverStriping` -> `Overstriping`

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +
* (의견) 위에 간단하게 적으시긴 했지만, 이 부분에 오버스트라이핑의 이점에 대한 그림의 설명이 있으면 좋을 것 같습니다. 그림에서 보시다시피, 단일 스트라이핑은 노드 수가 많아도 일관적으로 낮은 성능을 보이는 반면, 오버스트라이핑은 성능 증가가 보인다 와 같은 설명 정도로 하는거는 어떠신가요. 단순 제안입니다.

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +<center>그림 5. overstriping Performance</center>
* (오타) `overstriping Performance` -> `Overstriping Performance`
 * 아니면 지현씨 코멘트 대로 국문으로 쓰는거도 좋아 보일거 같습니다.

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +`lustre FS`는 현재 대용량 파일에 최적화되어 있습니다. 이로 인해 파일 크기가 너무 작은 단일 파일일 경우 성능이 크게 저하되는 문제가 있습니다. `DoM`은 작은 파일을 `MDT`에 저장하여 이러한 문제를 해결합니다. `DoM`을 이용해서 `MDT`에 작은 파일을 저장하였을 때 추가적으로 `OST`에 접근할 필요가 없어 작은 I/O에 대한 성능
* (오타) `lustre FS` -> `Lustre FS`
 * (양식) `Lustre` 용어를 이전 처럼 국문으로 표기할 지, 영문으로 표기할 지 통일이 필요해 보입니다.
 * (양식) 표기를 DoM 또는 DOM 중 하나로 통일이 필요해 보입니다.

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +`lustre` version 2.4에서는 볼륨의 각 디렉터리 마다 `MDT`를 정해서 동시에 사용하는 구조 였지만, 버전 2.7 이 후에는 Single Directory환경에서 여러개의 Multiple MDT를 분산 형태로 사용할 수 있도록 변경되었습니다. 이를 `Lustre`에서는 단계별로 표현을 하고 있습니다. 1단계 Remote directorie
* (오타) `lustre` -> `Lustre`

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +**GPU Direct 스토리지 기술을 lustre에서도 이번에 출시된 버전 2.15.0에서 지원한다고 합니다**(https://wiki.lustre.org/Lustre_2.15.0_Changelog).
* (오타) `GPU Direct 스토리지 기술을 lustre에서도...` -> `GPU Direct 스토리지 기술을 Lustre에서도`

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +* NVMe 이전 블러그 참고 : https://tech.gluesys.com/blog/2021/03/03/NVMe_1.html
* (오타) `NVMe 이전 블러그 참고...` -> `NVMe 이전 블로그 참고...`

2022-06-30 06:26 UTC, john3991005 commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +이번 포스팅에서는 lustre가 무엇인지 어떤 기능을 가지고 있는지와 GPU Direct Storage에 대해 간략하게 알아보았습니다. 다음 시간에서는 lustre FS을 구성하는 실습과 구성 후 각 기능을 이용한 테스트 및 성능 측정을 해보도록 하겠습니다. 감사합니다~👍
* (오타) `이번 포스팅에서는 lustre가...` -> `이번 포스팅에서는 Lustre가...`
 * (오타) `다음 시간에서는 lustre FS을...` -> `다음 시간에서는 Lustre FS을...`

2022-06-30 07:01 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +이번 포스팅에서는 lustre가 무엇인지 어떤 기능을 가지고 있는지와 GPU Direct Storage에 대해 간략하게 알아보았습니다. 다음 시간에서는 lustre FS을 구성하는 실습과 구성 후 각 기능을 이용한 테스트 및 성능 측정을 해보도록 하겠습니다. 감사합니다~👍
* `lustre FS` -> `Lustre 파일시스템`

2022-07-04 02:59 UTC, Gh0stSp1der approved these changes
음.. 오탈자가 몇 개 보이네요. 최종본에는 오탈자 검수를 완료하면 좋겠습니다.
첫 포스팅일 텐데 작성하시느라 고생 많으셨습니다.
리뷰는 개인적인 의견일 뿐이니 참고하셔서 자유롭게 반영하시면 되겠습니다.
미리 Approve 누르겠습니다.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +`HPC` 클러스터는 대규모 애플리케이션들이 최상의 컴퓨터 성능을 발휘할 수 있게 합니다. 이처럼 HPC 클러스터는 대규모 애플리케이션들을 다루기때문에 많은 양의 데이터를 처리하게 됩니다. 지난 세월동안 프로세서와 메모리의 속도의 발전 속도에 비해 I/O를 처리하는 시스템의 발전은 느려 대용량의 데이터를 처리할 때 클러스터의 전체 성능을 저하 시킬 수 있
HPC 클러스터 환경에서 Lustre가 필요한 이유를 설명하기 위해 `'스토리지의 발전이 컴퓨팅 발전보다 느리다.'` 라는 관점에서 내용을 풀려고 하는 것 같습니다.
다양한 분야의 구독자가 위 주장에 대해 받아들이기 어려울 것 같습니다.
왜냐하면 CPU와 메모리와 마찬가지로 스토리지도 다양한 노력으로 고도의 하드웨어의 발전이 있었는데(e.g. 테이프 -> 디스크 -> 플래시 메모리 -> PCIe 기반 플래시 메모리 -> PCIe 기반 스토리지 네트워크 통신 기술), 이러한 노력이 CPU/메모리에 비해 부족했다? 라는 생각은 저마다 다를 것 같습니다.

스토리지 발전 vs 컴퓨팅 발전 구도보다, 차라리 `'HPC 클러스터에는 병렬 컴퓨팅 처리도 중요한데, 병렬 데이터 처리 또한 중요하다.'` 라는 식으로 `'너희가 모르는 병렬 스토리지 분야가 있어~'` 로 분야를 소개하면서 자연스럽게 Lustre로 연결해보면 어떨까 싶습니다.

짧게 작성해봤습니다. 참고되시면 좋겠습니다.


`HPC 클러스터는 고도의 컴퓨팅 성능이 필요한 환경으로, 대규모의 애플리케이션들이 많은 양의 데이터를 처리합니다.
개발자는 HPC 애플리케이션 개발을 위해 병렬 처리를 위한 표준 라이브러리인 MPI(Message Passing Interface)를 이용하거나, MapReduce, Spark 등의 병렬 처리 프레임워크를 사용했습니다.
HPC 클러스터는 컴퓨팅 성능 외에도 대규모의 데이터를 다룰 수 있는 병렬 스토리지를 필요로 합니다.
대표적으로 병렬/분산 스토리지 분야에서 구글(Google)의 GFS(Google File System)와 이를 모티브한 오픈 프로젝트인 HDFS(Hadoop Distributed File System)등이 있지만, 두 프로젝트 모두 대용량의 데이터를 저장하는데 초점이 맞춰있습니다.
HPC 클러스터 환경은 이보다 작은 규모의 스토리지 환경에서 다수의 애플리케이션이 실시간으로 데이터에 동시 접근하기 때문에 보다 빠르고 더 작은 크기의 I/O 처리를 요구합니다.`

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +`러스터(Lustre)`는 분산 파일시스템의 한 유형인 병렬 파일시스템입니다. 러스터와 일반 분산 시스템의 차이점은 데이터와 메타데이터가 저장되는 방식에 있습니다. 분산 파일시스템은 단일 스토리지 노등에 파일을 저장하는 반면 병렬 파일시스템은 일반적으로 파일을 분할하고 여러 스토리지 노드에 데이터 블록을 나누어 저장합니다. 메타데이터는 일반적으로 효율적인
Lustre를 설명하다가 병렬 vs 분산 스토리지에 대한 이야기가 깊어지면서 단락의 목적이 흐려지네요.
병렬 vs 분산 스토리지에 대한 설명과, Lustre에 대한 소개가 나뉘면 좋겠습니다.
추가로 무언가에 대한(e.g. 병렬 vs 분산 스토리지) 차이점에 대해 설명할 때에는 익숙하지 않은 구독자를 위해 표를 첨부하면 더욱 좋습니다.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +# 러스터 파일 소개
리뷰하고 보니 러스터 `'파일시스템 소개'`보다 `'병렬/분산 파일시스템'` 문단으로 표기하면 아래 설명들이 명확해져서 좋아보입니다.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +# 러스터 파일시스템 아키텍처
이 문단부터 본격적으로 Lustre에 대한 소개 내용이네요.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +러스터라는 이름의 유래는 `Linux`와 `Clustre`의 혼성어로 탄생하였습니다.
아래 Lustre에 대한 소개의 시작말로 간단한 Lustre에 대한 설명과 같이 첨부하면 좋겠습니다.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +<center>그림 1. 러스터 파일시스템 아키텍처 </center>
외부 이미지인가요? 참고한 이미지라면 출처가 필요합니다. 출처는 각주로 넣어주면 좋겠네요.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +아래는 [그림 1]에서 볼 수 있는 러스터를 구성하는데 필요한 각 구성요소의 역할을 설명합니다.
`'아래는'` 으로 시작해서 위에 그려진 `[그림 1]`을 설명하는 문장이 자연스럽지 않네요.

짧게 수정해봤습니다.

`위 [그림 1]은 러스터 아키텍처를 표현한 것으로 각각의 구성요소와 역할은 다음과 같습니다.`

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +* HSM 아키텍처
요건 굳이 필요 없어 보이네요. 넣는다면 위에 Lustre 아키텍처에도 똑같이 넣어야 합니다.

글을 읽다가 구성이 묘하게 달라지면 읽는이가 헷갈릴 수 있습니다.

글의 구성은 전반적으로 통일되어여 합니다.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +
위에 [그림 1]을 넣고 구성요소와 역할을 설명하는 내용처럼 그림과 내용을 연결해주는 문장이 짧게 있으면 좋겠네요.

그런데 아래 내용들이 무엇을 설명하려는지 모르겠네요. [그림 2]의 동작 방식을 설명하고자 하는걸까요?

그렇다면 `위 [그림 2]는 HSM 아키텍처를 나타내며, HSM 동작 방식은 다음과 같습니다.` ?? 맞나요?

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +
[72L](https://github.com/gluesys/tech-blog/blame/lustre/_posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown#L72)의 `* HSM 아키텍처` 처럼, 구성 통일이 필요합니다!

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +[root@lzfs-client ~]# lfs setstripe --stripe-count 4 [file or directory name] //OST가 4개일 때 4개의 스트라이프
터미널 같은 명령어 표현 구문에는 실제 데이터를 넣는게 좋습니다. 예시 처럼 `[file or directory name]`은 헷갈릴 수 있습니다. 뒤에 주석도 별도로 문장에서 설명하는게 좋습니다.

아래 예시를 참고하시면 좋겠습니다.

```console
[root@lzfs-client ~]# lfs setstripe --stripe-count 4 /mnt/test1
...
````
Lustre에서 스트라이핑 구성은 `lfs setstripe` 명령을 사용합니다. 이때 옵션으로 `--stripe-count`를 사용할 수 있으며, 이어서 파일명 또는 디렉토리명이 필요합니다. 예시에서는 `/mnt/test` 디렉토리명을 입력합니다.

---

다만 위 경우 설명이 많아져서 구독자로부터 피로감이 올 수 있는데, 글이 전반적으로 길 경우에는 주석을 안에 넣어도 괜찮겠습니다. 다만 명령어와 동일한 라인이 아닌, 이전 라인에 표현하면 좋겠습니다.

```console
// 스트라이핑 구성 명령어, --stripe-count 옵션에 이어서 디렉토리 또는 파일명을 입력한다.
[root@lzfs-client ~]# lfs setstripe --stripe-count 4 /mnt/test1
...

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +[root@MDS ~]# lctl get_param lod.*.dom_stripesize //DoM Stripe 크기를 확인
앞서 가이드 드렸던 오버스트라이핑 예시와 동일하게 표현되면 좋겠습니다.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +  * 소스에서 바운스 버퍼로 데이터 복사
두 가지에 다른 복사에 대한 설명이라면 `*` 보다 `1.`, `2.` 로 숫자로 표현하는게 좋겠습니다.

2022-07-04 02:59 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +  * 직접 데이터 경로에는 원본에서 대상으로 하나의 복사본만 있습니다. CPU가 데이터 이동을 수행할 경우 CPU 가용성에 대한 충돌로 인해 지연 시간이 영향을 받아 불안할 수 있습니다. GDS는 이러한 지연 문제를 완화합니다.
그리고 두 복사에 대한 설명인가요? 그러면 앞에 `* 바운스 버퍼를 사용하면..` 문장에 시작줄을 맞추면 좋겠습니다.

2022-07-04 04:32 UTC, john3991005 approved these changes

2022-07-19 04:26 UTC, potatogim requested changes
리뷰 확인해주세요~!

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +title:      "HPC를 위한 Lustre FS과 Gpu Direct Storage 개요"
* Lustre FS -> Lustre 파일시스템
* Gpu -> GPU

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +
본문은 헤더를 시작한 이후에 서술해주세요~

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +## 러스터 파일시스템 특징 및 기능
특징 및 기능이라고 서술하는 경우, 일반적인 Lustre의 특징과 기능으로 시작하는 것이 적합해보이는데 실제로는 HSM과 PCC만 서술되어 있어 흐름이 어색합니다. 차라리 HSM과 PCC를 2번째 헤더 수준으로 올려서 서술하는게 좋을 것 같네요.

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +  * 러스터 파일 시스템을 하나 이상의 외부 스토리지 시스템에 연결할 수 있습니다.
"파일 시스템"과 "파일시스템"을 혼용하지 말고 "파일시스템"으로 통일해서 서술해주세요.

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +`PCC`는 러스터 클라이언트 측에서 로컬 캐시 그룹을 제공하는 프레임워크입니다. 각 클라이언트는 OST대신 로컬 저장 장치를 자체 캐시로 사용합니다. 로컬 파일 시스템은 로컬 저장장치 안에 있는 캐시 데이터를 관리하는 데 사용됩니다. 캐시 된 I/O의 경우 로컬 파일 시스템으로 전달되어 처리되고 일반 I/O는 OST로 전달됩니다.
* OST대신 -> OST 대신
* 앞서 "파일시스템"과 마찬가지로 "저장 장치", "저장장치"가 혼용되고 있는데 통일시켜주세요.

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +PCC는 데이터 동기화를 위해 HSM 기술을 사용합니다. `HSM copytool`을 사용하여 로컬 캐시에서 OST로 파일을 복원합니다. 각 PCC에는 고유한 아카이브 번호로 실행되는 `copytool` 인스턴스가 있고 다른 러스터 클라이언트에서 접근하게 되면 데이터 동기화가 진행됩니다. PCC가 있는 클라이언트가 오프라인 될 시 캐시 된 데이터는 일시적
* `HSM copytool`이 고유 명사는 아닌 것 같은데... `copytool` 쪽만 하이라이팅이 들어가는게 좋겠네요.
* copytool에 하이라이팅이 빠진 부분이 있네요.

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +* PCC 이점
장점만 기술되어 있는데 장/단점으로 분류해서 기술해주면 좋겠습니다.

추가로 제목을 목록으로 강조하기보다는 제목 헤더로 표현해주세요.

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +### Overstriping
* Overstriping -> 오버스트라이핑(Overstriping)

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +NVDIA는 위와 같은 문제를 해결하고 스토리지와 GPU 메모리간 데이터 이동을 간소화하기 위하여 `GDS(GPU Direct Storage)`를 만들었습니다.
* NVDIA -> NVIDIA

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +빅데이터, 인공지능, HPC 애플리케이션은 많은 연산을 수행하므로 빠른 연산을 위하여 CPU가 아닌 GPU로 연산을 처리합니다. 하지만 현재 GPU를 사용할 때 I/O가 바로 GPU로 가는 것이 아니라
* I/O -> 입출력

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +CPU를 거치고 GPU로 가기때문에 연산을 처리하는 성능에 있어서 주요 병목 현상이 될 수 있습니다.
* 가기때문에 -> 가기 때문에

2022-07-19 04:26 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +GDS의 이점은 다음과 같습니다.
마찬가지로 장/단점은 제목 수준으로 분류해주면 좋겠네요.

2022-07-19 08:54 UTC, potatogim requested changes
오타~!

2022-07-19 08:54 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +* Wath is PCC - Lustre whamcloud community: https://jira.whamcloud.com/browse/LU-10092
* Wath -> What

2022-07-19 08:54 UTC, potatogim commented on _posts/blog/2022-06-30-lustre_GPU_Direct_Storage.markdown
> +* Waht is overstripe - whamcloud LUG2019: https://wiki.lustre.org/images/b/b3/LUG2019-Lustre_Overstriping_Shared_Write_Performance-Farrell.pdf
* Wath -> What

2022-07-19 09:00 UTC, potatogim requested changes

2022-07-20 09:39 UTC, potatogim approved these changes

2022-07-21 10:55 UTC, merged