k8s_CSI
gluesys/tech-blog pull request #99
Opened 2022-06-30 05:36 UTC by Jade0829

pv,pvc,sc,csi driver

2022-06-30 05:46 UTC, potatogim commented
전체적인 양식에 대해서 기존 문서들을 참고해보면 좋겠네요~

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +* PVC&POD 생성 및 확인
* PVC&POD -> PVC & Pod

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +* SPDK Storage 서버 확인
* SPDK Storage 서버 확인 -> SPDK 스토리지 서버 확인

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +`PVC 생성 -> PV 생성 -> PVC-PV bound 확인 -> POD에 PVC 할당`
* POD -> Pod

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +* PV Yaml 파일 작성(test_pv.yaml)
* Yaml -> YAML

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +* PVC Yaml 파일 작성(test_pvc.yaml)
* Yaml -> YAML

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +        Retain : PVC가 삭제될 때 대응되는 PV 상태는 bound -> Released로 바뀌며 다른 PVC가 연결될 수 없는 상태이며 PV 속 데이터는 유지
이러한 목록들은 명시적인 목록 구문으로 작성해주세요.

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +    pvc는 사용자가 PV에 요구하는 스펙입니다. 사용하려는 용량, 접근 모드 등을 PV에 요청합니다.
* pvc -> PVC

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +    pv는 관리자가 사용자의 스토리지 요청에 맞게 프로비저닝하여 파드에서 사용할 수 있는 쿠버네티스 클러스터의
* pv -> PV

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +쿠버네티스 사용자 및 관리자에게 스토리지 사용 방법에서부터 제공 방법에 대한 세부 사항을 추상화하는 퍼시스턴트 볼륨(Persistent Volume, 이하 pv), 퍼시스턴트볼륨클레임(Persistent Volume Claim,이하 pvc)라는 두 가지 API 리소스를 사용한다.
* pv -> PV
* pvc -> PVC

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +위의 볼륨 유형 중 emptyDir는 파드가 노드에 할당될 때 생성되며 파드가 노드에서 제거되면 데이터가 영구적으로 삭제됩니다.
용어에 대해서는 고정폭으로 강조해주면 좋겠습니다.

* emptydir -> `emptydir`

2022-07-01 05:24 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +위의 볼륨 유형 중 emptyDir는 파드가 노드에 할당될 때 생성되며 파드가 노드에서 제거되면 데이터가 영구적으로 삭제됩니다.
* Pod에 대한 표기를 일관되게 작성해주세요.
    * https://github.com/gluesys/tech-blog/pull/98#discussion_r910616881
    * https://github.com/gluesys/tech-blog/pull/98#discussion_r910617919
    * https://github.com/gluesys/tech-blog/pull/98#discussion_r910644330

2022-07-04 06:35 UTC, Gh0stSp1der approved these changes
첫 기술 블로그 작성에 많은 정성을 들이신 것 같습니다. 고생 많으셨습니다.
최종본 적용 전에 오탈자 확인 후 진행하시면 좋겠습니다.
리뷰는 의견일 뿐이니 참고하셔서 적용할 부분만 적용하시면 됩니다.
Approve 미리 눌러놓겠습니다.

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +자~ 이제 관리자 입장에서 생각해봅시다.
이런 능글맞은 문장 좋습니당. 인사말에도 부드럽게 추가해 주세요 ㅠㅠ

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +사용자가 파드에 사용할 PVC를 생성했습니다. 이 때 관리자는 사용자가 PVC를 사용할 수 있도록 대응되는 PV를 만드는데 사용자가 적으면 대응되는 PV 만드는건 어렵지 않습니다. 하지만 사용자가 많아 PVC 요청이 많고 요청하는 시간이 제각각이라면 PVC에 해당되는 PV를 하나하나 만드는 것도 힘들 뿐 아니라 24시간 항시 PVC 요청을 확인하고 만들
`대응되는 PV 만드는건` -> `대응되는 PV를 만드는건`

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +사용자가 파드에 사용할 PVC를 생성했습니다. 이 때 관리자는 사용자가 PVC를 사용할 수 있도록 대응되는 PV를 만드는데 사용자가 적으면 대응되는 PV 만드는건 어렵지 않습니다. 하지만 사용자가 많아 PVC 요청이 많고 요청하는 시간이 제각각이라면 PVC에 해당되는 PV를 하나하나 만드는 것도 힘들 뿐 아니라 24시간 항시 PVC 요청을 확인하고 만들
`하지만 사용자가 많아 PVC 요청이 많고 ..` 음.. `많고 .. 많아..`.. `사용자가 많아` 부분을 빼도 자연스럽네요.
`하지만 PVC 요청이 많아지고 요청 시간이 제각각이라면..`

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +위와 같은 상황을 위해 쿠버네티스는 동적 프로비저닝을 제공합니다!!
주말 지나서 월요일에 쓰셨군요. 갑자기 화이팅이 넘칩니다. 포스팅 전체 느낌도 이렇게 ㄱㄱ

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +  쿠버네티스 CSI은 기본적으로 `Provsioner`, `Attacher`, `Controller`, `NodeServer`로 이루어져 있습니다.
`Provsioner` 오타 `Provisioner`

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +많은 CSI 드라이버 중 저번에 다뤄서 조금은 친숙한 `SPDK`에서 제공하는 SPDK CSI 드라이버를 알아보겠습니다.
간단하게 SPDK 설명도 추가해 주면서 지난 포스팅 링크도 추가해 주시면 더 좋겠습니다.

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +* SPDK 스토리지 서버 설정
글머리로 하는게 좋겠습니다.
`### SPDK 스토리지 서버 설정`

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +* 워커 노드 설정
요것도 글머리로?
`### 워커 노드 설정`

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +* 쿠버네티스 Master 노드 설정
크게 SPDK Target 설정, k8s worker 설정, k8s master 설정으로 나뉘는것 같은데..
목록 하위에 목록(아래 예시 참고) 형식으로 작성하다보니 완성된 포스팅에서 구분이 모호해 지는 것 같습니다.
```
* 블라 블라
  * 블라 블라
```

구분이 필요한 부분은 글머리로 나누면 자동으로 문장간의 간격이나, 라인이 생성되니 글머리로 구문할 수 있는 부분은 글머리로 나누는게 좋을 것 같습니다.
참고 : https://gist.github.com/ihoneymon/652be052a0727ad59601#this-is-an-h2

2022-07-04 06:35 UTC, Gh0stSp1der commented on _posts/blog/2022-06-30-CSI.markdown
> +* SPDK 스토리지 서버 확인
글머리 변경 검토! (이후 모두 포함)

2022-07-18 09:46 UTC, john3991005 approved these changes
작성하시느라 고생 많으셨습니다.
마지막으로 (개인적으로) 인사말 부분 문장들을 엔터로 나누어 내리는 것 보다, 문단으로 묶어서 나누는게 어떠신지 의견을 드립니다.
미리 어프루브 눌러놓겠습니다.
감사합니다~!

2022-07-18 09:46 UTC, john3991005 commented on _posts/blog/2022-06-30-CSI.markdown
> +이번 포스팅 내용은 쿠버네티스에서 동작하는 컨테이너들은 데이터를 어떻게 관리하는 지 알아보려합니다!!
(의견?) `이번 포스팅 내용은...` 로 시작하셨다면 `...쿠버네티스에서 동작하는 컨테이너의 데이터 관리 방법에 대한 소개입니다.` 로 끝나는게 좋을 것 같습니다.
아니면 `이번 포스트에서는 쿠버네티스에서 동작하는 컨테이너들이 데이터를 어떻게 관리하는 지 알아보고자 합니다.` 로 하는거도 좋을 것 같습니다.

2022-07-18 09:46 UTC, john3991005 commented on _posts/blog/2022-06-30-CSI.markdown
> +아!! 파드라는 용어도 모르실 수 있으니, 여기서 파드라는 개념은 쿠버네티스에서 생성하고 관리할 수 있는 최소한의 단위이며 파드는 단일 컨테이너일 수 있으며 또한 다중 컨테이너일 수도 있습니다.
(의견) `아!! 파드라는 용어도 모르실 수 있으니, 여기서...` 에서 문장을 어느정도 마무리하면 깔끔할거 같습니다. `아!! 파드라는 용어도 모르실 수 있으니 설명 드리자면, 파드는 쿠버네티스에서 생성하고...` 정도로 하면 좋을 것 같습니다.

2022-07-18 09:46 UTC, john3991005 commented on _posts/blog/2022-06-30-CSI.markdown
> +위의 볼륨 유형 중 `emptyDir`는 앞서 설명한 것과 같이 컨테이너 데이터를 임시로 저장하는 볼륨으로 파드가 삭제될 때 데이터가 영구적으로 삭제가 됩니다. 하지만 `emptyDir` 외 나머지 볼륨들은 파드가 제거되더라도 데이터는 유지되며 같은 내용을 서로 다른 파드들끼리 공유할 수 있습니다.
(의견) 쉼표를 사용하면 좋을 것 같습니다. 
 * `...앞서 설명한 것과 같이 컨테이너 데이터를...` -> `...앞서 설명한 것과 같이, 컨테이너 데이터를...`
 * `...파드가 제거되더라도 데이터는 유지되며 같은 내용을...` -> `...파드가 제거되더라도 데이터는 유지되며, 같은 내용을...`

2022-07-18 09:46 UTC, john3991005 commented on _posts/blog/2022-06-30-CSI.markdown
> +    <center>그림 1. PV-PVC Lifecycle</center>
(오타?) Lifecycle 띄어쓰기 통일하면 좋을 것 같습니다.

2022-07-18 09:46 UTC, john3991005 commented on _posts/blog/2022-06-30-CSI.markdown
> +사용자가 파드에 사용할 PVC를 생성했습니다. 이 때 관리자는 사용자가 PVC를 사용할 수 있도록 대응되는 PV를 만드는데 사용자가 적으면 대응되는 PV를 만드는 건 어렵지 않습니다. 하지만 사용자가 많아 PVC 요청이 많고 시간이 제각각이라면 PVC에 해당되는 PV를 하나하나 만드는 것도 힘들 뿐 아니라 24시간 항시 PVC 요청을 확인하고 만들 수도
(의견) 쉼표를 사용하면 좋을 것 같습니다.
 * `...PV를 만드는데 사용자가 적으면...` -> `...PV를 만드는데, 사용자가 적으면...`
 * `...힘들 뿐 아니라 24시간 항시 PVC 요청을...` -> `...힘들 뿐 아니라, 24시간 항시 PVC 요청을...`
 * `...기다려야 하고 그 시간이 길어지면...` -> `...기다려야 하고, 그 시간이 길어지면...`

2022-07-18 09:46 UTC, john3991005 commented on _posts/blog/2022-06-30-CSI.markdown
> +  * 워커 노드 전부 SPDK CSI 이미지를 생성 ,nvme-cli 모듈 설치
(오타) 쉼표 전후로 띄어쓰기 오류가 있어 보입니다.

2022-07-18 09:46 UTC, john3991005 commented on _posts/blog/2022-06-30-CSI.markdown
> +* PVC &  생성 및 확인
(오타?) `&` 뒤에 스페이스가 하나 더 있는데 어떤 단어가 들어가는 건가요?

2022-07-19 04:45 UTC, potatogim requested changes
리뷰 확인해주세요~!

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +  * emptyDir
각 유형에 대해서 표 형태로 작성해주면 좋겠네요~!

예)

| 이름 | 설명 |
| :---: | :--- |
| `hostPath` | ... |
| ... | ... |

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +    - Provisioning
* Provisioning -> 프로비저닝(Provisioning)

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +    - Binding
* Binding -> 바인딩(Binding)

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +    - Using
* 사용(Using)

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +    - Reclaiming
* 회수(Reclaiming)

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +      * Retain : PVC가 삭제될 때 대응되는 PV 상태는 bound -> Released로 바뀌며 다른 PVC가 연결될 수 없는 상태이며 PV 속 데이터는 유지합니다.
* 유지(Retain), 삭제(Delete), 재사용(Recycle) 혹은 재활용(Recycle)

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +* PVC YAML 파일 작성(test_pvc.yaml)
파일 이름은 코드 강조 내에서 첫 줄에 주석으로 추가해주고, 코드 강조는 console이 아니라 yaml로 해주세요~!

예)

```yaml
# test_pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
...
```

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +* PV YAML 파일 작성(test_pv.yaml)
마찬가지~!

2022-07-19 04:45 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +`PVC 생성 -> PV 생성 -> PVC-PV bound 확인 -> 파드에 PVC 할당`
단계를 그림이나 별도의 시각화를 해주면 좋겠네요.

2022-07-19 06:09 UTC, potatogim requested changes
리뷰 확인해주세요~!

2022-07-19 06:09 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +|`iSCSI`|아이스카시 볼륨|
* 아이스카시 -> iSCSI
* iSCSI 프로토콜에 대한 참고 링크를 각주로 달아주세요~!

2022-07-19 06:09 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +|`glusterfs`|글러스터(오픈 소스 네트워크 파일시스템) 볼륨|
* 글러스터 -> GlusterFS
* GlusterFS에 대한 참고 링크를 각주로 달아주세요~!

2022-07-19 06:09 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +|`nfs`|nfs(네트워크 파일시스템) 볼륨|
* nfs -> NFS

2022-07-19 06:09 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +쿠버네티스 사용자 및 관리자에게 스토리지 사용 방법에서부터 제공 방법에 대한 세부 사항을 추상화하는 퍼시스턴트 볼륨(Persistent Volume, 이하 PV), 퍼시스턴트볼륨클레임(Persistent Volume Claim, 이하 PVC)이라는 두 가지 API 리소스를 사용합니다.
* 퍼시스턴트볼륨클레임 -> 퍼시스턴트 볼륨 클레임

2022-07-19 08:48 UTC, Jade0829 commented on _posts/blog/2022-06-30-CSI.markdown
> +|`iSCSI`|아이스카시 볼륨|
수정 완료했습니다~

2022-07-19 08:49 UTC, Jade0829 commented on _posts/blog/2022-06-30-CSI.markdown
> +|`glusterfs`|글러스터(오픈 소스 네트워크 파일시스템) 볼륨|
수정 완료했습니다~

2022-07-19 08:57 UTC, potatogim requested changes
오타~!

2022-07-19 08:57 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +[^7]: iSCI : https://ko.wikipedia.org/wiki/ISCSI
* iSCI -> iSCSI

2022-07-19 08:58 UTC, potatogim requested changes

2022-07-19 08:58 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +  * 쿠버네티스 PV, PVC - https://kubernetes.io/ko/docs/concepts/storage/persistent-volumes/
제목 앞뒤로 개행 추가~!

2022-07-20 00:01 UTC, Jade0829 commented on _posts/blog/2022-06-30-CSI.markdown
> +  * 쿠버네티스 PV, PVC - https://kubernetes.io/ko/docs/concepts/storage/persistent-volumes/
수정완료했습니다~

2022-07-20 00:01 UTC, Jade0829 commented on _posts/blog/2022-06-30-CSI.markdown
> +[^7]: iSCI : https://ko.wikipedia.org/wiki/ISCSI
수정완료했습니다~

2022-07-21 08:26 UTC, merged

2023-08-01 07:06 UTC, john3991005 commented on _posts/blog/2022-06-30-CSI.markdown
> +## CSI(Container Storage Instance) 드라이버
뒷북이지만 여기 오타 발견했습니다:
CSI(Container Storage Instance) 드라이버
--> CSI(Container Storage Interface) 드라이버

2023-08-02 04:51 UTC, potatogim commented on _posts/blog/2022-06-30-CSI.markdown
> +## CSI(Container Storage Instance) 드라이버
@Jade0829 요거 확인 좀 부탁할게요~!